// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _canny_edge_HH_
#define _canny_edge_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Block_Mat_exit27932_s.h"
#include "Loop_1_proc.h"
#include "Duplicate.h"
#include "Sobel.h"
#include "Sobel_1.h"
#include "gradient_decompositi.h"
#include "nonmax_suppression.h"
#include "hysteresis.h"
#include "Loop_2_proc.h"
#include "fifo_w20_d2_A.h"
#include "fifo_w8_d2_A.h"
#include "fifo_w20_d7_A.h"
#include "fifo_w16_d2_A.h"
#include "start_for_Duplicate_U0.h"
#include "start_for_Loop_2_proc_U0.h"
#include "start_for_Sobel_U0.h"
#include "start_for_Sobel_1_U0.h"
#include "start_for_gradient_decompositi_U0.h"
#include "start_for_nonmax_suppression_U0.h"
#include "start_for_hysteresis_U0.h"
#include "canny_edge_CONTROL_BUS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32>
struct canny_edge : public sc_module {
    // Port declarations 28
    sc_in< sc_logic > s_axi_CONTROL_BUS_AWVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_AWREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_ADDR_WIDTH> > s_axi_CONTROL_BUS_AWADDR;
    sc_in< sc_logic > s_axi_CONTROL_BUS_WVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_WREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH> > s_axi_CONTROL_BUS_WDATA;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH/8> > s_axi_CONTROL_BUS_WSTRB;
    sc_in< sc_logic > s_axi_CONTROL_BUS_ARVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_ARREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_ADDR_WIDTH> > s_axi_CONTROL_BUS_ARADDR;
    sc_out< sc_logic > s_axi_CONTROL_BUS_RVALID;
    sc_in< sc_logic > s_axi_CONTROL_BUS_RREADY;
    sc_out< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH> > s_axi_CONTROL_BUS_RDATA;
    sc_out< sc_lv<2> > s_axi_CONTROL_BUS_RRESP;
    sc_out< sc_logic > s_axi_CONTROL_BUS_BVALID;
    sc_in< sc_logic > s_axi_CONTROL_BUS_BREADY;
    sc_out< sc_lv<2> > s_axi_CONTROL_BUS_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > interrupt;
    sc_in_clk AXI_LITE_clk;
    sc_in< sc_logic > ap_rst_n_AXI_LITE_clk;
    sc_in< sc_lv<32> > INPUT_data_V_TDATA;
    sc_out< sc_lv<32> > OUTPUT_data_V_TDATA;
    sc_in< sc_logic > INPUT_data_V_TVALID;
    sc_out< sc_logic > INPUT_data_V_TREADY;
    sc_out< sc_logic > OUTPUT_data_V_TVALID;
    sc_in< sc_logic > OUTPUT_data_V_TREADY;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    canny_edge(sc_module_name name);
    SC_HAS_PROCESS(canny_edge);

    ~canny_edge();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    canny_edge_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>* canny_edge_CONTROL_BUS_s_axi_U;
    Block_Mat_exit27932_s* Block_Mat_exit27932_U0;
    Loop_1_proc* Loop_1_proc_U0;
    Duplicate* Duplicate_U0;
    Sobel* Sobel_U0;
    Sobel_1* Sobel_1_U0;
    gradient_decompositi* gradient_decompositi_U0;
    nonmax_suppression* nonmax_suppression_U0;
    hysteresis* hysteresis_U0;
    Loop_2_proc* Loop_2_proc_U0;
    fifo_w20_d2_A* packets_cast_loc_c_U;
    fifo_w8_d2_A* src_bw_data_stream_0_U;
    fifo_w20_d7_A* packets_cast_loc_c35_U;
    fifo_w8_d2_A* src1_data_stream_0_s_U;
    fifo_w8_d2_A* src2_data_stream_0_s_U;
    fifo_w16_d2_A* sobel_gx_data_stream_U;
    fifo_w16_d2_A* sobel_gy_data_stream_U;
    fifo_w16_d2_A* grad_gd_data_stream_s_U;
    fifo_w16_d2_A* suppressed_data_stre_U;
    fifo_w8_d2_A* canny_edges_data_str_U;
    start_for_Duplicate_U0* start_for_Duplicate_U0_U;
    start_for_Loop_2_proc_U0* start_for_Loop_2_proc_U0_U;
    start_for_Sobel_U0* start_for_Sobel_U0_U;
    start_for_Sobel_1_U0* start_for_Sobel_1_U0_U;
    start_for_gradient_decompositi_U0* start_for_gradient_decompositi_U0_U;
    start_for_nonmax_suppression_U0* start_for_nonmax_suppression_U0_U;
    start_for_hysteresis_U0* start_for_hysteresis_U0_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<32> > rows_V;
    sc_signal< sc_lv<32> > cols_V;
    sc_signal< sc_lv<32> > threshold1;
    sc_signal< sc_lv<32> > threshold2;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_rst_n_AXI_LITE_clk_inv;
    sc_signal< sc_logic > Block_Mat_exit27932_U0_ap_start;
    sc_signal< sc_logic > Block_Mat_exit27932_U0_ap_done;
    sc_signal< sc_logic > Block_Mat_exit27932_U0_ap_continue;
    sc_signal< sc_logic > Block_Mat_exit27932_U0_ap_idle;
    sc_signal< sc_logic > Block_Mat_exit27932_U0_ap_ready;
    sc_signal< sc_lv<20> > Block_Mat_exit27932_U0_packets_cast_out_out_din;
    sc_signal< sc_logic > Block_Mat_exit27932_U0_packets_cast_out_out_write;
    sc_signal< sc_logic > Loop_1_proc_U0_ap_start;
    sc_signal< sc_logic > Loop_1_proc_U0_start_full_n;
    sc_signal< sc_logic > Loop_1_proc_U0_ap_done;
    sc_signal< sc_logic > Loop_1_proc_U0_ap_continue;
    sc_signal< sc_logic > Loop_1_proc_U0_ap_idle;
    sc_signal< sc_logic > Loop_1_proc_U0_ap_ready;
    sc_signal< sc_logic > Loop_1_proc_U0_start_out;
    sc_signal< sc_logic > Loop_1_proc_U0_start_write;
    sc_signal< sc_logic > Loop_1_proc_U0_packets_cast_loc_read;
    sc_signal< sc_logic > Loop_1_proc_U0_in_stream_data_V_TREADY;
    sc_signal< sc_lv<8> > Loop_1_proc_U0_src_bw_data_stream_0_V_din;
    sc_signal< sc_logic > Loop_1_proc_U0_src_bw_data_stream_0_V_write;
    sc_signal< sc_lv<20> > Loop_1_proc_U0_packets_cast_loc_out_din;
    sc_signal< sc_logic > Loop_1_proc_U0_packets_cast_loc_out_write;
    sc_signal< sc_logic > Duplicate_U0_ap_start;
    sc_signal< sc_logic > Duplicate_U0_start_full_n;
    sc_signal< sc_logic > Duplicate_U0_ap_done;
    sc_signal< sc_logic > Duplicate_U0_ap_continue;
    sc_signal< sc_logic > Duplicate_U0_ap_idle;
    sc_signal< sc_logic > Duplicate_U0_ap_ready;
    sc_signal< sc_logic > Duplicate_U0_start_out;
    sc_signal< sc_logic > Duplicate_U0_start_write;
    sc_signal< sc_logic > Duplicate_U0_src_data_stream_V_read;
    sc_signal< sc_lv<8> > Duplicate_U0_dst1_data_stream_V_din;
    sc_signal< sc_logic > Duplicate_U0_dst1_data_stream_V_write;
    sc_signal< sc_lv<8> > Duplicate_U0_dst2_data_stream_V_din;
    sc_signal< sc_logic > Duplicate_U0_dst2_data_stream_V_write;
    sc_signal< sc_logic > Sobel_U0_ap_start;
    sc_signal< sc_logic > Sobel_U0_ap_done;
    sc_signal< sc_logic > Sobel_U0_ap_continue;
    sc_signal< sc_logic > Sobel_U0_ap_idle;
    sc_signal< sc_logic > Sobel_U0_ap_ready;
    sc_signal< sc_logic > Sobel_U0_start_out;
    sc_signal< sc_logic > Sobel_U0_start_write;
    sc_signal< sc_logic > Sobel_U0_p_src_data_stream_V_read;
    sc_signal< sc_lv<16> > Sobel_U0_p_dst_data_stream_V_din;
    sc_signal< sc_logic > Sobel_U0_p_dst_data_stream_V_write;
    sc_signal< sc_logic > Sobel_1_U0_ap_start;
    sc_signal< sc_logic > Sobel_1_U0_ap_done;
    sc_signal< sc_logic > Sobel_1_U0_ap_continue;
    sc_signal< sc_logic > Sobel_1_U0_ap_idle;
    sc_signal< sc_logic > Sobel_1_U0_ap_ready;
    sc_signal< sc_logic > Sobel_1_U0_p_src_data_stream_V_read;
    sc_signal< sc_lv<16> > Sobel_1_U0_p_dst_data_stream_V_din;
    sc_signal< sc_logic > Sobel_1_U0_p_dst_data_stream_V_write;
    sc_signal< sc_logic > gradient_decompositi_U0_ap_start;
    sc_signal< sc_logic > gradient_decompositi_U0_ap_done;
    sc_signal< sc_logic > gradient_decompositi_U0_ap_continue;
    sc_signal< sc_logic > gradient_decompositi_U0_ap_idle;
    sc_signal< sc_logic > gradient_decompositi_U0_ap_ready;
    sc_signal< sc_logic > gradient_decompositi_U0_start_out;
    sc_signal< sc_logic > gradient_decompositi_U0_start_write;
    sc_signal< sc_logic > gradient_decompositi_U0_gx_data_stream_V_read;
    sc_signal< sc_logic > gradient_decompositi_U0_gy_data_stream_V_read;
    sc_signal< sc_lv<16> > gradient_decompositi_U0_gd_data_stream_V_din;
    sc_signal< sc_logic > gradient_decompositi_U0_gd_data_stream_V_write;
    sc_signal< sc_logic > nonmax_suppression_U0_ap_start;
    sc_signal< sc_logic > nonmax_suppression_U0_ap_done;
    sc_signal< sc_logic > nonmax_suppression_U0_ap_continue;
    sc_signal< sc_logic > nonmax_suppression_U0_ap_idle;
    sc_signal< sc_logic > nonmax_suppression_U0_ap_ready;
    sc_signal< sc_logic > nonmax_suppression_U0_start_out;
    sc_signal< sc_logic > nonmax_suppression_U0_start_write;
    sc_signal< sc_logic > nonmax_suppression_U0_gd_data_stream_V_read;
    sc_signal< sc_lv<16> > nonmax_suppression_U0_dst_data_stream_V_din;
    sc_signal< sc_logic > nonmax_suppression_U0_dst_data_stream_V_write;
    sc_signal< sc_logic > hysteresis_U0_ap_start;
    sc_signal< sc_logic > hysteresis_U0_ap_done;
    sc_signal< sc_logic > hysteresis_U0_ap_continue;
    sc_signal< sc_logic > hysteresis_U0_ap_idle;
    sc_signal< sc_logic > hysteresis_U0_ap_ready;
    sc_signal< sc_logic > hysteresis_U0_src_data_stream_V_read;
    sc_signal< sc_lv<8> > hysteresis_U0_dst_data_stream_V_din;
    sc_signal< sc_logic > hysteresis_U0_dst_data_stream_V_write;
    sc_signal< sc_logic > Loop_2_proc_U0_ap_start;
    sc_signal< sc_logic > Loop_2_proc_U0_ap_done;
    sc_signal< sc_logic > Loop_2_proc_U0_ap_continue;
    sc_signal< sc_logic > Loop_2_proc_U0_ap_idle;
    sc_signal< sc_logic > Loop_2_proc_U0_ap_ready;
    sc_signal< sc_logic > Loop_2_proc_U0_packets_cast_loc_read;
    sc_signal< sc_logic > Loop_2_proc_U0_canny_edges_data_stream_0_V_read;
    sc_signal< sc_lv<32> > Loop_2_proc_U0_out_stream_data_V_TDATA;
    sc_signal< sc_logic > Loop_2_proc_U0_out_stream_data_V_TVALID;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > packets_cast_loc_c_full_n;
    sc_signal< sc_lv<20> > packets_cast_loc_c_dout;
    sc_signal< sc_logic > packets_cast_loc_c_empty_n;
    sc_signal< sc_logic > src_bw_data_stream_0_full_n;
    sc_signal< sc_lv<8> > src_bw_data_stream_0_dout;
    sc_signal< sc_logic > src_bw_data_stream_0_empty_n;
    sc_signal< sc_logic > packets_cast_loc_c35_full_n;
    sc_signal< sc_lv<20> > packets_cast_loc_c35_dout;
    sc_signal< sc_logic > packets_cast_loc_c35_empty_n;
    sc_signal< sc_logic > src1_data_stream_0_s_full_n;
    sc_signal< sc_lv<8> > src1_data_stream_0_s_dout;
    sc_signal< sc_logic > src1_data_stream_0_s_empty_n;
    sc_signal< sc_logic > src2_data_stream_0_s_full_n;
    sc_signal< sc_lv<8> > src2_data_stream_0_s_dout;
    sc_signal< sc_logic > src2_data_stream_0_s_empty_n;
    sc_signal< sc_logic > sobel_gx_data_stream_full_n;
    sc_signal< sc_lv<16> > sobel_gx_data_stream_dout;
    sc_signal< sc_logic > sobel_gx_data_stream_empty_n;
    sc_signal< sc_logic > sobel_gy_data_stream_full_n;
    sc_signal< sc_lv<16> > sobel_gy_data_stream_dout;
    sc_signal< sc_logic > sobel_gy_data_stream_empty_n;
    sc_signal< sc_logic > grad_gd_data_stream_s_full_n;
    sc_signal< sc_lv<16> > grad_gd_data_stream_s_dout;
    sc_signal< sc_logic > grad_gd_data_stream_s_empty_n;
    sc_signal< sc_logic > suppressed_data_stre_full_n;
    sc_signal< sc_lv<16> > suppressed_data_stre_dout;
    sc_signal< sc_logic > suppressed_data_stre_empty_n;
    sc_signal< sc_logic > canny_edges_data_str_full_n;
    sc_signal< sc_lv<8> > canny_edges_data_str_dout;
    sc_signal< sc_logic > canny_edges_data_str_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > ap_sync_reg_Block_Mat_exit27932_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_Block_Mat_exit27932_U0_ap_ready;
    sc_signal< sc_lv<2> > Block_Mat_exit27932_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_Loop_1_proc_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_Loop_1_proc_U0_ap_ready;
    sc_signal< sc_lv<2> > Loop_1_proc_U0_ap_ready_count;
    sc_signal< sc_logic > Block_Mat_exit27932_U0_start_full_n;
    sc_signal< sc_logic > Block_Mat_exit27932_U0_start_write;
    sc_signal< sc_lv<1> > start_for_Duplicate_U0_din;
    sc_signal< sc_logic > start_for_Duplicate_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Duplicate_U0_dout;
    sc_signal< sc_logic > start_for_Duplicate_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Loop_2_proc_U0_din;
    sc_signal< sc_logic > start_for_Loop_2_proc_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Loop_2_proc_U0_dout;
    sc_signal< sc_logic > start_for_Loop_2_proc_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Sobel_U0_din;
    sc_signal< sc_logic > start_for_Sobel_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Sobel_U0_dout;
    sc_signal< sc_logic > start_for_Sobel_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Sobel_1_U0_din;
    sc_signal< sc_logic > start_for_Sobel_1_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Sobel_1_U0_dout;
    sc_signal< sc_logic > start_for_Sobel_1_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_gradient_decompositi_U0_din;
    sc_signal< sc_logic > start_for_gradient_decompositi_U0_full_n;
    sc_signal< sc_lv<1> > start_for_gradient_decompositi_U0_dout;
    sc_signal< sc_logic > start_for_gradient_decompositi_U0_empty_n;
    sc_signal< sc_logic > Sobel_1_U0_start_full_n;
    sc_signal< sc_logic > Sobel_1_U0_start_write;
    sc_signal< sc_lv<1> > start_for_nonmax_suppression_U0_din;
    sc_signal< sc_logic > start_for_nonmax_suppression_U0_full_n;
    sc_signal< sc_lv<1> > start_for_nonmax_suppression_U0_dout;
    sc_signal< sc_logic > start_for_nonmax_suppression_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_hysteresis_U0_din;
    sc_signal< sc_logic > start_for_hysteresis_U0_full_n;
    sc_signal< sc_lv<1> > start_for_hysteresis_U0_dout;
    sc_signal< sc_logic > start_for_hysteresis_U0_empty_n;
    sc_signal< sc_logic > hysteresis_U0_start_full_n;
    sc_signal< sc_logic > hysteresis_U0_start_write;
    sc_signal< sc_logic > Loop_2_proc_U0_start_full_n;
    sc_signal< sc_logic > Loop_2_proc_U0_start_write;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_S_AXI_WSTRB_WIDTH;
    static const int C_S_AXI_ADDR_WIDTH;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_Block_Mat_exit27932_U0_ap_continue();
    void thread_Block_Mat_exit27932_U0_ap_start();
    void thread_Block_Mat_exit27932_U0_start_full_n();
    void thread_Block_Mat_exit27932_U0_start_write();
    void thread_Duplicate_U0_ap_continue();
    void thread_Duplicate_U0_ap_start();
    void thread_Duplicate_U0_start_full_n();
    void thread_INPUT_data_V_TREADY();
    void thread_Loop_1_proc_U0_ap_continue();
    void thread_Loop_1_proc_U0_ap_start();
    void thread_Loop_1_proc_U0_start_full_n();
    void thread_Loop_2_proc_U0_ap_continue();
    void thread_Loop_2_proc_U0_ap_start();
    void thread_Loop_2_proc_U0_start_full_n();
    void thread_Loop_2_proc_U0_start_write();
    void thread_OUTPUT_data_V_TDATA();
    void thread_OUTPUT_data_V_TVALID();
    void thread_Sobel_1_U0_ap_continue();
    void thread_Sobel_1_U0_ap_start();
    void thread_Sobel_1_U0_start_full_n();
    void thread_Sobel_1_U0_start_write();
    void thread_Sobel_U0_ap_continue();
    void thread_Sobel_U0_ap_start();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_AXI_LITE_clk_inv();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_Block_Mat_exit27932_U0_ap_ready();
    void thread_ap_sync_Loop_1_proc_U0_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_gradient_decompositi_U0_ap_continue();
    void thread_gradient_decompositi_U0_ap_start();
    void thread_hysteresis_U0_ap_continue();
    void thread_hysteresis_U0_ap_start();
    void thread_hysteresis_U0_start_full_n();
    void thread_hysteresis_U0_start_write();
    void thread_nonmax_suppression_U0_ap_continue();
    void thread_nonmax_suppression_U0_ap_start();
    void thread_start_for_Duplicate_U0_din();
    void thread_start_for_Loop_2_proc_U0_din();
    void thread_start_for_Sobel_1_U0_din();
    void thread_start_for_Sobel_U0_din();
    void thread_start_for_gradient_decompositi_U0_din();
    void thread_start_for_hysteresis_U0_din();
    void thread_start_for_nonmax_suppression_U0_din();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
