// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "canny_edge.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int canny_edge::C_S_AXI_DATA_WIDTH = "100000";
const int canny_edge::C_S_AXI_WSTRB_WIDTH = "100";
const int canny_edge::C_S_AXI_ADDR_WIDTH = "100000";
const sc_logic canny_edge::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<32> canny_edge::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_logic canny_edge::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> canny_edge::ap_const_lv2_0 = "00";
const sc_lv<2> canny_edge::ap_const_lv2_1 = "1";
const bool canny_edge::ap_const_boolean_1 = true;

canny_edge::canny_edge(sc_module_name name) : sc_module(name), mVcdFile(0) {
    canny_edge_CONTROL_BUS_s_axi_U = new canny_edge_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>("canny_edge_CONTROL_BUS_s_axi_U");
    canny_edge_CONTROL_BUS_s_axi_U->AWVALID(s_axi_CONTROL_BUS_AWVALID);
    canny_edge_CONTROL_BUS_s_axi_U->AWREADY(s_axi_CONTROL_BUS_AWREADY);
    canny_edge_CONTROL_BUS_s_axi_U->AWADDR(s_axi_CONTROL_BUS_AWADDR);
    canny_edge_CONTROL_BUS_s_axi_U->WVALID(s_axi_CONTROL_BUS_WVALID);
    canny_edge_CONTROL_BUS_s_axi_U->WREADY(s_axi_CONTROL_BUS_WREADY);
    canny_edge_CONTROL_BUS_s_axi_U->WDATA(s_axi_CONTROL_BUS_WDATA);
    canny_edge_CONTROL_BUS_s_axi_U->WSTRB(s_axi_CONTROL_BUS_WSTRB);
    canny_edge_CONTROL_BUS_s_axi_U->ARVALID(s_axi_CONTROL_BUS_ARVALID);
    canny_edge_CONTROL_BUS_s_axi_U->ARREADY(s_axi_CONTROL_BUS_ARREADY);
    canny_edge_CONTROL_BUS_s_axi_U->ARADDR(s_axi_CONTROL_BUS_ARADDR);
    canny_edge_CONTROL_BUS_s_axi_U->RVALID(s_axi_CONTROL_BUS_RVALID);
    canny_edge_CONTROL_BUS_s_axi_U->RREADY(s_axi_CONTROL_BUS_RREADY);
    canny_edge_CONTROL_BUS_s_axi_U->RDATA(s_axi_CONTROL_BUS_RDATA);
    canny_edge_CONTROL_BUS_s_axi_U->RRESP(s_axi_CONTROL_BUS_RRESP);
    canny_edge_CONTROL_BUS_s_axi_U->BVALID(s_axi_CONTROL_BUS_BVALID);
    canny_edge_CONTROL_BUS_s_axi_U->BREADY(s_axi_CONTROL_BUS_BREADY);
    canny_edge_CONTROL_BUS_s_axi_U->BRESP(s_axi_CONTROL_BUS_BRESP);
    canny_edge_CONTROL_BUS_s_axi_U->ACLK(AXI_LITE_clk);
    canny_edge_CONTROL_BUS_s_axi_U->ARESET(ap_rst_n_inv);
    canny_edge_CONTROL_BUS_s_axi_U->ACLK_EN(ap_var_for_const0);
    canny_edge_CONTROL_BUS_s_axi_U->rows_V(rows_V);
    canny_edge_CONTROL_BUS_s_axi_U->cols_V(cols_V);
    canny_edge_CONTROL_BUS_s_axi_U->threshold1(threshold1);
    canny_edge_CONTROL_BUS_s_axi_U->threshold2(threshold2);
    canny_edge_CONTROL_BUS_s_axi_U->ap_start(ap_start);
    canny_edge_CONTROL_BUS_s_axi_U->interrupt(interrupt);
    canny_edge_CONTROL_BUS_s_axi_U->ap_ready(ap_ready);
    canny_edge_CONTROL_BUS_s_axi_U->ap_done(ap_done);
    canny_edge_CONTROL_BUS_s_axi_U->ap_idle(ap_idle);
    canny_edge_CONTROL_BUS_s_axi_U->clk(ap_clk);
    canny_edge_CONTROL_BUS_s_axi_U->rst(ap_rst_n_AXI_LITE_clk_inv);
    Block_Mat_exit27932_U0 = new Block_Mat_exit27932_s("Block_Mat_exit27932_U0");
    Block_Mat_exit27932_U0->ap_clk(ap_clk);
    Block_Mat_exit27932_U0->ap_rst(ap_rst_n_inv);
    Block_Mat_exit27932_U0->ap_start(Block_Mat_exit27932_U0_ap_start);
    Block_Mat_exit27932_U0->ap_done(Block_Mat_exit27932_U0_ap_done);
    Block_Mat_exit27932_U0->ap_continue(Block_Mat_exit27932_U0_ap_continue);
    Block_Mat_exit27932_U0->ap_idle(Block_Mat_exit27932_U0_ap_idle);
    Block_Mat_exit27932_U0->ap_ready(Block_Mat_exit27932_U0_ap_ready);
    Block_Mat_exit27932_U0->rows_V(rows_V);
    Block_Mat_exit27932_U0->cols_V(cols_V);
    Block_Mat_exit27932_U0->packets_cast_out_out_din(Block_Mat_exit27932_U0_packets_cast_out_out_din);
    Block_Mat_exit27932_U0->packets_cast_out_out_full_n(packets_cast_loc_c_full_n);
    Block_Mat_exit27932_U0->packets_cast_out_out_write(Block_Mat_exit27932_U0_packets_cast_out_out_write);
    Loop_1_proc_U0 = new Loop_1_proc("Loop_1_proc_U0");
    Loop_1_proc_U0->ap_clk(ap_clk);
    Loop_1_proc_U0->ap_rst(ap_rst_n_inv);
    Loop_1_proc_U0->ap_start(Loop_1_proc_U0_ap_start);
    Loop_1_proc_U0->start_full_n(Loop_1_proc_U0_start_full_n);
    Loop_1_proc_U0->ap_done(Loop_1_proc_U0_ap_done);
    Loop_1_proc_U0->ap_continue(Loop_1_proc_U0_ap_continue);
    Loop_1_proc_U0->ap_idle(Loop_1_proc_U0_ap_idle);
    Loop_1_proc_U0->ap_ready(Loop_1_proc_U0_ap_ready);
    Loop_1_proc_U0->start_out(Loop_1_proc_U0_start_out);
    Loop_1_proc_U0->start_write(Loop_1_proc_U0_start_write);
    Loop_1_proc_U0->packets_cast_loc_dout(packets_cast_loc_c_dout);
    Loop_1_proc_U0->packets_cast_loc_empty_n(packets_cast_loc_c_empty_n);
    Loop_1_proc_U0->packets_cast_loc_read(Loop_1_proc_U0_packets_cast_loc_read);
    Loop_1_proc_U0->in_stream_data_V_TDATA(INPUT_data_V_TDATA);
    Loop_1_proc_U0->in_stream_data_V_TVALID(INPUT_data_V_TVALID);
    Loop_1_proc_U0->in_stream_data_V_TREADY(Loop_1_proc_U0_in_stream_data_V_TREADY);
    Loop_1_proc_U0->src_bw_data_stream_0_V_din(Loop_1_proc_U0_src_bw_data_stream_0_V_din);
    Loop_1_proc_U0->src_bw_data_stream_0_V_full_n(src_bw_data_stream_0_full_n);
    Loop_1_proc_U0->src_bw_data_stream_0_V_write(Loop_1_proc_U0_src_bw_data_stream_0_V_write);
    Loop_1_proc_U0->packets_cast_loc_out_din(Loop_1_proc_U0_packets_cast_loc_out_din);
    Loop_1_proc_U0->packets_cast_loc_out_full_n(packets_cast_loc_c35_full_n);
    Loop_1_proc_U0->packets_cast_loc_out_write(Loop_1_proc_U0_packets_cast_loc_out_write);
    Duplicate_U0 = new Duplicate("Duplicate_U0");
    Duplicate_U0->ap_clk(ap_clk);
    Duplicate_U0->ap_rst(ap_rst_n_inv);
    Duplicate_U0->ap_start(Duplicate_U0_ap_start);
    Duplicate_U0->start_full_n(Duplicate_U0_start_full_n);
    Duplicate_U0->ap_done(Duplicate_U0_ap_done);
    Duplicate_U0->ap_continue(Duplicate_U0_ap_continue);
    Duplicate_U0->ap_idle(Duplicate_U0_ap_idle);
    Duplicate_U0->ap_ready(Duplicate_U0_ap_ready);
    Duplicate_U0->start_out(Duplicate_U0_start_out);
    Duplicate_U0->start_write(Duplicate_U0_start_write);
    Duplicate_U0->src_rows_V(rows_V);
    Duplicate_U0->src_cols_V(cols_V);
    Duplicate_U0->src_data_stream_V_dout(src_bw_data_stream_0_dout);
    Duplicate_U0->src_data_stream_V_empty_n(src_bw_data_stream_0_empty_n);
    Duplicate_U0->src_data_stream_V_read(Duplicate_U0_src_data_stream_V_read);
    Duplicate_U0->dst1_data_stream_V_din(Duplicate_U0_dst1_data_stream_V_din);
    Duplicate_U0->dst1_data_stream_V_full_n(src1_data_stream_0_s_full_n);
    Duplicate_U0->dst1_data_stream_V_write(Duplicate_U0_dst1_data_stream_V_write);
    Duplicate_U0->dst2_data_stream_V_din(Duplicate_U0_dst2_data_stream_V_din);
    Duplicate_U0->dst2_data_stream_V_full_n(src2_data_stream_0_s_full_n);
    Duplicate_U0->dst2_data_stream_V_write(Duplicate_U0_dst2_data_stream_V_write);
    Sobel_U0 = new Sobel("Sobel_U0");
    Sobel_U0->ap_clk(ap_clk);
    Sobel_U0->ap_rst(ap_rst_n_inv);
    Sobel_U0->ap_start(Sobel_U0_ap_start);
    Sobel_U0->start_full_n(start_for_gradient_decompositi_U0_full_n);
    Sobel_U0->ap_done(Sobel_U0_ap_done);
    Sobel_U0->ap_continue(Sobel_U0_ap_continue);
    Sobel_U0->ap_idle(Sobel_U0_ap_idle);
    Sobel_U0->ap_ready(Sobel_U0_ap_ready);
    Sobel_U0->start_out(Sobel_U0_start_out);
    Sobel_U0->start_write(Sobel_U0_start_write);
    Sobel_U0->p_src_rows_V(rows_V);
    Sobel_U0->p_src_cols_V(cols_V);
    Sobel_U0->p_src_data_stream_V_dout(src1_data_stream_0_s_dout);
    Sobel_U0->p_src_data_stream_V_empty_n(src1_data_stream_0_s_empty_n);
    Sobel_U0->p_src_data_stream_V_read(Sobel_U0_p_src_data_stream_V_read);
    Sobel_U0->p_dst_data_stream_V_din(Sobel_U0_p_dst_data_stream_V_din);
    Sobel_U0->p_dst_data_stream_V_full_n(sobel_gx_data_stream_full_n);
    Sobel_U0->p_dst_data_stream_V_write(Sobel_U0_p_dst_data_stream_V_write);
    Sobel_1_U0 = new Sobel_1("Sobel_1_U0");
    Sobel_1_U0->ap_clk(ap_clk);
    Sobel_1_U0->ap_rst(ap_rst_n_inv);
    Sobel_1_U0->ap_start(Sobel_1_U0_ap_start);
    Sobel_1_U0->ap_done(Sobel_1_U0_ap_done);
    Sobel_1_U0->ap_continue(Sobel_1_U0_ap_continue);
    Sobel_1_U0->ap_idle(Sobel_1_U0_ap_idle);
    Sobel_1_U0->ap_ready(Sobel_1_U0_ap_ready);
    Sobel_1_U0->p_src_rows_V(rows_V);
    Sobel_1_U0->p_src_cols_V(cols_V);
    Sobel_1_U0->p_src_data_stream_V_dout(src2_data_stream_0_s_dout);
    Sobel_1_U0->p_src_data_stream_V_empty_n(src2_data_stream_0_s_empty_n);
    Sobel_1_U0->p_src_data_stream_V_read(Sobel_1_U0_p_src_data_stream_V_read);
    Sobel_1_U0->p_dst_data_stream_V_din(Sobel_1_U0_p_dst_data_stream_V_din);
    Sobel_1_U0->p_dst_data_stream_V_full_n(sobel_gy_data_stream_full_n);
    Sobel_1_U0->p_dst_data_stream_V_write(Sobel_1_U0_p_dst_data_stream_V_write);
    gradient_decompositi_U0 = new gradient_decompositi("gradient_decompositi_U0");
    gradient_decompositi_U0->ap_clk(ap_clk);
    gradient_decompositi_U0->ap_rst(ap_rst_n_inv);
    gradient_decompositi_U0->ap_start(gradient_decompositi_U0_ap_start);
    gradient_decompositi_U0->start_full_n(start_for_nonmax_suppression_U0_full_n);
    gradient_decompositi_U0->ap_done(gradient_decompositi_U0_ap_done);
    gradient_decompositi_U0->ap_continue(gradient_decompositi_U0_ap_continue);
    gradient_decompositi_U0->ap_idle(gradient_decompositi_U0_ap_idle);
    gradient_decompositi_U0->ap_ready(gradient_decompositi_U0_ap_ready);
    gradient_decompositi_U0->start_out(gradient_decompositi_U0_start_out);
    gradient_decompositi_U0->start_write(gradient_decompositi_U0_start_write);
    gradient_decompositi_U0->gx_rows_V(rows_V);
    gradient_decompositi_U0->gx_cols_V(cols_V);
    gradient_decompositi_U0->gx_data_stream_V_dout(sobel_gx_data_stream_dout);
    gradient_decompositi_U0->gx_data_stream_V_empty_n(sobel_gx_data_stream_empty_n);
    gradient_decompositi_U0->gx_data_stream_V_read(gradient_decompositi_U0_gx_data_stream_V_read);
    gradient_decompositi_U0->gy_data_stream_V_dout(sobel_gy_data_stream_dout);
    gradient_decompositi_U0->gy_data_stream_V_empty_n(sobel_gy_data_stream_empty_n);
    gradient_decompositi_U0->gy_data_stream_V_read(gradient_decompositi_U0_gy_data_stream_V_read);
    gradient_decompositi_U0->gd_data_stream_V_din(gradient_decompositi_U0_gd_data_stream_V_din);
    gradient_decompositi_U0->gd_data_stream_V_full_n(grad_gd_data_stream_s_full_n);
    gradient_decompositi_U0->gd_data_stream_V_write(gradient_decompositi_U0_gd_data_stream_V_write);
    nonmax_suppression_U0 = new nonmax_suppression("nonmax_suppression_U0");
    nonmax_suppression_U0->ap_clk(ap_clk);
    nonmax_suppression_U0->ap_rst(ap_rst_n_inv);
    nonmax_suppression_U0->ap_start(nonmax_suppression_U0_ap_start);
    nonmax_suppression_U0->start_full_n(start_for_hysteresis_U0_full_n);
    nonmax_suppression_U0->ap_done(nonmax_suppression_U0_ap_done);
    nonmax_suppression_U0->ap_continue(nonmax_suppression_U0_ap_continue);
    nonmax_suppression_U0->ap_idle(nonmax_suppression_U0_ap_idle);
    nonmax_suppression_U0->ap_ready(nonmax_suppression_U0_ap_ready);
    nonmax_suppression_U0->start_out(nonmax_suppression_U0_start_out);
    nonmax_suppression_U0->start_write(nonmax_suppression_U0_start_write);
    nonmax_suppression_U0->gd_rows_V(rows_V);
    nonmax_suppression_U0->gd_cols_V(cols_V);
    nonmax_suppression_U0->gd_data_stream_V_dout(grad_gd_data_stream_s_dout);
    nonmax_suppression_U0->gd_data_stream_V_empty_n(grad_gd_data_stream_s_empty_n);
    nonmax_suppression_U0->gd_data_stream_V_read(nonmax_suppression_U0_gd_data_stream_V_read);
    nonmax_suppression_U0->dst_data_stream_V_din(nonmax_suppression_U0_dst_data_stream_V_din);
    nonmax_suppression_U0->dst_data_stream_V_full_n(suppressed_data_stre_full_n);
    nonmax_suppression_U0->dst_data_stream_V_write(nonmax_suppression_U0_dst_data_stream_V_write);
    hysteresis_U0 = new hysteresis("hysteresis_U0");
    hysteresis_U0->ap_clk(ap_clk);
    hysteresis_U0->ap_rst(ap_rst_n_inv);
    hysteresis_U0->ap_start(hysteresis_U0_ap_start);
    hysteresis_U0->ap_done(hysteresis_U0_ap_done);
    hysteresis_U0->ap_continue(hysteresis_U0_ap_continue);
    hysteresis_U0->ap_idle(hysteresis_U0_ap_idle);
    hysteresis_U0->ap_ready(hysteresis_U0_ap_ready);
    hysteresis_U0->src_rows_V(rows_V);
    hysteresis_U0->src_cols_V(cols_V);
    hysteresis_U0->src_data_stream_V_dout(suppressed_data_stre_dout);
    hysteresis_U0->src_data_stream_V_empty_n(suppressed_data_stre_empty_n);
    hysteresis_U0->src_data_stream_V_read(hysteresis_U0_src_data_stream_V_read);
    hysteresis_U0->dst_data_stream_V_din(hysteresis_U0_dst_data_stream_V_din);
    hysteresis_U0->dst_data_stream_V_full_n(canny_edges_data_str_full_n);
    hysteresis_U0->dst_data_stream_V_write(hysteresis_U0_dst_data_stream_V_write);
    hysteresis_U0->threshold_low(threshold1);
    hysteresis_U0->threshold_high(threshold2);
    Loop_2_proc_U0 = new Loop_2_proc("Loop_2_proc_U0");
    Loop_2_proc_U0->ap_clk(ap_clk);
    Loop_2_proc_U0->ap_rst(ap_rst_n_inv);
    Loop_2_proc_U0->ap_start(Loop_2_proc_U0_ap_start);
    Loop_2_proc_U0->ap_done(Loop_2_proc_U0_ap_done);
    Loop_2_proc_U0->ap_continue(Loop_2_proc_U0_ap_continue);
    Loop_2_proc_U0->ap_idle(Loop_2_proc_U0_ap_idle);
    Loop_2_proc_U0->ap_ready(Loop_2_proc_U0_ap_ready);
    Loop_2_proc_U0->packets_cast_loc_dout(packets_cast_loc_c35_dout);
    Loop_2_proc_U0->packets_cast_loc_empty_n(packets_cast_loc_c35_empty_n);
    Loop_2_proc_U0->packets_cast_loc_read(Loop_2_proc_U0_packets_cast_loc_read);
    Loop_2_proc_U0->canny_edges_data_stream_0_V_dout(canny_edges_data_str_dout);
    Loop_2_proc_U0->canny_edges_data_stream_0_V_empty_n(canny_edges_data_str_empty_n);
    Loop_2_proc_U0->canny_edges_data_stream_0_V_read(Loop_2_proc_U0_canny_edges_data_stream_0_V_read);
    Loop_2_proc_U0->out_stream_data_V_TDATA(Loop_2_proc_U0_out_stream_data_V_TDATA);
    Loop_2_proc_U0->out_stream_data_V_TVALID(Loop_2_proc_U0_out_stream_data_V_TVALID);
    Loop_2_proc_U0->out_stream_data_V_TREADY(OUTPUT_data_V_TREADY);
    packets_cast_loc_c_U = new fifo_w20_d2_A("packets_cast_loc_c_U");
    packets_cast_loc_c_U->clk(ap_clk);
    packets_cast_loc_c_U->reset(ap_rst_n_inv);
    packets_cast_loc_c_U->if_read_ce(ap_var_for_const0);
    packets_cast_loc_c_U->if_write_ce(ap_var_for_const0);
    packets_cast_loc_c_U->if_din(Block_Mat_exit27932_U0_packets_cast_out_out_din);
    packets_cast_loc_c_U->if_full_n(packets_cast_loc_c_full_n);
    packets_cast_loc_c_U->if_write(Block_Mat_exit27932_U0_packets_cast_out_out_write);
    packets_cast_loc_c_U->if_dout(packets_cast_loc_c_dout);
    packets_cast_loc_c_U->if_empty_n(packets_cast_loc_c_empty_n);
    packets_cast_loc_c_U->if_read(Loop_1_proc_U0_packets_cast_loc_read);
    src_bw_data_stream_0_U = new fifo_w8_d2_A("src_bw_data_stream_0_U");
    src_bw_data_stream_0_U->clk(ap_clk);
    src_bw_data_stream_0_U->reset(ap_rst_n_inv);
    src_bw_data_stream_0_U->if_read_ce(ap_var_for_const0);
    src_bw_data_stream_0_U->if_write_ce(ap_var_for_const0);
    src_bw_data_stream_0_U->if_din(Loop_1_proc_U0_src_bw_data_stream_0_V_din);
    src_bw_data_stream_0_U->if_full_n(src_bw_data_stream_0_full_n);
    src_bw_data_stream_0_U->if_write(Loop_1_proc_U0_src_bw_data_stream_0_V_write);
    src_bw_data_stream_0_U->if_dout(src_bw_data_stream_0_dout);
    src_bw_data_stream_0_U->if_empty_n(src_bw_data_stream_0_empty_n);
    src_bw_data_stream_0_U->if_read(Duplicate_U0_src_data_stream_V_read);
    packets_cast_loc_c35_U = new fifo_w20_d7_A("packets_cast_loc_c35_U");
    packets_cast_loc_c35_U->clk(ap_clk);
    packets_cast_loc_c35_U->reset(ap_rst_n_inv);
    packets_cast_loc_c35_U->if_read_ce(ap_var_for_const0);
    packets_cast_loc_c35_U->if_write_ce(ap_var_for_const0);
    packets_cast_loc_c35_U->if_din(Loop_1_proc_U0_packets_cast_loc_out_din);
    packets_cast_loc_c35_U->if_full_n(packets_cast_loc_c35_full_n);
    packets_cast_loc_c35_U->if_write(Loop_1_proc_U0_packets_cast_loc_out_write);
    packets_cast_loc_c35_U->if_dout(packets_cast_loc_c35_dout);
    packets_cast_loc_c35_U->if_empty_n(packets_cast_loc_c35_empty_n);
    packets_cast_loc_c35_U->if_read(Loop_2_proc_U0_packets_cast_loc_read);
    src1_data_stream_0_s_U = new fifo_w8_d2_A("src1_data_stream_0_s_U");
    src1_data_stream_0_s_U->clk(ap_clk);
    src1_data_stream_0_s_U->reset(ap_rst_n_inv);
    src1_data_stream_0_s_U->if_read_ce(ap_var_for_const0);
    src1_data_stream_0_s_U->if_write_ce(ap_var_for_const0);
    src1_data_stream_0_s_U->if_din(Duplicate_U0_dst1_data_stream_V_din);
    src1_data_stream_0_s_U->if_full_n(src1_data_stream_0_s_full_n);
    src1_data_stream_0_s_U->if_write(Duplicate_U0_dst1_data_stream_V_write);
    src1_data_stream_0_s_U->if_dout(src1_data_stream_0_s_dout);
    src1_data_stream_0_s_U->if_empty_n(src1_data_stream_0_s_empty_n);
    src1_data_stream_0_s_U->if_read(Sobel_U0_p_src_data_stream_V_read);
    src2_data_stream_0_s_U = new fifo_w8_d2_A("src2_data_stream_0_s_U");
    src2_data_stream_0_s_U->clk(ap_clk);
    src2_data_stream_0_s_U->reset(ap_rst_n_inv);
    src2_data_stream_0_s_U->if_read_ce(ap_var_for_const0);
    src2_data_stream_0_s_U->if_write_ce(ap_var_for_const0);
    src2_data_stream_0_s_U->if_din(Duplicate_U0_dst2_data_stream_V_din);
    src2_data_stream_0_s_U->if_full_n(src2_data_stream_0_s_full_n);
    src2_data_stream_0_s_U->if_write(Duplicate_U0_dst2_data_stream_V_write);
    src2_data_stream_0_s_U->if_dout(src2_data_stream_0_s_dout);
    src2_data_stream_0_s_U->if_empty_n(src2_data_stream_0_s_empty_n);
    src2_data_stream_0_s_U->if_read(Sobel_1_U0_p_src_data_stream_V_read);
    sobel_gx_data_stream_U = new fifo_w16_d2_A("sobel_gx_data_stream_U");
    sobel_gx_data_stream_U->clk(ap_clk);
    sobel_gx_data_stream_U->reset(ap_rst_n_inv);
    sobel_gx_data_stream_U->if_read_ce(ap_var_for_const0);
    sobel_gx_data_stream_U->if_write_ce(ap_var_for_const0);
    sobel_gx_data_stream_U->if_din(Sobel_U0_p_dst_data_stream_V_din);
    sobel_gx_data_stream_U->if_full_n(sobel_gx_data_stream_full_n);
    sobel_gx_data_stream_U->if_write(Sobel_U0_p_dst_data_stream_V_write);
    sobel_gx_data_stream_U->if_dout(sobel_gx_data_stream_dout);
    sobel_gx_data_stream_U->if_empty_n(sobel_gx_data_stream_empty_n);
    sobel_gx_data_stream_U->if_read(gradient_decompositi_U0_gx_data_stream_V_read);
    sobel_gy_data_stream_U = new fifo_w16_d2_A("sobel_gy_data_stream_U");
    sobel_gy_data_stream_U->clk(ap_clk);
    sobel_gy_data_stream_U->reset(ap_rst_n_inv);
    sobel_gy_data_stream_U->if_read_ce(ap_var_for_const0);
    sobel_gy_data_stream_U->if_write_ce(ap_var_for_const0);
    sobel_gy_data_stream_U->if_din(Sobel_1_U0_p_dst_data_stream_V_din);
    sobel_gy_data_stream_U->if_full_n(sobel_gy_data_stream_full_n);
    sobel_gy_data_stream_U->if_write(Sobel_1_U0_p_dst_data_stream_V_write);
    sobel_gy_data_stream_U->if_dout(sobel_gy_data_stream_dout);
    sobel_gy_data_stream_U->if_empty_n(sobel_gy_data_stream_empty_n);
    sobel_gy_data_stream_U->if_read(gradient_decompositi_U0_gy_data_stream_V_read);
    grad_gd_data_stream_s_U = new fifo_w16_d2_A("grad_gd_data_stream_s_U");
    grad_gd_data_stream_s_U->clk(ap_clk);
    grad_gd_data_stream_s_U->reset(ap_rst_n_inv);
    grad_gd_data_stream_s_U->if_read_ce(ap_var_for_const0);
    grad_gd_data_stream_s_U->if_write_ce(ap_var_for_const0);
    grad_gd_data_stream_s_U->if_din(gradient_decompositi_U0_gd_data_stream_V_din);
    grad_gd_data_stream_s_U->if_full_n(grad_gd_data_stream_s_full_n);
    grad_gd_data_stream_s_U->if_write(gradient_decompositi_U0_gd_data_stream_V_write);
    grad_gd_data_stream_s_U->if_dout(grad_gd_data_stream_s_dout);
    grad_gd_data_stream_s_U->if_empty_n(grad_gd_data_stream_s_empty_n);
    grad_gd_data_stream_s_U->if_read(nonmax_suppression_U0_gd_data_stream_V_read);
    suppressed_data_stre_U = new fifo_w16_d2_A("suppressed_data_stre_U");
    suppressed_data_stre_U->clk(ap_clk);
    suppressed_data_stre_U->reset(ap_rst_n_inv);
    suppressed_data_stre_U->if_read_ce(ap_var_for_const0);
    suppressed_data_stre_U->if_write_ce(ap_var_for_const0);
    suppressed_data_stre_U->if_din(nonmax_suppression_U0_dst_data_stream_V_din);
    suppressed_data_stre_U->if_full_n(suppressed_data_stre_full_n);
    suppressed_data_stre_U->if_write(nonmax_suppression_U0_dst_data_stream_V_write);
    suppressed_data_stre_U->if_dout(suppressed_data_stre_dout);
    suppressed_data_stre_U->if_empty_n(suppressed_data_stre_empty_n);
    suppressed_data_stre_U->if_read(hysteresis_U0_src_data_stream_V_read);
    canny_edges_data_str_U = new fifo_w8_d2_A("canny_edges_data_str_U");
    canny_edges_data_str_U->clk(ap_clk);
    canny_edges_data_str_U->reset(ap_rst_n_inv);
    canny_edges_data_str_U->if_read_ce(ap_var_for_const0);
    canny_edges_data_str_U->if_write_ce(ap_var_for_const0);
    canny_edges_data_str_U->if_din(hysteresis_U0_dst_data_stream_V_din);
    canny_edges_data_str_U->if_full_n(canny_edges_data_str_full_n);
    canny_edges_data_str_U->if_write(hysteresis_U0_dst_data_stream_V_write);
    canny_edges_data_str_U->if_dout(canny_edges_data_str_dout);
    canny_edges_data_str_U->if_empty_n(canny_edges_data_str_empty_n);
    canny_edges_data_str_U->if_read(Loop_2_proc_U0_canny_edges_data_stream_0_V_read);
    start_for_Duplicate_U0_U = new start_for_Duplicate_U0("start_for_Duplicate_U0_U");
    start_for_Duplicate_U0_U->clk(ap_clk);
    start_for_Duplicate_U0_U->reset(ap_rst_n_inv);
    start_for_Duplicate_U0_U->if_read_ce(ap_var_for_const0);
    start_for_Duplicate_U0_U->if_write_ce(ap_var_for_const0);
    start_for_Duplicate_U0_U->if_din(start_for_Duplicate_U0_din);
    start_for_Duplicate_U0_U->if_full_n(start_for_Duplicate_U0_full_n);
    start_for_Duplicate_U0_U->if_write(Loop_1_proc_U0_start_write);
    start_for_Duplicate_U0_U->if_dout(start_for_Duplicate_U0_dout);
    start_for_Duplicate_U0_U->if_empty_n(start_for_Duplicate_U0_empty_n);
    start_for_Duplicate_U0_U->if_read(Duplicate_U0_ap_ready);
    start_for_Loop_2_proc_U0_U = new start_for_Loop_2_proc_U0("start_for_Loop_2_proc_U0_U");
    start_for_Loop_2_proc_U0_U->clk(ap_clk);
    start_for_Loop_2_proc_U0_U->reset(ap_rst_n_inv);
    start_for_Loop_2_proc_U0_U->if_read_ce(ap_var_for_const0);
    start_for_Loop_2_proc_U0_U->if_write_ce(ap_var_for_const0);
    start_for_Loop_2_proc_U0_U->if_din(start_for_Loop_2_proc_U0_din);
    start_for_Loop_2_proc_U0_U->if_full_n(start_for_Loop_2_proc_U0_full_n);
    start_for_Loop_2_proc_U0_U->if_write(Loop_1_proc_U0_start_write);
    start_for_Loop_2_proc_U0_U->if_dout(start_for_Loop_2_proc_U0_dout);
    start_for_Loop_2_proc_U0_U->if_empty_n(start_for_Loop_2_proc_U0_empty_n);
    start_for_Loop_2_proc_U0_U->if_read(Loop_2_proc_U0_ap_ready);
    start_for_Sobel_U0_U = new start_for_Sobel_U0("start_for_Sobel_U0_U");
    start_for_Sobel_U0_U->clk(ap_clk);
    start_for_Sobel_U0_U->reset(ap_rst_n_inv);
    start_for_Sobel_U0_U->if_read_ce(ap_var_for_const0);
    start_for_Sobel_U0_U->if_write_ce(ap_var_for_const0);
    start_for_Sobel_U0_U->if_din(start_for_Sobel_U0_din);
    start_for_Sobel_U0_U->if_full_n(start_for_Sobel_U0_full_n);
    start_for_Sobel_U0_U->if_write(Duplicate_U0_start_write);
    start_for_Sobel_U0_U->if_dout(start_for_Sobel_U0_dout);
    start_for_Sobel_U0_U->if_empty_n(start_for_Sobel_U0_empty_n);
    start_for_Sobel_U0_U->if_read(Sobel_U0_ap_ready);
    start_for_Sobel_1_U0_U = new start_for_Sobel_1_U0("start_for_Sobel_1_U0_U");
    start_for_Sobel_1_U0_U->clk(ap_clk);
    start_for_Sobel_1_U0_U->reset(ap_rst_n_inv);
    start_for_Sobel_1_U0_U->if_read_ce(ap_var_for_const0);
    start_for_Sobel_1_U0_U->if_write_ce(ap_var_for_const0);
    start_for_Sobel_1_U0_U->if_din(start_for_Sobel_1_U0_din);
    start_for_Sobel_1_U0_U->if_full_n(start_for_Sobel_1_U0_full_n);
    start_for_Sobel_1_U0_U->if_write(Duplicate_U0_start_write);
    start_for_Sobel_1_U0_U->if_dout(start_for_Sobel_1_U0_dout);
    start_for_Sobel_1_U0_U->if_empty_n(start_for_Sobel_1_U0_empty_n);
    start_for_Sobel_1_U0_U->if_read(Sobel_1_U0_ap_ready);
    start_for_gradient_decompositi_U0_U = new start_for_gradient_decompositi_U0("start_for_gradient_decompositi_U0_U");
    start_for_gradient_decompositi_U0_U->clk(ap_clk);
    start_for_gradient_decompositi_U0_U->reset(ap_rst_n_inv);
    start_for_gradient_decompositi_U0_U->if_read_ce(ap_var_for_const0);
    start_for_gradient_decompositi_U0_U->if_write_ce(ap_var_for_const0);
    start_for_gradient_decompositi_U0_U->if_din(start_for_gradient_decompositi_U0_din);
    start_for_gradient_decompositi_U0_U->if_full_n(start_for_gradient_decompositi_U0_full_n);
    start_for_gradient_decompositi_U0_U->if_write(Sobel_U0_start_write);
    start_for_gradient_decompositi_U0_U->if_dout(start_for_gradient_decompositi_U0_dout);
    start_for_gradient_decompositi_U0_U->if_empty_n(start_for_gradient_decompositi_U0_empty_n);
    start_for_gradient_decompositi_U0_U->if_read(gradient_decompositi_U0_ap_ready);
    start_for_nonmax_suppression_U0_U = new start_for_nonmax_suppression_U0("start_for_nonmax_suppression_U0_U");
    start_for_nonmax_suppression_U0_U->clk(ap_clk);
    start_for_nonmax_suppression_U0_U->reset(ap_rst_n_inv);
    start_for_nonmax_suppression_U0_U->if_read_ce(ap_var_for_const0);
    start_for_nonmax_suppression_U0_U->if_write_ce(ap_var_for_const0);
    start_for_nonmax_suppression_U0_U->if_din(start_for_nonmax_suppression_U0_din);
    start_for_nonmax_suppression_U0_U->if_full_n(start_for_nonmax_suppression_U0_full_n);
    start_for_nonmax_suppression_U0_U->if_write(gradient_decompositi_U0_start_write);
    start_for_nonmax_suppression_U0_U->if_dout(start_for_nonmax_suppression_U0_dout);
    start_for_nonmax_suppression_U0_U->if_empty_n(start_for_nonmax_suppression_U0_empty_n);
    start_for_nonmax_suppression_U0_U->if_read(nonmax_suppression_U0_ap_ready);
    start_for_hysteresis_U0_U = new start_for_hysteresis_U0("start_for_hysteresis_U0_U");
    start_for_hysteresis_U0_U->clk(ap_clk);
    start_for_hysteresis_U0_U->reset(ap_rst_n_inv);
    start_for_hysteresis_U0_U->if_read_ce(ap_var_for_const0);
    start_for_hysteresis_U0_U->if_write_ce(ap_var_for_const0);
    start_for_hysteresis_U0_U->if_din(start_for_hysteresis_U0_din);
    start_for_hysteresis_U0_U->if_full_n(start_for_hysteresis_U0_full_n);
    start_for_hysteresis_U0_U->if_write(nonmax_suppression_U0_start_write);
    start_for_hysteresis_U0_U->if_dout(start_for_hysteresis_U0_dout);
    start_for_hysteresis_U0_U->if_empty_n(start_for_hysteresis_U0_empty_n);
    start_for_hysteresis_U0_U->if_read(hysteresis_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Block_Mat_exit27932_U0_ap_continue);

    SC_METHOD(thread_Block_Mat_exit27932_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_Block_Mat_exit27932_U0_ap_ready );

    SC_METHOD(thread_Block_Mat_exit27932_U0_start_full_n);

    SC_METHOD(thread_Block_Mat_exit27932_U0_start_write);

    SC_METHOD(thread_Duplicate_U0_ap_continue);

    SC_METHOD(thread_Duplicate_U0_ap_start);
    sensitive << ( start_for_Duplicate_U0_empty_n );

    SC_METHOD(thread_Duplicate_U0_start_full_n);
    sensitive << ( start_for_Sobel_U0_full_n );
    sensitive << ( start_for_Sobel_1_U0_full_n );

    SC_METHOD(thread_INPUT_data_V_TREADY);
    sensitive << ( Loop_1_proc_U0_in_stream_data_V_TREADY );

    SC_METHOD(thread_Loop_1_proc_U0_ap_continue);

    SC_METHOD(thread_Loop_1_proc_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_Loop_1_proc_U0_ap_ready );

    SC_METHOD(thread_Loop_1_proc_U0_start_full_n);
    sensitive << ( start_for_Duplicate_U0_full_n );
    sensitive << ( start_for_Loop_2_proc_U0_full_n );

    SC_METHOD(thread_Loop_2_proc_U0_ap_continue);

    SC_METHOD(thread_Loop_2_proc_U0_ap_start);
    sensitive << ( start_for_Loop_2_proc_U0_empty_n );

    SC_METHOD(thread_Loop_2_proc_U0_start_full_n);

    SC_METHOD(thread_Loop_2_proc_U0_start_write);

    SC_METHOD(thread_OUTPUT_data_V_TDATA);
    sensitive << ( Loop_2_proc_U0_out_stream_data_V_TDATA );

    SC_METHOD(thread_OUTPUT_data_V_TVALID);
    sensitive << ( Loop_2_proc_U0_out_stream_data_V_TVALID );

    SC_METHOD(thread_Sobel_1_U0_ap_continue);

    SC_METHOD(thread_Sobel_1_U0_ap_start);
    sensitive << ( start_for_Sobel_1_U0_empty_n );

    SC_METHOD(thread_Sobel_1_U0_start_full_n);

    SC_METHOD(thread_Sobel_1_U0_start_write);

    SC_METHOD(thread_Sobel_U0_ap_continue);

    SC_METHOD(thread_Sobel_U0_ap_start);
    sensitive << ( start_for_Sobel_U0_empty_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( Loop_2_proc_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Block_Mat_exit27932_U0_ap_idle );
    sensitive << ( Loop_1_proc_U0_ap_idle );
    sensitive << ( Duplicate_U0_ap_idle );
    sensitive << ( Sobel_U0_ap_idle );
    sensitive << ( Sobel_1_U0_ap_idle );
    sensitive << ( gradient_decompositi_U0_ap_idle );
    sensitive << ( nonmax_suppression_U0_ap_idle );
    sensitive << ( hysteresis_U0_ap_idle );
    sensitive << ( Loop_2_proc_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sync_ready );

    SC_METHOD(thread_ap_rst_n_AXI_LITE_clk_inv);
    sensitive << ( ap_rst_n_AXI_LITE_clk );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_Block_Mat_exit27932_U0_ap_ready);
    sensitive << ( Block_Mat_exit27932_U0_ap_ready );
    sensitive << ( ap_sync_reg_Block_Mat_exit27932_U0_ap_ready );

    SC_METHOD(thread_ap_sync_Loop_1_proc_U0_ap_ready);
    sensitive << ( Loop_1_proc_U0_ap_ready );
    sensitive << ( ap_sync_reg_Loop_1_proc_U0_ap_ready );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( Loop_2_proc_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( ap_sync_Block_Mat_exit27932_U0_ap_ready );
    sensitive << ( ap_sync_Loop_1_proc_U0_ap_ready );

    SC_METHOD(thread_gradient_decompositi_U0_ap_continue);

    SC_METHOD(thread_gradient_decompositi_U0_ap_start);
    sensitive << ( start_for_gradient_decompositi_U0_empty_n );

    SC_METHOD(thread_hysteresis_U0_ap_continue);

    SC_METHOD(thread_hysteresis_U0_ap_start);
    sensitive << ( start_for_hysteresis_U0_empty_n );

    SC_METHOD(thread_hysteresis_U0_start_full_n);

    SC_METHOD(thread_hysteresis_U0_start_write);

    SC_METHOD(thread_nonmax_suppression_U0_ap_continue);

    SC_METHOD(thread_nonmax_suppression_U0_ap_start);
    sensitive << ( start_for_nonmax_suppression_U0_empty_n );

    SC_METHOD(thread_start_for_Duplicate_U0_din);

    SC_METHOD(thread_start_for_Loop_2_proc_U0_din);

    SC_METHOD(thread_start_for_Sobel_1_U0_din);

    SC_METHOD(thread_start_for_Sobel_U0_din);

    SC_METHOD(thread_start_for_gradient_decompositi_U0_din);

    SC_METHOD(thread_start_for_hysteresis_U0_din);

    SC_METHOD(thread_start_for_nonmax_suppression_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_Block_Mat_exit27932_U0_ap_ready = SC_LOGIC_0;
    Block_Mat_exit27932_U0_ap_ready_count = "00";
    ap_sync_reg_Loop_1_proc_U0_ap_ready = SC_LOGIC_0;
    Loop_1_proc_U0_ap_ready_count = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "canny_edge_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWVALID, "(port)s_axi_CONTROL_BUS_AWVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWREADY, "(port)s_axi_CONTROL_BUS_AWREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWADDR, "(port)s_axi_CONTROL_BUS_AWADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WVALID, "(port)s_axi_CONTROL_BUS_WVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WREADY, "(port)s_axi_CONTROL_BUS_WREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WDATA, "(port)s_axi_CONTROL_BUS_WDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WSTRB, "(port)s_axi_CONTROL_BUS_WSTRB");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARVALID, "(port)s_axi_CONTROL_BUS_ARVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARREADY, "(port)s_axi_CONTROL_BUS_ARREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARADDR, "(port)s_axi_CONTROL_BUS_ARADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RVALID, "(port)s_axi_CONTROL_BUS_RVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RREADY, "(port)s_axi_CONTROL_BUS_RREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RDATA, "(port)s_axi_CONTROL_BUS_RDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RRESP, "(port)s_axi_CONTROL_BUS_RRESP");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BVALID, "(port)s_axi_CONTROL_BUS_BVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BREADY, "(port)s_axi_CONTROL_BUS_BREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BRESP, "(port)s_axi_CONTROL_BUS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
    sc_trace(mVcdFile, AXI_LITE_clk, "(port)AXI_LITE_clk");
    sc_trace(mVcdFile, ap_rst_n_AXI_LITE_clk, "(port)ap_rst_n_AXI_LITE_clk");
    sc_trace(mVcdFile, INPUT_data_V_TDATA, "(port)INPUT_data_V_TDATA");
    sc_trace(mVcdFile, OUTPUT_data_V_TDATA, "(port)OUTPUT_data_V_TDATA");
    sc_trace(mVcdFile, INPUT_data_V_TVALID, "(port)INPUT_data_V_TVALID");
    sc_trace(mVcdFile, INPUT_data_V_TREADY, "(port)INPUT_data_V_TREADY");
    sc_trace(mVcdFile, OUTPUT_data_V_TVALID, "(port)OUTPUT_data_V_TVALID");
    sc_trace(mVcdFile, OUTPUT_data_V_TREADY, "(port)OUTPUT_data_V_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, rows_V, "rows_V");
    sc_trace(mVcdFile, cols_V, "cols_V");
    sc_trace(mVcdFile, threshold1, "threshold1");
    sc_trace(mVcdFile, threshold2, "threshold2");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_rst_n_AXI_LITE_clk_inv, "ap_rst_n_AXI_LITE_clk_inv");
    sc_trace(mVcdFile, Block_Mat_exit27932_U0_ap_start, "Block_Mat_exit27932_U0_ap_start");
    sc_trace(mVcdFile, Block_Mat_exit27932_U0_ap_done, "Block_Mat_exit27932_U0_ap_done");
    sc_trace(mVcdFile, Block_Mat_exit27932_U0_ap_continue, "Block_Mat_exit27932_U0_ap_continue");
    sc_trace(mVcdFile, Block_Mat_exit27932_U0_ap_idle, "Block_Mat_exit27932_U0_ap_idle");
    sc_trace(mVcdFile, Block_Mat_exit27932_U0_ap_ready, "Block_Mat_exit27932_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit27932_U0_packets_cast_out_out_din, "Block_Mat_exit27932_U0_packets_cast_out_out_din");
    sc_trace(mVcdFile, Block_Mat_exit27932_U0_packets_cast_out_out_write, "Block_Mat_exit27932_U0_packets_cast_out_out_write");
    sc_trace(mVcdFile, Loop_1_proc_U0_ap_start, "Loop_1_proc_U0_ap_start");
    sc_trace(mVcdFile, Loop_1_proc_U0_start_full_n, "Loop_1_proc_U0_start_full_n");
    sc_trace(mVcdFile, Loop_1_proc_U0_ap_done, "Loop_1_proc_U0_ap_done");
    sc_trace(mVcdFile, Loop_1_proc_U0_ap_continue, "Loop_1_proc_U0_ap_continue");
    sc_trace(mVcdFile, Loop_1_proc_U0_ap_idle, "Loop_1_proc_U0_ap_idle");
    sc_trace(mVcdFile, Loop_1_proc_U0_ap_ready, "Loop_1_proc_U0_ap_ready");
    sc_trace(mVcdFile, Loop_1_proc_U0_start_out, "Loop_1_proc_U0_start_out");
    sc_trace(mVcdFile, Loop_1_proc_U0_start_write, "Loop_1_proc_U0_start_write");
    sc_trace(mVcdFile, Loop_1_proc_U0_packets_cast_loc_read, "Loop_1_proc_U0_packets_cast_loc_read");
    sc_trace(mVcdFile, Loop_1_proc_U0_in_stream_data_V_TREADY, "Loop_1_proc_U0_in_stream_data_V_TREADY");
    sc_trace(mVcdFile, Loop_1_proc_U0_src_bw_data_stream_0_V_din, "Loop_1_proc_U0_src_bw_data_stream_0_V_din");
    sc_trace(mVcdFile, Loop_1_proc_U0_src_bw_data_stream_0_V_write, "Loop_1_proc_U0_src_bw_data_stream_0_V_write");
    sc_trace(mVcdFile, Loop_1_proc_U0_packets_cast_loc_out_din, "Loop_1_proc_U0_packets_cast_loc_out_din");
    sc_trace(mVcdFile, Loop_1_proc_U0_packets_cast_loc_out_write, "Loop_1_proc_U0_packets_cast_loc_out_write");
    sc_trace(mVcdFile, Duplicate_U0_ap_start, "Duplicate_U0_ap_start");
    sc_trace(mVcdFile, Duplicate_U0_start_full_n, "Duplicate_U0_start_full_n");
    sc_trace(mVcdFile, Duplicate_U0_ap_done, "Duplicate_U0_ap_done");
    sc_trace(mVcdFile, Duplicate_U0_ap_continue, "Duplicate_U0_ap_continue");
    sc_trace(mVcdFile, Duplicate_U0_ap_idle, "Duplicate_U0_ap_idle");
    sc_trace(mVcdFile, Duplicate_U0_ap_ready, "Duplicate_U0_ap_ready");
    sc_trace(mVcdFile, Duplicate_U0_start_out, "Duplicate_U0_start_out");
    sc_trace(mVcdFile, Duplicate_U0_start_write, "Duplicate_U0_start_write");
    sc_trace(mVcdFile, Duplicate_U0_src_data_stream_V_read, "Duplicate_U0_src_data_stream_V_read");
    sc_trace(mVcdFile, Duplicate_U0_dst1_data_stream_V_din, "Duplicate_U0_dst1_data_stream_V_din");
    sc_trace(mVcdFile, Duplicate_U0_dst1_data_stream_V_write, "Duplicate_U0_dst1_data_stream_V_write");
    sc_trace(mVcdFile, Duplicate_U0_dst2_data_stream_V_din, "Duplicate_U0_dst2_data_stream_V_din");
    sc_trace(mVcdFile, Duplicate_U0_dst2_data_stream_V_write, "Duplicate_U0_dst2_data_stream_V_write");
    sc_trace(mVcdFile, Sobel_U0_ap_start, "Sobel_U0_ap_start");
    sc_trace(mVcdFile, Sobel_U0_ap_done, "Sobel_U0_ap_done");
    sc_trace(mVcdFile, Sobel_U0_ap_continue, "Sobel_U0_ap_continue");
    sc_trace(mVcdFile, Sobel_U0_ap_idle, "Sobel_U0_ap_idle");
    sc_trace(mVcdFile, Sobel_U0_ap_ready, "Sobel_U0_ap_ready");
    sc_trace(mVcdFile, Sobel_U0_start_out, "Sobel_U0_start_out");
    sc_trace(mVcdFile, Sobel_U0_start_write, "Sobel_U0_start_write");
    sc_trace(mVcdFile, Sobel_U0_p_src_data_stream_V_read, "Sobel_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, Sobel_U0_p_dst_data_stream_V_din, "Sobel_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, Sobel_U0_p_dst_data_stream_V_write, "Sobel_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, Sobel_1_U0_ap_start, "Sobel_1_U0_ap_start");
    sc_trace(mVcdFile, Sobel_1_U0_ap_done, "Sobel_1_U0_ap_done");
    sc_trace(mVcdFile, Sobel_1_U0_ap_continue, "Sobel_1_U0_ap_continue");
    sc_trace(mVcdFile, Sobel_1_U0_ap_idle, "Sobel_1_U0_ap_idle");
    sc_trace(mVcdFile, Sobel_1_U0_ap_ready, "Sobel_1_U0_ap_ready");
    sc_trace(mVcdFile, Sobel_1_U0_p_src_data_stream_V_read, "Sobel_1_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, Sobel_1_U0_p_dst_data_stream_V_din, "Sobel_1_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, Sobel_1_U0_p_dst_data_stream_V_write, "Sobel_1_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, gradient_decompositi_U0_ap_start, "gradient_decompositi_U0_ap_start");
    sc_trace(mVcdFile, gradient_decompositi_U0_ap_done, "gradient_decompositi_U0_ap_done");
    sc_trace(mVcdFile, gradient_decompositi_U0_ap_continue, "gradient_decompositi_U0_ap_continue");
    sc_trace(mVcdFile, gradient_decompositi_U0_ap_idle, "gradient_decompositi_U0_ap_idle");
    sc_trace(mVcdFile, gradient_decompositi_U0_ap_ready, "gradient_decompositi_U0_ap_ready");
    sc_trace(mVcdFile, gradient_decompositi_U0_start_out, "gradient_decompositi_U0_start_out");
    sc_trace(mVcdFile, gradient_decompositi_U0_start_write, "gradient_decompositi_U0_start_write");
    sc_trace(mVcdFile, gradient_decompositi_U0_gx_data_stream_V_read, "gradient_decompositi_U0_gx_data_stream_V_read");
    sc_trace(mVcdFile, gradient_decompositi_U0_gy_data_stream_V_read, "gradient_decompositi_U0_gy_data_stream_V_read");
    sc_trace(mVcdFile, gradient_decompositi_U0_gd_data_stream_V_din, "gradient_decompositi_U0_gd_data_stream_V_din");
    sc_trace(mVcdFile, gradient_decompositi_U0_gd_data_stream_V_write, "gradient_decompositi_U0_gd_data_stream_V_write");
    sc_trace(mVcdFile, nonmax_suppression_U0_ap_start, "nonmax_suppression_U0_ap_start");
    sc_trace(mVcdFile, nonmax_suppression_U0_ap_done, "nonmax_suppression_U0_ap_done");
    sc_trace(mVcdFile, nonmax_suppression_U0_ap_continue, "nonmax_suppression_U0_ap_continue");
    sc_trace(mVcdFile, nonmax_suppression_U0_ap_idle, "nonmax_suppression_U0_ap_idle");
    sc_trace(mVcdFile, nonmax_suppression_U0_ap_ready, "nonmax_suppression_U0_ap_ready");
    sc_trace(mVcdFile, nonmax_suppression_U0_start_out, "nonmax_suppression_U0_start_out");
    sc_trace(mVcdFile, nonmax_suppression_U0_start_write, "nonmax_suppression_U0_start_write");
    sc_trace(mVcdFile, nonmax_suppression_U0_gd_data_stream_V_read, "nonmax_suppression_U0_gd_data_stream_V_read");
    sc_trace(mVcdFile, nonmax_suppression_U0_dst_data_stream_V_din, "nonmax_suppression_U0_dst_data_stream_V_din");
    sc_trace(mVcdFile, nonmax_suppression_U0_dst_data_stream_V_write, "nonmax_suppression_U0_dst_data_stream_V_write");
    sc_trace(mVcdFile, hysteresis_U0_ap_start, "hysteresis_U0_ap_start");
    sc_trace(mVcdFile, hysteresis_U0_ap_done, "hysteresis_U0_ap_done");
    sc_trace(mVcdFile, hysteresis_U0_ap_continue, "hysteresis_U0_ap_continue");
    sc_trace(mVcdFile, hysteresis_U0_ap_idle, "hysteresis_U0_ap_idle");
    sc_trace(mVcdFile, hysteresis_U0_ap_ready, "hysteresis_U0_ap_ready");
    sc_trace(mVcdFile, hysteresis_U0_src_data_stream_V_read, "hysteresis_U0_src_data_stream_V_read");
    sc_trace(mVcdFile, hysteresis_U0_dst_data_stream_V_din, "hysteresis_U0_dst_data_stream_V_din");
    sc_trace(mVcdFile, hysteresis_U0_dst_data_stream_V_write, "hysteresis_U0_dst_data_stream_V_write");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_start, "Loop_2_proc_U0_ap_start");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_done, "Loop_2_proc_U0_ap_done");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_continue, "Loop_2_proc_U0_ap_continue");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_idle, "Loop_2_proc_U0_ap_idle");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_ready, "Loop_2_proc_U0_ap_ready");
    sc_trace(mVcdFile, Loop_2_proc_U0_packets_cast_loc_read, "Loop_2_proc_U0_packets_cast_loc_read");
    sc_trace(mVcdFile, Loop_2_proc_U0_canny_edges_data_stream_0_V_read, "Loop_2_proc_U0_canny_edges_data_stream_0_V_read");
    sc_trace(mVcdFile, Loop_2_proc_U0_out_stream_data_V_TDATA, "Loop_2_proc_U0_out_stream_data_V_TDATA");
    sc_trace(mVcdFile, Loop_2_proc_U0_out_stream_data_V_TVALID, "Loop_2_proc_U0_out_stream_data_V_TVALID");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, packets_cast_loc_c_full_n, "packets_cast_loc_c_full_n");
    sc_trace(mVcdFile, packets_cast_loc_c_dout, "packets_cast_loc_c_dout");
    sc_trace(mVcdFile, packets_cast_loc_c_empty_n, "packets_cast_loc_c_empty_n");
    sc_trace(mVcdFile, src_bw_data_stream_0_full_n, "src_bw_data_stream_0_full_n");
    sc_trace(mVcdFile, src_bw_data_stream_0_dout, "src_bw_data_stream_0_dout");
    sc_trace(mVcdFile, src_bw_data_stream_0_empty_n, "src_bw_data_stream_0_empty_n");
    sc_trace(mVcdFile, packets_cast_loc_c35_full_n, "packets_cast_loc_c35_full_n");
    sc_trace(mVcdFile, packets_cast_loc_c35_dout, "packets_cast_loc_c35_dout");
    sc_trace(mVcdFile, packets_cast_loc_c35_empty_n, "packets_cast_loc_c35_empty_n");
    sc_trace(mVcdFile, src1_data_stream_0_s_full_n, "src1_data_stream_0_s_full_n");
    sc_trace(mVcdFile, src1_data_stream_0_s_dout, "src1_data_stream_0_s_dout");
    sc_trace(mVcdFile, src1_data_stream_0_s_empty_n, "src1_data_stream_0_s_empty_n");
    sc_trace(mVcdFile, src2_data_stream_0_s_full_n, "src2_data_stream_0_s_full_n");
    sc_trace(mVcdFile, src2_data_stream_0_s_dout, "src2_data_stream_0_s_dout");
    sc_trace(mVcdFile, src2_data_stream_0_s_empty_n, "src2_data_stream_0_s_empty_n");
    sc_trace(mVcdFile, sobel_gx_data_stream_full_n, "sobel_gx_data_stream_full_n");
    sc_trace(mVcdFile, sobel_gx_data_stream_dout, "sobel_gx_data_stream_dout");
    sc_trace(mVcdFile, sobel_gx_data_stream_empty_n, "sobel_gx_data_stream_empty_n");
    sc_trace(mVcdFile, sobel_gy_data_stream_full_n, "sobel_gy_data_stream_full_n");
    sc_trace(mVcdFile, sobel_gy_data_stream_dout, "sobel_gy_data_stream_dout");
    sc_trace(mVcdFile, sobel_gy_data_stream_empty_n, "sobel_gy_data_stream_empty_n");
    sc_trace(mVcdFile, grad_gd_data_stream_s_full_n, "grad_gd_data_stream_s_full_n");
    sc_trace(mVcdFile, grad_gd_data_stream_s_dout, "grad_gd_data_stream_s_dout");
    sc_trace(mVcdFile, grad_gd_data_stream_s_empty_n, "grad_gd_data_stream_s_empty_n");
    sc_trace(mVcdFile, suppressed_data_stre_full_n, "suppressed_data_stre_full_n");
    sc_trace(mVcdFile, suppressed_data_stre_dout, "suppressed_data_stre_dout");
    sc_trace(mVcdFile, suppressed_data_stre_empty_n, "suppressed_data_stre_empty_n");
    sc_trace(mVcdFile, canny_edges_data_str_full_n, "canny_edges_data_str_full_n");
    sc_trace(mVcdFile, canny_edges_data_str_dout, "canny_edges_data_str_dout");
    sc_trace(mVcdFile, canny_edges_data_str_empty_n, "canny_edges_data_str_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, ap_sync_reg_Block_Mat_exit27932_U0_ap_ready, "ap_sync_reg_Block_Mat_exit27932_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Block_Mat_exit27932_U0_ap_ready, "ap_sync_Block_Mat_exit27932_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit27932_U0_ap_ready_count, "Block_Mat_exit27932_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_Loop_1_proc_U0_ap_ready, "ap_sync_reg_Loop_1_proc_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Loop_1_proc_U0_ap_ready, "ap_sync_Loop_1_proc_U0_ap_ready");
    sc_trace(mVcdFile, Loop_1_proc_U0_ap_ready_count, "Loop_1_proc_U0_ap_ready_count");
    sc_trace(mVcdFile, Block_Mat_exit27932_U0_start_full_n, "Block_Mat_exit27932_U0_start_full_n");
    sc_trace(mVcdFile, Block_Mat_exit27932_U0_start_write, "Block_Mat_exit27932_U0_start_write");
    sc_trace(mVcdFile, start_for_Duplicate_U0_din, "start_for_Duplicate_U0_din");
    sc_trace(mVcdFile, start_for_Duplicate_U0_full_n, "start_for_Duplicate_U0_full_n");
    sc_trace(mVcdFile, start_for_Duplicate_U0_dout, "start_for_Duplicate_U0_dout");
    sc_trace(mVcdFile, start_for_Duplicate_U0_empty_n, "start_for_Duplicate_U0_empty_n");
    sc_trace(mVcdFile, start_for_Loop_2_proc_U0_din, "start_for_Loop_2_proc_U0_din");
    sc_trace(mVcdFile, start_for_Loop_2_proc_U0_full_n, "start_for_Loop_2_proc_U0_full_n");
    sc_trace(mVcdFile, start_for_Loop_2_proc_U0_dout, "start_for_Loop_2_proc_U0_dout");
    sc_trace(mVcdFile, start_for_Loop_2_proc_U0_empty_n, "start_for_Loop_2_proc_U0_empty_n");
    sc_trace(mVcdFile, start_for_Sobel_U0_din, "start_for_Sobel_U0_din");
    sc_trace(mVcdFile, start_for_Sobel_U0_full_n, "start_for_Sobel_U0_full_n");
    sc_trace(mVcdFile, start_for_Sobel_U0_dout, "start_for_Sobel_U0_dout");
    sc_trace(mVcdFile, start_for_Sobel_U0_empty_n, "start_for_Sobel_U0_empty_n");
    sc_trace(mVcdFile, start_for_Sobel_1_U0_din, "start_for_Sobel_1_U0_din");
    sc_trace(mVcdFile, start_for_Sobel_1_U0_full_n, "start_for_Sobel_1_U0_full_n");
    sc_trace(mVcdFile, start_for_Sobel_1_U0_dout, "start_for_Sobel_1_U0_dout");
    sc_trace(mVcdFile, start_for_Sobel_1_U0_empty_n, "start_for_Sobel_1_U0_empty_n");
    sc_trace(mVcdFile, start_for_gradient_decompositi_U0_din, "start_for_gradient_decompositi_U0_din");
    sc_trace(mVcdFile, start_for_gradient_decompositi_U0_full_n, "start_for_gradient_decompositi_U0_full_n");
    sc_trace(mVcdFile, start_for_gradient_decompositi_U0_dout, "start_for_gradient_decompositi_U0_dout");
    sc_trace(mVcdFile, start_for_gradient_decompositi_U0_empty_n, "start_for_gradient_decompositi_U0_empty_n");
    sc_trace(mVcdFile, Sobel_1_U0_start_full_n, "Sobel_1_U0_start_full_n");
    sc_trace(mVcdFile, Sobel_1_U0_start_write, "Sobel_1_U0_start_write");
    sc_trace(mVcdFile, start_for_nonmax_suppression_U0_din, "start_for_nonmax_suppression_U0_din");
    sc_trace(mVcdFile, start_for_nonmax_suppression_U0_full_n, "start_for_nonmax_suppression_U0_full_n");
    sc_trace(mVcdFile, start_for_nonmax_suppression_U0_dout, "start_for_nonmax_suppression_U0_dout");
    sc_trace(mVcdFile, start_for_nonmax_suppression_U0_empty_n, "start_for_nonmax_suppression_U0_empty_n");
    sc_trace(mVcdFile, start_for_hysteresis_U0_din, "start_for_hysteresis_U0_din");
    sc_trace(mVcdFile, start_for_hysteresis_U0_full_n, "start_for_hysteresis_U0_full_n");
    sc_trace(mVcdFile, start_for_hysteresis_U0_dout, "start_for_hysteresis_U0_dout");
    sc_trace(mVcdFile, start_for_hysteresis_U0_empty_n, "start_for_hysteresis_U0_empty_n");
    sc_trace(mVcdFile, hysteresis_U0_start_full_n, "hysteresis_U0_start_full_n");
    sc_trace(mVcdFile, hysteresis_U0_start_write, "hysteresis_U0_start_write");
    sc_trace(mVcdFile, Loop_2_proc_U0_start_full_n, "Loop_2_proc_U0_start_full_n");
    sc_trace(mVcdFile, Loop_2_proc_U0_start_write, "Loop_2_proc_U0_start_write");
#endif

    }
    mHdltvinHandle.open("canny_edge.hdltvin.dat");
    mHdltvoutHandle.open("canny_edge.hdltvout.dat");
}

canny_edge::~canny_edge() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete canny_edge_CONTROL_BUS_s_axi_U;
    delete Block_Mat_exit27932_U0;
    delete Loop_1_proc_U0;
    delete Duplicate_U0;
    delete Sobel_U0;
    delete Sobel_1_U0;
    delete gradient_decompositi_U0;
    delete nonmax_suppression_U0;
    delete hysteresis_U0;
    delete Loop_2_proc_U0;
    delete packets_cast_loc_c_U;
    delete src_bw_data_stream_0_U;
    delete packets_cast_loc_c35_U;
    delete src1_data_stream_0_s_U;
    delete src2_data_stream_0_s_U;
    delete sobel_gx_data_stream_U;
    delete sobel_gy_data_stream_U;
    delete grad_gd_data_stream_s_U;
    delete suppressed_data_stre_U;
    delete canny_edges_data_str_U;
    delete start_for_Duplicate_U0_U;
    delete start_for_Loop_2_proc_U0_U;
    delete start_for_Sobel_U0_U;
    delete start_for_Sobel_1_U0_U;
    delete start_for_gradient_decompositi_U0_U;
    delete start_for_nonmax_suppression_U0_U;
    delete start_for_hysteresis_U0_U;
}

void canny_edge::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void canny_edge::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(Block_Mat_exit27932_U0_ap_ready.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()))) {
        Block_Mat_exit27932_U0_ap_ready_count = (!Block_Mat_exit27932_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_Mat_exit27932_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, Block_Mat_exit27932_U0_ap_ready.read()) && 
                esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0))) {
        Block_Mat_exit27932_U0_ap_ready_count = (!Block_Mat_exit27932_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_Mat_exit27932_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(Loop_1_proc_U0_ap_ready.read(), ap_const_logic_0))) {
        Loop_1_proc_U0_ap_ready_count = (!Loop_1_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Loop_1_proc_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, Loop_1_proc_U0_ap_ready.read()))) {
        Loop_1_proc_U0_ap_ready_count = (!Loop_1_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Loop_1_proc_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Block_Mat_exit27932_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Block_Mat_exit27932_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Block_Mat_exit27932_U0_ap_ready = ap_sync_Block_Mat_exit27932_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Loop_1_proc_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Loop_1_proc_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Loop_1_proc_U0_ap_ready = ap_sync_Loop_1_proc_U0_ap_ready.read();
        }
    }
}

void canny_edge::thread_Block_Mat_exit27932_U0_ap_continue() {
    Block_Mat_exit27932_U0_ap_continue = ap_const_logic_1;
}

void canny_edge::thread_Block_Mat_exit27932_U0_ap_start() {
    Block_Mat_exit27932_U0_ap_start = (ap_start.read() & (ap_sync_reg_Block_Mat_exit27932_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void canny_edge::thread_Block_Mat_exit27932_U0_start_full_n() {
    Block_Mat_exit27932_U0_start_full_n = ap_const_logic_1;
}

void canny_edge::thread_Block_Mat_exit27932_U0_start_write() {
    Block_Mat_exit27932_U0_start_write = ap_const_logic_0;
}

void canny_edge::thread_Duplicate_U0_ap_continue() {
    Duplicate_U0_ap_continue = ap_const_logic_1;
}

void canny_edge::thread_Duplicate_U0_ap_start() {
    Duplicate_U0_ap_start = start_for_Duplicate_U0_empty_n.read();
}

void canny_edge::thread_Duplicate_U0_start_full_n() {
    Duplicate_U0_start_full_n = (start_for_Sobel_U0_full_n.read() & start_for_Sobel_1_U0_full_n.read());
}

void canny_edge::thread_INPUT_data_V_TREADY() {
    INPUT_data_V_TREADY = Loop_1_proc_U0_in_stream_data_V_TREADY.read();
}

void canny_edge::thread_Loop_1_proc_U0_ap_continue() {
    Loop_1_proc_U0_ap_continue = ap_const_logic_1;
}

void canny_edge::thread_Loop_1_proc_U0_ap_start() {
    Loop_1_proc_U0_ap_start = (ap_start.read() & (ap_sync_reg_Loop_1_proc_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void canny_edge::thread_Loop_1_proc_U0_start_full_n() {
    Loop_1_proc_U0_start_full_n = (start_for_Duplicate_U0_full_n.read() & start_for_Loop_2_proc_U0_full_n.read());
}

void canny_edge::thread_Loop_2_proc_U0_ap_continue() {
    Loop_2_proc_U0_ap_continue = ap_const_logic_1;
}

void canny_edge::thread_Loop_2_proc_U0_ap_start() {
    Loop_2_proc_U0_ap_start = start_for_Loop_2_proc_U0_empty_n.read();
}

void canny_edge::thread_Loop_2_proc_U0_start_full_n() {
    Loop_2_proc_U0_start_full_n = ap_const_logic_1;
}

void canny_edge::thread_Loop_2_proc_U0_start_write() {
    Loop_2_proc_U0_start_write = ap_const_logic_0;
}

void canny_edge::thread_OUTPUT_data_V_TDATA() {
    OUTPUT_data_V_TDATA = Loop_2_proc_U0_out_stream_data_V_TDATA.read();
}

void canny_edge::thread_OUTPUT_data_V_TVALID() {
    OUTPUT_data_V_TVALID = Loop_2_proc_U0_out_stream_data_V_TVALID.read();
}

void canny_edge::thread_Sobel_1_U0_ap_continue() {
    Sobel_1_U0_ap_continue = ap_const_logic_1;
}

void canny_edge::thread_Sobel_1_U0_ap_start() {
    Sobel_1_U0_ap_start = start_for_Sobel_1_U0_empty_n.read();
}

void canny_edge::thread_Sobel_1_U0_start_full_n() {
    Sobel_1_U0_start_full_n = ap_const_logic_1;
}

void canny_edge::thread_Sobel_1_U0_start_write() {
    Sobel_1_U0_start_write = ap_const_logic_0;
}

void canny_edge::thread_Sobel_U0_ap_continue() {
    Sobel_U0_ap_continue = ap_const_logic_1;
}

void canny_edge::thread_Sobel_U0_ap_start() {
    Sobel_U0_ap_start = start_for_Sobel_U0_empty_n.read();
}

void canny_edge::thread_ap_done() {
    ap_done = Loop_2_proc_U0_ap_done.read();
}

void canny_edge::thread_ap_idle() {
    ap_idle = (Block_Mat_exit27932_U0_ap_idle.read() & Loop_1_proc_U0_ap_idle.read() & Duplicate_U0_ap_idle.read() & Sobel_U0_ap_idle.read() & Sobel_1_U0_ap_idle.read() & gradient_decompositi_U0_ap_idle.read() & nonmax_suppression_U0_ap_idle.read() & hysteresis_U0_ap_idle.read() & Loop_2_proc_U0_ap_idle.read());
}

void canny_edge::thread_ap_ready() {
    ap_ready = ap_sync_ready.read();
}

void canny_edge::thread_ap_rst_n_AXI_LITE_clk_inv() {
    ap_rst_n_AXI_LITE_clk_inv =  (sc_logic) (~ap_rst_n_AXI_LITE_clk.read());
}

void canny_edge::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void canny_edge::thread_ap_sync_Block_Mat_exit27932_U0_ap_ready() {
    ap_sync_Block_Mat_exit27932_U0_ap_ready = (Block_Mat_exit27932_U0_ap_ready.read() | ap_sync_reg_Block_Mat_exit27932_U0_ap_ready.read());
}

void canny_edge::thread_ap_sync_Loop_1_proc_U0_ap_ready() {
    ap_sync_Loop_1_proc_U0_ap_ready = (Loop_1_proc_U0_ap_ready.read() | ap_sync_reg_Loop_1_proc_U0_ap_ready.read());
}

void canny_edge::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_1;
}

void canny_edge::thread_ap_sync_done() {
    ap_sync_done = Loop_2_proc_U0_ap_done.read();
}

void canny_edge::thread_ap_sync_ready() {
    ap_sync_ready = (ap_sync_Block_Mat_exit27932_U0_ap_ready.read() & ap_sync_Loop_1_proc_U0_ap_ready.read());
}

void canny_edge::thread_gradient_decompositi_U0_ap_continue() {
    gradient_decompositi_U0_ap_continue = ap_const_logic_1;
}

void canny_edge::thread_gradient_decompositi_U0_ap_start() {
    gradient_decompositi_U0_ap_start = start_for_gradient_decompositi_U0_empty_n.read();
}

void canny_edge::thread_hysteresis_U0_ap_continue() {
    hysteresis_U0_ap_continue = ap_const_logic_1;
}

void canny_edge::thread_hysteresis_U0_ap_start() {
    hysteresis_U0_ap_start = start_for_hysteresis_U0_empty_n.read();
}

void canny_edge::thread_hysteresis_U0_start_full_n() {
    hysteresis_U0_start_full_n = ap_const_logic_1;
}

void canny_edge::thread_hysteresis_U0_start_write() {
    hysteresis_U0_start_write = ap_const_logic_0;
}

void canny_edge::thread_nonmax_suppression_U0_ap_continue() {
    nonmax_suppression_U0_ap_continue = ap_const_logic_1;
}

void canny_edge::thread_nonmax_suppression_U0_ap_start() {
    nonmax_suppression_U0_ap_start = start_for_nonmax_suppression_U0_empty_n.read();
}

void canny_edge::thread_start_for_Duplicate_U0_din() {
    start_for_Duplicate_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void canny_edge::thread_start_for_Loop_2_proc_U0_din() {
    start_for_Loop_2_proc_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void canny_edge::thread_start_for_Sobel_1_U0_din() {
    start_for_Sobel_1_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void canny_edge::thread_start_for_Sobel_U0_din() {
    start_for_Sobel_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void canny_edge::thread_start_for_gradient_decompositi_U0_din() {
    start_for_gradient_decompositi_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void canny_edge::thread_start_for_hysteresis_U0_din() {
    start_for_hysteresis_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void canny_edge::thread_start_for_nonmax_suppression_U0_din() {
    start_for_nonmax_suppression_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void canny_edge::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_CONTROL_BUS_AWVALID\" :  \"" << s_axi_CONTROL_BUS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_CONTROL_BUS_AWREADY\" :  \"" << s_axi_CONTROL_BUS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_AWADDR\" :  \"" << s_axi_CONTROL_BUS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WVALID\" :  \"" << s_axi_CONTROL_BUS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_WREADY\" :  \"" << s_axi_CONTROL_BUS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WDATA\" :  \"" << s_axi_CONTROL_BUS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WSTRB\" :  \"" << s_axi_CONTROL_BUS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARVALID\" :  \"" << s_axi_CONTROL_BUS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARREADY\" :  \"" << s_axi_CONTROL_BUS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARADDR\" :  \"" << s_axi_CONTROL_BUS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RVALID\" :  \"" << s_axi_CONTROL_BUS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_RREADY\" :  \"" << s_axi_CONTROL_BUS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RDATA\" :  \"" << s_axi_CONTROL_BUS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RRESP\" :  \"" << s_axi_CONTROL_BUS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BVALID\" :  \"" << s_axi_CONTROL_BUS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_BREADY\" :  \"" << s_axi_CONTROL_BUS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BRESP\" :  \"" << s_axi_CONTROL_BUS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n_AXI_LITE_clk\" :  \"" << ap_rst_n_AXI_LITE_clk.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_data_V_TDATA\" :  \"" << INPUT_data_V_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_data_V_TDATA\" :  \"" << OUTPUT_data_V_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_data_V_TVALID\" :  \"" << INPUT_data_V_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"INPUT_data_V_TREADY\" :  \"" << INPUT_data_V_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_data_V_TVALID\" :  \"" << OUTPUT_data_V_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"OUTPUT_data_V_TREADY\" :  \"" << OUTPUT_data_V_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

