// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "hysteresis.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic hysteresis::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic hysteresis::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> hysteresis::ap_ST_fsm_state1 = "1";
const sc_lv<11> hysteresis::ap_ST_fsm_state2 = "10";
const sc_lv<11> hysteresis::ap_ST_fsm_state3 = "100";
const sc_lv<11> hysteresis::ap_ST_fsm_state4 = "1000";
const sc_lv<11> hysteresis::ap_ST_fsm_state5 = "10000";
const sc_lv<11> hysteresis::ap_ST_fsm_state6 = "100000";
const sc_lv<11> hysteresis::ap_ST_fsm_state7 = "1000000";
const sc_lv<11> hysteresis::ap_ST_fsm_state8 = "10000000";
const sc_lv<11> hysteresis::ap_ST_fsm_state9 = "100000000";
const sc_lv<11> hysteresis::ap_ST_fsm_state10 = "1000000000";
const sc_lv<11> hysteresis::ap_ST_fsm_state11 = "10000000000";
const sc_lv<32> hysteresis::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> hysteresis::ap_const_lv32_7 = "111";
const sc_lv<1> hysteresis::ap_const_lv1_1 = "1";
const sc_lv<32> hysteresis::ap_const_lv32_A = "1010";
const sc_lv<1> hysteresis::ap_const_lv1_0 = "0";
const sc_lv<32> hysteresis::ap_const_lv32_1 = "1";
const sc_lv<32> hysteresis::ap_const_lv32_5 = "101";
const sc_lv<32> hysteresis::ap_const_lv32_6 = "110";
const sc_lv<32> hysteresis::ap_const_lv32_8 = "1000";
const sc_lv<32> hysteresis::ap_const_lv32_9 = "1001";
const sc_lv<65> hysteresis::ap_const_lv65_0 = "00000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<33> hysteresis::ap_const_lv33_1 = "1";
const sc_lv<33> hysteresis::ap_const_lv33_1FFFFFFFF = "111111111111111111111111111111111";
const sc_lv<32> hysteresis::ap_const_lv32_1F = "11111";
const sc_lv<31> hysteresis::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<65> hysteresis::ap_const_lv65_1 = "1";
const sc_lv<8> hysteresis::ap_const_lv8_FF = "11111111";
const sc_lv<8> hysteresis::ap_const_lv8_0 = "00000000";
const bool hysteresis::ap_const_boolean_1 = true;

hysteresis::hysteresis(sc_module_name name) : sc_module(name), mVcdFile(0) {
    linebuff_val_0_U = new hysteresis_linebuff_val_0("linebuff_val_0_U");
    linebuff_val_0_U->clk(ap_clk);
    linebuff_val_0_U->reset(ap_rst);
    linebuff_val_0_U->address0(linebuff_val_0_address0);
    linebuff_val_0_U->ce0(linebuff_val_0_ce0);
    linebuff_val_0_U->we0(linebuff_val_0_we0);
    linebuff_val_0_U->d0(element_gd_1_fu_152);
    linebuff_val_0_U->q0(linebuff_val_0_q0);
    linebuff_val_1_U = new hysteresis_linebuff_val_0("linebuff_val_1_U");
    linebuff_val_1_U->clk(ap_clk);
    linebuff_val_1_U->reset(ap_rst);
    linebuff_val_1_U->address0(linebuff_val_1_address0);
    linebuff_val_1_U->ce0(linebuff_val_1_ce0);
    linebuff_val_1_U->we0(linebuff_val_1_we0);
    linebuff_val_1_U->d0(tmp0_reg_1092);
    linebuff_val_1_U->q0(linebuff_val_1_q0);
    canny_edge_mul_33ns_33ns_65_5_1_U63 = new canny_edge_mul_33ns_33ns_65_5_1<1,5,33,33,65>("canny_edge_mul_33ns_33ns_65_5_1_U63");
    canny_edge_mul_33ns_33ns_65_5_1_U63->clk(ap_clk);
    canny_edge_mul_33ns_33ns_65_5_1_U63->reset(ap_rst);
    canny_edge_mul_33ns_33ns_65_5_1_U63->din0(grp_fu_301_p0);
    canny_edge_mul_33ns_33ns_65_5_1_U63->din1(grp_fu_301_p1);
    canny_edge_mul_33ns_33ns_65_5_1_U63->ce(ap_var_for_const0);
    canny_edge_mul_33ns_33ns_65_5_1_U63->dout(grp_fu_301_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state11);
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( or_cond5_fu_825_p2 );

    SC_METHOD(thread_ap_block_state8);
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( or_cond_fu_483_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten_fu_371_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten_fu_371_p2 );

    SC_METHOD(thread_col_assign_mid2_fu_447_p3);
    sensitive << ( tmp_28_reg_1001 );
    sensitive << ( t_V_2_reg_254 );

    SC_METHOD(thread_dst_data_stream_V_blk_n);
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( or_cond5_fu_825_p2 );

    SC_METHOD(thread_dst_data_stream_V_din);
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( or_cond5_fu_825_p2 );
    sensitive << ( tmp_45_fu_805_p2 );

    SC_METHOD(thread_dst_data_stream_V_write);
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( or_cond5_fu_825_p2 );

    SC_METHOD(thread_exitcond_flatten_fu_371_p2);
    sensitive << ( grp_fu_301_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( indvar_flatten_reg_232 );

    SC_METHOD(thread_grp_fu_301_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_fu_301_p00 );

    SC_METHOD(thread_grp_fu_301_p00);
    sensitive << ( ret_V_fu_279_p2 );

    SC_METHOD(thread_grp_fu_301_p1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_fu_301_p10 );

    SC_METHOD(thread_grp_fu_301_p10);
    sensitive << ( ret_V_4_fu_289_p2 );

    SC_METHOD(thread_i_V_fu_397_p2);
    sensitive << ( t_V_reg_243 );

    SC_METHOD(thread_icmp2_fu_422_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten_fu_371_p2 );
    sensitive << ( tmp_46_fu_412_p4 );

    SC_METHOD(thread_icmp3_fu_557_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_50_fu_548_p4 );

    SC_METHOD(thread_icmp_fu_345_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_fu_335_p4 );

    SC_METHOD(thread_indvar_flatten_next_fu_376_p2);
    sensitive << ( indvar_flatten_reg_232 );

    SC_METHOD(thread_j_V_fu_830_p2);
    sensitive << ( col_assign_mid2_reg_1043 );

    SC_METHOD(thread_lhs_V_2_cast_fu_285_p1);
    sensitive << ( src_cols_V );

    SC_METHOD(thread_lhs_V_cast_fu_275_p1);
    sensitive << ( src_rows_V );

    SC_METHOD(thread_linebuff_val_0_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_31_fu_494_p1 );
    sensitive << ( tmp_32_fu_514_p1 );

    SC_METHOD(thread_linebuff_val_0_ce0);
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( or_cond_fu_483_p2 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_linebuff_val_0_we0);
    sensitive << ( or_cond_reg_1078 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_linebuff_val_1_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( linebuff_val_1_addr_reg_1082 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_31_fu_494_p1 );

    SC_METHOD(thread_linebuff_val_1_ce0);
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( or_cond_fu_483_p2 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_linebuff_val_1_we0);
    sensitive << ( tmp_29_reg_1071 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_or_cond4_fu_577_p2);
    sensitive << ( tmp25_fu_572_p2 );
    sensitive << ( tmp24_fu_567_p2 );

    SC_METHOD(thread_or_cond5_fu_825_p2);
    sensitive << ( tmp_27_mid2_reg_1056 );
    sensitive << ( tmp_47_fu_820_p2 );

    SC_METHOD(thread_or_cond_fu_483_p2);
    sensitive << ( tmp_29_fu_478_p2 );
    sensitive << ( tmp_25_mid2_fu_454_p3 );

    SC_METHOD(thread_ret_V_4_fu_289_p2);
    sensitive << ( lhs_V_2_cast_fu_285_p1 );

    SC_METHOD(thread_ret_V_5_fu_312_p2);
    sensitive << ( lhs_V_2_cast_fu_285_p1 );

    SC_METHOD(thread_ret_V_fu_279_p2);
    sensitive << ( lhs_V_cast_fu_275_p1 );

    SC_METHOD(thread_rev1_fu_649_p2);
    sensitive << ( slt1_fu_644_p2 );

    SC_METHOD(thread_rev2_fu_660_p2);
    sensitive << ( slt2_fu_655_p2 );

    SC_METHOD(thread_rev3_fu_671_p2);
    sensitive << ( slt3_fu_666_p2 );

    SC_METHOD(thread_rev4_fu_741_p2);
    sensitive << ( slt4_reg_1107 );

    SC_METHOD(thread_rev5_fu_746_p2);
    sensitive << ( slt5_reg_1112 );

    SC_METHOD(thread_rev6_fu_751_p2);
    sensitive << ( slt6_reg_1117 );

    SC_METHOD(thread_rev7_fu_756_p2);
    sensitive << ( slt7_reg_1122 );

    SC_METHOD(thread_rev8_fu_761_p2);
    sensitive << ( slt8_reg_1127 );

    SC_METHOD(thread_rev_fu_638_p2);
    sensitive << ( slt_fu_633_p2 );

    SC_METHOD(thread_sel_tmp4_fu_790_p2);
    sensitive << ( tmp27_reg_1132 );
    sensitive << ( tmp31_fu_784_p2 );

    SC_METHOD(thread_sel_tmp6_demorgan_fu_621_p2);
    sensitive << ( or_cond4_fu_577_p2 );
    sensitive << ( tmp_36_fu_587_p2 );

    SC_METHOD(thread_sel_tmp6_fu_627_p2);
    sensitive << ( sel_tmp6_demorgan_fu_621_p2 );

    SC_METHOD(thread_slt1_fu_644_p2);
    sensitive << ( threshold_high );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_37_fu_592_p1 );

    SC_METHOD(thread_slt2_fu_655_p2);
    sensitive << ( threshold_high );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_38_fu_596_p1 );

    SC_METHOD(thread_slt3_fu_666_p2);
    sensitive << ( threshold_high );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_39_fu_600_p1 );

    SC_METHOD(thread_slt4_fu_677_p2);
    sensitive << ( threshold_high );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_40_fu_603_p1 );

    SC_METHOD(thread_slt5_fu_682_p2);
    sensitive << ( threshold_high );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_41_fu_607_p1 );

    SC_METHOD(thread_slt6_fu_687_p2);
    sensitive << ( threshold_high );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_42_fu_610_p1 );

    SC_METHOD(thread_slt7_fu_692_p2);
    sensitive << ( threshold_high );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_43_fu_614_p1 );

    SC_METHOD(thread_slt8_fu_697_p2);
    sensitive << ( threshold_high );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_44_fu_618_p1 );

    SC_METHOD(thread_slt_fu_633_p2);
    sensitive << ( threshold_high );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_35_fu_583_p1 );

    SC_METHOD(thread_src_data_stream_V_blk_n);
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( or_cond_fu_483_p2 );

    SC_METHOD(thread_src_data_stream_V_read);
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( or_cond_fu_483_p2 );

    SC_METHOD(thread_t_V_mid2_fu_439_p3);
    sensitive << ( tmp_28_fu_366_p2 );
    sensitive << ( t_V_reg_243 );
    sensitive << ( i_V_fu_397_p2 );

    SC_METHOD(thread_tmp24_fu_567_p2);
    sensitive << ( tmp_28_mid2_reg_1061 );
    sensitive << ( icmp3_fu_557_p2 );

    SC_METHOD(thread_tmp25_fu_572_p2);
    sensitive << ( tmp_26_mid2_reg_1051 );
    sensitive << ( tmp_34_fu_563_p2 );

    SC_METHOD(thread_tmp26_fu_702_p2);
    sensitive << ( rev_fu_638_p2 );
    sensitive << ( sel_tmp6_fu_627_p2 );

    SC_METHOD(thread_tmp27_fu_720_p2);
    sensitive << ( tmp29_fu_714_p2 );
    sensitive << ( tmp26_fu_702_p2 );

    SC_METHOD(thread_tmp28_fu_708_p2);
    sensitive << ( rev2_fu_660_p2 );
    sensitive << ( rev3_fu_671_p2 );

    SC_METHOD(thread_tmp29_fu_714_p2);
    sensitive << ( tmp28_fu_708_p2 );
    sensitive << ( rev1_fu_649_p2 );

    SC_METHOD(thread_tmp30_fu_766_p2);
    sensitive << ( rev4_fu_741_p2 );
    sensitive << ( rev5_fu_746_p2 );

    SC_METHOD(thread_tmp31_fu_784_p2);
    sensitive << ( tmp33_fu_778_p2 );
    sensitive << ( tmp30_fu_766_p2 );

    SC_METHOD(thread_tmp32_fu_772_p2);
    sensitive << ( rev7_fu_756_p2 );
    sensitive << ( rev8_fu_761_p2 );

    SC_METHOD(thread_tmp33_fu_778_p2);
    sensitive << ( tmp32_fu_772_p2 );
    sensitive << ( rev6_fu_751_p2 );

    SC_METHOD(thread_tmp34_fu_795_p2);
    sensitive << ( or_cond4_reg_1097 );
    sensitive << ( sel_tmp4_fu_790_p2 );

    SC_METHOD(thread_tmp_24_fu_330_p2);
    sensitive << ( src_rows_V );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( t_V_reg_243 );

    SC_METHOD(thread_tmp_25_mid1_fu_407_p2);
    sensitive << ( src_rows_V );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten_fu_371_p2 );
    sensitive << ( i_V_fu_397_p2 );

    SC_METHOD(thread_tmp_25_mid2_fu_454_p3);
    sensitive << ( tmp_24_reg_981 );
    sensitive << ( tmp_28_reg_1001 );
    sensitive << ( tmp_25_mid1_reg_1018 );

    SC_METHOD(thread_tmp_26_fu_351_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( t_V_reg_243 );

    SC_METHOD(thread_tmp_26_mid2_fu_459_p3);
    sensitive << ( icmp_reg_986 );
    sensitive << ( tmp_28_reg_1001 );
    sensitive << ( icmp2_reg_1023 );

    SC_METHOD(thread_tmp_27_fu_357_p2);
    sensitive << ( tmp_s_fu_307_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_cast_mid1_fu_326_p1 );

    SC_METHOD(thread_tmp_27_mid1_fu_428_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten_fu_371_p2 );
    sensitive << ( i_V_fu_397_p2 );

    SC_METHOD(thread_tmp_27_mid2_fu_464_p3);
    sensitive << ( tmp_26_reg_991 );
    sensitive << ( tmp_28_reg_1001 );
    sensitive << ( tmp_27_mid1_reg_1028 );

    SC_METHOD(thread_tmp_28_fu_366_p2);
    sensitive << ( ret_V_4_fu_289_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_30_cast_fu_362_p1 );

    SC_METHOD(thread_tmp_28_mid1_fu_434_p2);
    sensitive << ( tmp_s_fu_307_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten_fu_371_p2 );
    sensitive << ( tmp_cast_fu_403_p1 );

    SC_METHOD(thread_tmp_28_mid2_fu_469_p3);
    sensitive << ( tmp_27_reg_996 );
    sensitive << ( tmp_28_reg_1001 );
    sensitive << ( tmp_28_mid1_reg_1033 );

    SC_METHOD(thread_tmp_29_fu_478_p2);
    sensitive << ( src_cols_V );
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( or_cond_fu_483_p2 );
    sensitive << ( col_assign_mid2_fu_447_p3 );

    SC_METHOD(thread_tmp_30_cast_fu_362_p1);
    sensitive << ( t_V_2_reg_254 );

    SC_METHOD(thread_tmp_30_cast_mid2_cas_fu_474_p1);
    sensitive << ( col_assign_mid2_fu_447_p3 );

    SC_METHOD(thread_tmp_31_fu_494_p1);
    sensitive << ( col_assign_mid2_fu_447_p3 );

    SC_METHOD(thread_tmp_32_fu_514_p1);
    sensitive << ( col_assign_mid2_reg_1043 );

    SC_METHOD(thread_tmp_34_fu_563_p2);
    sensitive << ( ret_V_5_fu_312_p2 );
    sensitive << ( tmp_30_cast_mid2_cas_reg_1066 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_tmp_35_fu_583_p1);
    sensitive << ( win_val_1_1_fu_128 );

    SC_METHOD(thread_tmp_36_fu_587_p2);
    sensitive << ( threshold_low );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_35_fu_583_p1 );

    SC_METHOD(thread_tmp_37_fu_592_p1);
    sensitive << ( win_val_0_0_0_win_va_fu_541_p3 );

    SC_METHOD(thread_tmp_38_fu_596_p1);
    sensitive << ( win_val_0_1_fu_120 );

    SC_METHOD(thread_tmp_39_fu_600_p1);
    sensitive << ( win_val_0_1_2_load_reg_966 );

    SC_METHOD(thread_tmp_40_fu_603_p1);
    sensitive << ( win_val_1_0_0_win_va_fu_534_p3 );

    SC_METHOD(thread_tmp_41_fu_607_p1);
    sensitive << ( win_val_1_1_2_load_reg_971 );

    SC_METHOD(thread_tmp_42_fu_610_p1);
    sensitive << ( win_val_2_0_0_win_va_fu_527_p3 );

    SC_METHOD(thread_tmp_43_fu_614_p1);
    sensitive << ( win_val_2_1_fu_136 );

    SC_METHOD(thread_tmp_44_fu_618_p1);
    sensitive << ( win_val_2_1_2_load_reg_976 );

    SC_METHOD(thread_tmp_45_fu_805_p2);
    sensitive << ( tmp_55_demorgan_fu_800_p2 );

    SC_METHOD(thread_tmp_46_fu_412_p4);
    sensitive << ( i_V_fu_397_p2 );

    SC_METHOD(thread_tmp_47_fu_820_p2);
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( or_cond5_fu_825_p2 );
    sensitive << ( col_assign_mid2_reg_1043 );

    SC_METHOD(thread_tmp_50_fu_548_p4);
    sensitive << ( col_assign_mid2_reg_1043 );

    SC_METHOD(thread_tmp_55_demorgan_fu_800_p2);
    sensitive << ( tmp_36_reg_1102 );
    sensitive << ( tmp34_fu_795_p2 );

    SC_METHOD(thread_tmp_cast_fu_403_p1);
    sensitive << ( i_V_fu_397_p2 );

    SC_METHOD(thread_tmp_cast_mid1_fu_326_p1);
    sensitive << ( t_V_reg_243 );

    SC_METHOD(thread_tmp_fu_335_p4);
    sensitive << ( t_V_reg_243 );

    SC_METHOD(thread_tmp_s_fu_307_p2);
    sensitive << ( lhs_V_cast_fu_275_p1 );

    SC_METHOD(thread_win_val_0_0_0_win_va_fu_541_p3);
    sensitive << ( tmp_29_reg_1071 );
    sensitive << ( win_val_0_1_fu_120 );
    sensitive << ( element_gd_1_fu_152 );

    SC_METHOD(thread_win_val_1_0_0_win_va_fu_534_p3);
    sensitive << ( tmp_29_reg_1071 );
    sensitive << ( win_val_1_1_fu_128 );
    sensitive << ( tmp0_1_fu_148 );

    SC_METHOD(thread_win_val_2_0_0_win_va_fu_527_p3);
    sensitive << ( tmp_29_reg_1071 );
    sensitive << ( win_val_2_1_fu_136 );
    sensitive << ( tmp1_1_fu_144 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( or_cond_fu_483_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( or_cond5_fu_825_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_flatten_fu_371_p2 );
    sensitive << ( tmp_29_fu_478_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "hysteresis_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, src_rows_V, "(port)src_rows_V");
    sc_trace(mVcdFile, src_cols_V, "(port)src_cols_V");
    sc_trace(mVcdFile, src_data_stream_V_dout, "(port)src_data_stream_V_dout");
    sc_trace(mVcdFile, src_data_stream_V_empty_n, "(port)src_data_stream_V_empty_n");
    sc_trace(mVcdFile, src_data_stream_V_read, "(port)src_data_stream_V_read");
    sc_trace(mVcdFile, dst_data_stream_V_din, "(port)dst_data_stream_V_din");
    sc_trace(mVcdFile, dst_data_stream_V_full_n, "(port)dst_data_stream_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_V_write, "(port)dst_data_stream_V_write");
    sc_trace(mVcdFile, threshold_low, "(port)threshold_low");
    sc_trace(mVcdFile, threshold_high, "(port)threshold_high");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, src_data_stream_V_blk_n, "src_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, or_cond_fu_483_p2, "or_cond_fu_483_p2");
    sc_trace(mVcdFile, dst_data_stream_V_blk_n, "dst_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, or_cond5_fu_825_p2, "or_cond5_fu_825_p2");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, lhs_V_cast_fu_275_p1, "lhs_V_cast_fu_275_p1");
    sc_trace(mVcdFile, ret_V_fu_279_p2, "ret_V_fu_279_p2");
    sc_trace(mVcdFile, lhs_V_2_cast_fu_285_p1, "lhs_V_2_cast_fu_285_p1");
    sc_trace(mVcdFile, ret_V_4_fu_289_p2, "ret_V_4_fu_289_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_s_fu_307_p2, "tmp_s_fu_307_p2");
    sc_trace(mVcdFile, ret_V_5_fu_312_p2, "ret_V_5_fu_312_p2");
    sc_trace(mVcdFile, grp_fu_301_p2, "grp_fu_301_p2");
    sc_trace(mVcdFile, win_val_0_1_2_load_reg_966, "win_val_0_1_2_load_reg_966");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, win_val_1_1_2_load_reg_971, "win_val_1_1_2_load_reg_971");
    sc_trace(mVcdFile, win_val_2_1_2_load_reg_976, "win_val_2_1_2_load_reg_976");
    sc_trace(mVcdFile, tmp_24_fu_330_p2, "tmp_24_fu_330_p2");
    sc_trace(mVcdFile, tmp_24_reg_981, "tmp_24_reg_981");
    sc_trace(mVcdFile, icmp_fu_345_p2, "icmp_fu_345_p2");
    sc_trace(mVcdFile, icmp_reg_986, "icmp_reg_986");
    sc_trace(mVcdFile, tmp_26_fu_351_p2, "tmp_26_fu_351_p2");
    sc_trace(mVcdFile, tmp_26_reg_991, "tmp_26_reg_991");
    sc_trace(mVcdFile, tmp_27_fu_357_p2, "tmp_27_fu_357_p2");
    sc_trace(mVcdFile, tmp_27_reg_996, "tmp_27_reg_996");
    sc_trace(mVcdFile, tmp_28_fu_366_p2, "tmp_28_fu_366_p2");
    sc_trace(mVcdFile, tmp_28_reg_1001, "tmp_28_reg_1001");
    sc_trace(mVcdFile, indvar_flatten_next_fu_376_p2, "indvar_flatten_next_fu_376_p2");
    sc_trace(mVcdFile, indvar_flatten_next_reg_1013, "indvar_flatten_next_reg_1013");
    sc_trace(mVcdFile, tmp_25_mid1_fu_407_p2, "tmp_25_mid1_fu_407_p2");
    sc_trace(mVcdFile, tmp_25_mid1_reg_1018, "tmp_25_mid1_reg_1018");
    sc_trace(mVcdFile, exitcond_flatten_fu_371_p2, "exitcond_flatten_fu_371_p2");
    sc_trace(mVcdFile, icmp2_fu_422_p2, "icmp2_fu_422_p2");
    sc_trace(mVcdFile, icmp2_reg_1023, "icmp2_reg_1023");
    sc_trace(mVcdFile, tmp_27_mid1_fu_428_p2, "tmp_27_mid1_fu_428_p2");
    sc_trace(mVcdFile, tmp_27_mid1_reg_1028, "tmp_27_mid1_reg_1028");
    sc_trace(mVcdFile, tmp_28_mid1_fu_434_p2, "tmp_28_mid1_fu_434_p2");
    sc_trace(mVcdFile, tmp_28_mid1_reg_1033, "tmp_28_mid1_reg_1033");
    sc_trace(mVcdFile, t_V_mid2_fu_439_p3, "t_V_mid2_fu_439_p3");
    sc_trace(mVcdFile, t_V_mid2_reg_1038, "t_V_mid2_reg_1038");
    sc_trace(mVcdFile, col_assign_mid2_fu_447_p3, "col_assign_mid2_fu_447_p3");
    sc_trace(mVcdFile, col_assign_mid2_reg_1043, "col_assign_mid2_reg_1043");
    sc_trace(mVcdFile, ap_block_state8, "ap_block_state8");
    sc_trace(mVcdFile, tmp_26_mid2_fu_459_p3, "tmp_26_mid2_fu_459_p3");
    sc_trace(mVcdFile, tmp_26_mid2_reg_1051, "tmp_26_mid2_reg_1051");
    sc_trace(mVcdFile, tmp_27_mid2_fu_464_p3, "tmp_27_mid2_fu_464_p3");
    sc_trace(mVcdFile, tmp_27_mid2_reg_1056, "tmp_27_mid2_reg_1056");
    sc_trace(mVcdFile, tmp_28_mid2_fu_469_p3, "tmp_28_mid2_fu_469_p3");
    sc_trace(mVcdFile, tmp_28_mid2_reg_1061, "tmp_28_mid2_reg_1061");
    sc_trace(mVcdFile, tmp_30_cast_mid2_cas_fu_474_p1, "tmp_30_cast_mid2_cas_fu_474_p1");
    sc_trace(mVcdFile, tmp_30_cast_mid2_cas_reg_1066, "tmp_30_cast_mid2_cas_reg_1066");
    sc_trace(mVcdFile, tmp_29_fu_478_p2, "tmp_29_fu_478_p2");
    sc_trace(mVcdFile, tmp_29_reg_1071, "tmp_29_reg_1071");
    sc_trace(mVcdFile, or_cond_reg_1078, "or_cond_reg_1078");
    sc_trace(mVcdFile, linebuff_val_1_addr_reg_1082, "linebuff_val_1_addr_reg_1082");
    sc_trace(mVcdFile, linebuff_val_0_q0, "linebuff_val_0_q0");
    sc_trace(mVcdFile, tmp0_reg_1092, "tmp0_reg_1092");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, or_cond4_fu_577_p2, "or_cond4_fu_577_p2");
    sc_trace(mVcdFile, or_cond4_reg_1097, "or_cond4_reg_1097");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_36_fu_587_p2, "tmp_36_fu_587_p2");
    sc_trace(mVcdFile, tmp_36_reg_1102, "tmp_36_reg_1102");
    sc_trace(mVcdFile, slt4_fu_677_p2, "slt4_fu_677_p2");
    sc_trace(mVcdFile, slt4_reg_1107, "slt4_reg_1107");
    sc_trace(mVcdFile, slt5_fu_682_p2, "slt5_fu_682_p2");
    sc_trace(mVcdFile, slt5_reg_1112, "slt5_reg_1112");
    sc_trace(mVcdFile, slt6_fu_687_p2, "slt6_fu_687_p2");
    sc_trace(mVcdFile, slt6_reg_1117, "slt6_reg_1117");
    sc_trace(mVcdFile, slt7_fu_692_p2, "slt7_fu_692_p2");
    sc_trace(mVcdFile, slt7_reg_1122, "slt7_reg_1122");
    sc_trace(mVcdFile, slt8_fu_697_p2, "slt8_fu_697_p2");
    sc_trace(mVcdFile, slt8_reg_1127, "slt8_reg_1127");
    sc_trace(mVcdFile, tmp27_fu_720_p2, "tmp27_fu_720_p2");
    sc_trace(mVcdFile, tmp27_reg_1132, "tmp27_reg_1132");
    sc_trace(mVcdFile, j_V_fu_830_p2, "j_V_fu_830_p2");
    sc_trace(mVcdFile, ap_block_state11, "ap_block_state11");
    sc_trace(mVcdFile, linebuff_val_0_address0, "linebuff_val_0_address0");
    sc_trace(mVcdFile, linebuff_val_0_ce0, "linebuff_val_0_ce0");
    sc_trace(mVcdFile, linebuff_val_0_we0, "linebuff_val_0_we0");
    sc_trace(mVcdFile, linebuff_val_1_address0, "linebuff_val_1_address0");
    sc_trace(mVcdFile, linebuff_val_1_ce0, "linebuff_val_1_ce0");
    sc_trace(mVcdFile, linebuff_val_1_we0, "linebuff_val_1_we0");
    sc_trace(mVcdFile, linebuff_val_1_q0, "linebuff_val_1_q0");
    sc_trace(mVcdFile, indvar_flatten_reg_232, "indvar_flatten_reg_232");
    sc_trace(mVcdFile, t_V_reg_243, "t_V_reg_243");
    sc_trace(mVcdFile, t_V_2_reg_254, "t_V_2_reg_254");
    sc_trace(mVcdFile, tmp_31_fu_494_p1, "tmp_31_fu_494_p1");
    sc_trace(mVcdFile, tmp_32_fu_514_p1, "tmp_32_fu_514_p1");
    sc_trace(mVcdFile, win_val_0_1_fu_120, "win_val_0_1_fu_120");
    sc_trace(mVcdFile, win_val_0_0_0_win_va_fu_541_p3, "win_val_0_0_0_win_va_fu_541_p3");
    sc_trace(mVcdFile, win_val_0_1_2_fu_124, "win_val_0_1_2_fu_124");
    sc_trace(mVcdFile, win_val_1_1_fu_128, "win_val_1_1_fu_128");
    sc_trace(mVcdFile, win_val_1_0_0_win_va_fu_534_p3, "win_val_1_0_0_win_va_fu_534_p3");
    sc_trace(mVcdFile, win_val_1_1_2_fu_132, "win_val_1_1_2_fu_132");
    sc_trace(mVcdFile, win_val_2_1_fu_136, "win_val_2_1_fu_136");
    sc_trace(mVcdFile, win_val_2_0_0_win_va_fu_527_p3, "win_val_2_0_0_win_va_fu_527_p3");
    sc_trace(mVcdFile, win_val_2_1_2_fu_140, "win_val_2_1_2_fu_140");
    sc_trace(mVcdFile, tmp1_1_fu_144, "tmp1_1_fu_144");
    sc_trace(mVcdFile, tmp0_1_fu_148, "tmp0_1_fu_148");
    sc_trace(mVcdFile, element_gd_1_fu_152, "element_gd_1_fu_152");
    sc_trace(mVcdFile, grp_fu_301_p0, "grp_fu_301_p0");
    sc_trace(mVcdFile, grp_fu_301_p1, "grp_fu_301_p1");
    sc_trace(mVcdFile, tmp_fu_335_p4, "tmp_fu_335_p4");
    sc_trace(mVcdFile, tmp_cast_mid1_fu_326_p1, "tmp_cast_mid1_fu_326_p1");
    sc_trace(mVcdFile, tmp_30_cast_fu_362_p1, "tmp_30_cast_fu_362_p1");
    sc_trace(mVcdFile, i_V_fu_397_p2, "i_V_fu_397_p2");
    sc_trace(mVcdFile, tmp_46_fu_412_p4, "tmp_46_fu_412_p4");
    sc_trace(mVcdFile, tmp_cast_fu_403_p1, "tmp_cast_fu_403_p1");
    sc_trace(mVcdFile, tmp_25_mid2_fu_454_p3, "tmp_25_mid2_fu_454_p3");
    sc_trace(mVcdFile, tmp_50_fu_548_p4, "tmp_50_fu_548_p4");
    sc_trace(mVcdFile, icmp3_fu_557_p2, "icmp3_fu_557_p2");
    sc_trace(mVcdFile, tmp_34_fu_563_p2, "tmp_34_fu_563_p2");
    sc_trace(mVcdFile, tmp25_fu_572_p2, "tmp25_fu_572_p2");
    sc_trace(mVcdFile, tmp24_fu_567_p2, "tmp24_fu_567_p2");
    sc_trace(mVcdFile, tmp_35_fu_583_p1, "tmp_35_fu_583_p1");
    sc_trace(mVcdFile, sel_tmp6_demorgan_fu_621_p2, "sel_tmp6_demorgan_fu_621_p2");
    sc_trace(mVcdFile, slt_fu_633_p2, "slt_fu_633_p2");
    sc_trace(mVcdFile, tmp_37_fu_592_p1, "tmp_37_fu_592_p1");
    sc_trace(mVcdFile, slt1_fu_644_p2, "slt1_fu_644_p2");
    sc_trace(mVcdFile, tmp_38_fu_596_p1, "tmp_38_fu_596_p1");
    sc_trace(mVcdFile, slt2_fu_655_p2, "slt2_fu_655_p2");
    sc_trace(mVcdFile, tmp_39_fu_600_p1, "tmp_39_fu_600_p1");
    sc_trace(mVcdFile, slt3_fu_666_p2, "slt3_fu_666_p2");
    sc_trace(mVcdFile, tmp_40_fu_603_p1, "tmp_40_fu_603_p1");
    sc_trace(mVcdFile, tmp_41_fu_607_p1, "tmp_41_fu_607_p1");
    sc_trace(mVcdFile, tmp_42_fu_610_p1, "tmp_42_fu_610_p1");
    sc_trace(mVcdFile, tmp_43_fu_614_p1, "tmp_43_fu_614_p1");
    sc_trace(mVcdFile, tmp_44_fu_618_p1, "tmp_44_fu_618_p1");
    sc_trace(mVcdFile, rev_fu_638_p2, "rev_fu_638_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_627_p2, "sel_tmp6_fu_627_p2");
    sc_trace(mVcdFile, rev2_fu_660_p2, "rev2_fu_660_p2");
    sc_trace(mVcdFile, rev3_fu_671_p2, "rev3_fu_671_p2");
    sc_trace(mVcdFile, tmp28_fu_708_p2, "tmp28_fu_708_p2");
    sc_trace(mVcdFile, rev1_fu_649_p2, "rev1_fu_649_p2");
    sc_trace(mVcdFile, tmp29_fu_714_p2, "tmp29_fu_714_p2");
    sc_trace(mVcdFile, tmp26_fu_702_p2, "tmp26_fu_702_p2");
    sc_trace(mVcdFile, rev4_fu_741_p2, "rev4_fu_741_p2");
    sc_trace(mVcdFile, rev5_fu_746_p2, "rev5_fu_746_p2");
    sc_trace(mVcdFile, rev7_fu_756_p2, "rev7_fu_756_p2");
    sc_trace(mVcdFile, rev8_fu_761_p2, "rev8_fu_761_p2");
    sc_trace(mVcdFile, tmp32_fu_772_p2, "tmp32_fu_772_p2");
    sc_trace(mVcdFile, rev6_fu_751_p2, "rev6_fu_751_p2");
    sc_trace(mVcdFile, tmp33_fu_778_p2, "tmp33_fu_778_p2");
    sc_trace(mVcdFile, tmp30_fu_766_p2, "tmp30_fu_766_p2");
    sc_trace(mVcdFile, tmp31_fu_784_p2, "tmp31_fu_784_p2");
    sc_trace(mVcdFile, sel_tmp4_fu_790_p2, "sel_tmp4_fu_790_p2");
    sc_trace(mVcdFile, tmp34_fu_795_p2, "tmp34_fu_795_p2");
    sc_trace(mVcdFile, tmp_55_demorgan_fu_800_p2, "tmp_55_demorgan_fu_800_p2");
    sc_trace(mVcdFile, tmp_45_fu_805_p2, "tmp_45_fu_805_p2");
    sc_trace(mVcdFile, tmp_47_fu_820_p2, "tmp_47_fu_820_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_301_p00, "grp_fu_301_p00");
    sc_trace(mVcdFile, grp_fu_301_p10, "grp_fu_301_p10");
#endif

    }
}

hysteresis::~hysteresis() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete linebuff_val_0_U;
    delete linebuff_val_1_U;
    delete canny_edge_mul_33ns_33ns_65_5_1_U63;
}

void hysteresis::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void hysteresis::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten_fu_371_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         !(esl_seteq<1,1,1>(or_cond5_fu_825_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())))) {
        indvar_flatten_reg_232 = indvar_flatten_next_reg_1013.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        indvar_flatten_reg_232 = ap_const_lv65_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         !(esl_seteq<1,1,1>(or_cond5_fu_825_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())))) {
        t_V_2_reg_254 = j_V_fu_830_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        t_V_2_reg_254 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         !(esl_seteq<1,1,1>(or_cond5_fu_825_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())))) {
        t_V_reg_243 = t_V_mid2_reg_1038.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        t_V_reg_243 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && !(esl_seteq<1,1,1>(or_cond_fu_483_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())))) {
        col_assign_mid2_reg_1043 = col_assign_mid2_fu_447_p3.read();
        or_cond_reg_1078 = or_cond_fu_483_p2.read();
        tmp_26_mid2_reg_1051 = tmp_26_mid2_fu_459_p3.read();
        tmp_27_mid2_reg_1056 = tmp_27_mid2_fu_464_p3.read();
        tmp_28_mid2_reg_1061 = tmp_28_mid2_fu_469_p3.read();
        tmp_29_reg_1071 = tmp_29_fu_478_p2.read();
        tmp_30_cast_mid2_cas_reg_1066 = tmp_30_cast_mid2_cas_fu_474_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(or_cond_fu_483_p2.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(or_cond_fu_483_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())))) {
        element_gd_1_fu_152 = src_data_stream_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_371_p2.read()))) {
        icmp2_reg_1023 = icmp2_fu_422_p2.read();
        t_V_mid2_reg_1038 = t_V_mid2_fu_439_p3.read();
        tmp_25_mid1_reg_1018 = tmp_25_mid1_fu_407_p2.read();
        tmp_27_mid1_reg_1028 = tmp_27_mid1_fu_428_p2.read();
        tmp_28_mid1_reg_1033 = tmp_28_mid1_fu_434_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        icmp_reg_986 = icmp_fu_345_p2.read();
        indvar_flatten_next_reg_1013 = indvar_flatten_next_fu_376_p2.read();
        tmp_24_reg_981 = tmp_24_fu_330_p2.read();
        tmp_26_reg_991 = tmp_26_fu_351_p2.read();
        tmp_27_reg_996 = tmp_27_fu_357_p2.read();
        tmp_28_reg_1001 = tmp_28_fu_366_p2.read();
        win_val_0_1_2_fu_124 = win_val_0_1_fu_120.read();
        win_val_0_1_2_load_reg_966 = win_val_0_1_2_fu_124.read();
        win_val_1_1_2_fu_132 = win_val_1_1_fu_128.read();
        win_val_1_1_2_load_reg_971 = win_val_1_1_2_fu_132.read();
        win_val_2_1_2_fu_140 = win_val_2_1_fu_136.read();
        win_val_2_1_2_load_reg_976 = win_val_2_1_2_fu_140.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && !(esl_seteq<1,1,1>(or_cond_fu_483_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_29_fu_478_p2.read()))) {
        linebuff_val_1_addr_reg_1082 =  (sc_lv<11>) (tmp_31_fu_494_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        or_cond4_reg_1097 = or_cond4_fu_577_p2.read();
        slt4_reg_1107 = slt4_fu_677_p2.read();
        slt5_reg_1112 = slt5_fu_682_p2.read();
        slt6_reg_1117 = slt6_fu_687_p2.read();
        slt7_reg_1122 = slt7_fu_692_p2.read();
        slt8_reg_1127 = slt8_fu_697_p2.read();
        tmp27_reg_1132 = tmp27_fu_720_p2.read();
        tmp_36_reg_1102 = tmp_36_fu_587_p2.read();
        win_val_0_1_fu_120 = win_val_0_0_0_win_va_fu_541_p3.read();
        win_val_1_1_fu_128 = win_val_1_0_0_win_va_fu_534_p3.read();
        win_val_2_1_fu_136 = win_val_2_0_0_win_va_fu_527_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        tmp0_1_fu_148 = linebuff_val_0_q0.read();
        tmp0_reg_1092 = linebuff_val_0_q0.read();
        tmp1_1_fu_144 = linebuff_val_1_q0.read();
    }
}

void hysteresis::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void hysteresis::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void hysteresis::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void hysteresis::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void hysteresis::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void hysteresis::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void hysteresis::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void hysteresis::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void hysteresis::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void hysteresis::thread_ap_block_state11() {
    ap_block_state11 = (esl_seteq<1,1,1>(or_cond5_fu_825_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read()));
}

void hysteresis::thread_ap_block_state8() {
    ap_block_state8 = (esl_seteq<1,1,1>(or_cond_fu_483_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read()));
}

void hysteresis::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten_fu_371_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void hysteresis::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void hysteresis::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten_fu_371_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void hysteresis::thread_col_assign_mid2_fu_447_p3() {
    col_assign_mid2_fu_447_p3 = (!tmp_28_reg_1001.read()[0].is_01())? sc_lv<32>(): ((tmp_28_reg_1001.read()[0].to_bool())? t_V_2_reg_254.read(): ap_const_lv32_0);
}

void hysteresis::thread_dst_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(or_cond5_fu_825_p2.read(), ap_const_lv1_0))) {
        dst_data_stream_V_blk_n = dst_data_stream_V_full_n.read();
    } else {
        dst_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void hysteresis::thread_dst_data_stream_V_din() {
    dst_data_stream_V_din = (!tmp_45_fu_805_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_45_fu_805_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void hysteresis::thread_dst_data_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(or_cond5_fu_825_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(or_cond5_fu_825_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())))) {
        dst_data_stream_V_write = ap_const_logic_1;
    } else {
        dst_data_stream_V_write = ap_const_logic_0;
    }
}

void hysteresis::thread_exitcond_flatten_fu_371_p2() {
    exitcond_flatten_fu_371_p2 = (!indvar_flatten_reg_232.read().is_01() || !grp_fu_301_p2.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_232.read() == grp_fu_301_p2.read());
}

void hysteresis::thread_grp_fu_301_p0() {
    grp_fu_301_p0 =  (sc_lv<33>) (grp_fu_301_p00.read());
}

void hysteresis::thread_grp_fu_301_p00() {
    grp_fu_301_p00 = esl_zext<65,33>(ret_V_fu_279_p2.read());
}

void hysteresis::thread_grp_fu_301_p1() {
    grp_fu_301_p1 =  (sc_lv<33>) (grp_fu_301_p10.read());
}

void hysteresis::thread_grp_fu_301_p10() {
    grp_fu_301_p10 = esl_zext<65,33>(ret_V_4_fu_289_p2.read());
}

void hysteresis::thread_i_V_fu_397_p2() {
    i_V_fu_397_p2 = (!t_V_reg_243.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_reg_243.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void hysteresis::thread_icmp2_fu_422_p2() {
    icmp2_fu_422_p2 = (!tmp_46_fu_412_p4.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_46_fu_412_p4.read() == ap_const_lv31_0);
}

void hysteresis::thread_icmp3_fu_557_p2() {
    icmp3_fu_557_p2 = (!tmp_50_fu_548_p4.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_50_fu_548_p4.read() == ap_const_lv31_0);
}

void hysteresis::thread_icmp_fu_345_p2() {
    icmp_fu_345_p2 = (!tmp_fu_335_p4.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_335_p4.read() == ap_const_lv31_0);
}

void hysteresis::thread_indvar_flatten_next_fu_376_p2() {
    indvar_flatten_next_fu_376_p2 = (!indvar_flatten_reg_232.read().is_01() || !ap_const_lv65_1.is_01())? sc_lv<65>(): (sc_biguint<65>(indvar_flatten_reg_232.read()) + sc_biguint<65>(ap_const_lv65_1));
}

void hysteresis::thread_j_V_fu_830_p2() {
    j_V_fu_830_p2 = (!col_assign_mid2_reg_1043.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(col_assign_mid2_reg_1043.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void hysteresis::thread_lhs_V_2_cast_fu_285_p1() {
    lhs_V_2_cast_fu_285_p1 = esl_zext<33,32>(src_cols_V.read());
}

void hysteresis::thread_lhs_V_cast_fu_275_p1() {
    lhs_V_cast_fu_275_p1 = esl_zext<33,32>(src_rows_V.read());
}

void hysteresis::thread_linebuff_val_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        linebuff_val_0_address0 =  (sc_lv<11>) (tmp_32_fu_514_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        linebuff_val_0_address0 =  (sc_lv<11>) (tmp_31_fu_494_p1.read());
    } else {
        linebuff_val_0_address0 = "XXXXXXXXXXX";
    }
}

void hysteresis::thread_linebuff_val_0_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          !(esl_seteq<1,1,1>(or_cond_fu_483_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read()))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        linebuff_val_0_ce0 = ap_const_logic_1;
    } else {
        linebuff_val_0_ce0 = ap_const_logic_0;
    }
}

void hysteresis::thread_linebuff_val_0_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_reg_1078.read()))) {
        linebuff_val_0_we0 = ap_const_logic_1;
    } else {
        linebuff_val_0_we0 = ap_const_logic_0;
    }
}

void hysteresis::thread_linebuff_val_1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        linebuff_val_1_address0 = linebuff_val_1_addr_reg_1082.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        linebuff_val_1_address0 =  (sc_lv<11>) (tmp_31_fu_494_p1.read());
    } else {
        linebuff_val_1_address0 = "XXXXXXXXXXX";
    }
}

void hysteresis::thread_linebuff_val_1_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          !(esl_seteq<1,1,1>(or_cond_fu_483_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read()))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        linebuff_val_1_ce0 = ap_const_logic_1;
    } else {
        linebuff_val_1_ce0 = ap_const_logic_0;
    }
}

void hysteresis::thread_linebuff_val_1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_29_reg_1071.read()))) {
        linebuff_val_1_we0 = ap_const_logic_1;
    } else {
        linebuff_val_1_we0 = ap_const_logic_0;
    }
}

void hysteresis::thread_or_cond4_fu_577_p2() {
    or_cond4_fu_577_p2 = (tmp25_fu_572_p2.read() | tmp24_fu_567_p2.read());
}

void hysteresis::thread_or_cond5_fu_825_p2() {
    or_cond5_fu_825_p2 = (tmp_47_fu_820_p2.read() | tmp_27_mid2_reg_1056.read());
}

void hysteresis::thread_or_cond_fu_483_p2() {
    or_cond_fu_483_p2 = (tmp_25_mid2_fu_454_p3.read() & tmp_29_fu_478_p2.read());
}

void hysteresis::thread_ret_V_4_fu_289_p2() {
    ret_V_4_fu_289_p2 = (!lhs_V_2_cast_fu_285_p1.read().is_01() || !ap_const_lv33_1.is_01())? sc_lv<33>(): (sc_biguint<33>(lhs_V_2_cast_fu_285_p1.read()) + sc_biguint<33>(ap_const_lv33_1));
}

void hysteresis::thread_ret_V_5_fu_312_p2() {
    ret_V_5_fu_312_p2 = (!lhs_V_2_cast_fu_285_p1.read().is_01() || !ap_const_lv33_1FFFFFFFF.is_01())? sc_lv<33>(): (sc_biguint<33>(lhs_V_2_cast_fu_285_p1.read()) + sc_bigint<33>(ap_const_lv33_1FFFFFFFF));
}

void hysteresis::thread_ret_V_fu_279_p2() {
    ret_V_fu_279_p2 = (!lhs_V_cast_fu_275_p1.read().is_01() || !ap_const_lv33_1.is_01())? sc_lv<33>(): (sc_biguint<33>(lhs_V_cast_fu_275_p1.read()) + sc_biguint<33>(ap_const_lv33_1));
}

void hysteresis::thread_rev1_fu_649_p2() {
    rev1_fu_649_p2 = (slt1_fu_644_p2.read() ^ ap_const_lv1_1);
}

void hysteresis::thread_rev2_fu_660_p2() {
    rev2_fu_660_p2 = (slt2_fu_655_p2.read() ^ ap_const_lv1_1);
}

void hysteresis::thread_rev3_fu_671_p2() {
    rev3_fu_671_p2 = (slt3_fu_666_p2.read() ^ ap_const_lv1_1);
}

void hysteresis::thread_rev4_fu_741_p2() {
    rev4_fu_741_p2 = (slt4_reg_1107.read() ^ ap_const_lv1_1);
}

void hysteresis::thread_rev5_fu_746_p2() {
    rev5_fu_746_p2 = (slt5_reg_1112.read() ^ ap_const_lv1_1);
}

void hysteresis::thread_rev6_fu_751_p2() {
    rev6_fu_751_p2 = (slt6_reg_1117.read() ^ ap_const_lv1_1);
}

void hysteresis::thread_rev7_fu_756_p2() {
    rev7_fu_756_p2 = (slt7_reg_1122.read() ^ ap_const_lv1_1);
}

void hysteresis::thread_rev8_fu_761_p2() {
    rev8_fu_761_p2 = (slt8_reg_1127.read() ^ ap_const_lv1_1);
}

void hysteresis::thread_rev_fu_638_p2() {
    rev_fu_638_p2 = (slt_fu_633_p2.read() ^ ap_const_lv1_1);
}

void hysteresis::thread_sel_tmp4_fu_790_p2() {
    sel_tmp4_fu_790_p2 = (tmp31_fu_784_p2.read() & tmp27_reg_1132.read());
}

void hysteresis::thread_sel_tmp6_demorgan_fu_621_p2() {
    sel_tmp6_demorgan_fu_621_p2 = (or_cond4_fu_577_p2.read() | tmp_36_fu_587_p2.read());
}

void hysteresis::thread_sel_tmp6_fu_627_p2() {
    sel_tmp6_fu_627_p2 = (sel_tmp6_demorgan_fu_621_p2.read() ^ ap_const_lv1_1);
}

void hysteresis::thread_slt1_fu_644_p2() {
    slt1_fu_644_p2 = (!threshold_high.read().is_01() || !tmp_37_fu_592_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(threshold_high.read()) < sc_bigint<32>(tmp_37_fu_592_p1.read()));
}

void hysteresis::thread_slt2_fu_655_p2() {
    slt2_fu_655_p2 = (!threshold_high.read().is_01() || !tmp_38_fu_596_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(threshold_high.read()) < sc_bigint<32>(tmp_38_fu_596_p1.read()));
}

void hysteresis::thread_slt3_fu_666_p2() {
    slt3_fu_666_p2 = (!threshold_high.read().is_01() || !tmp_39_fu_600_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(threshold_high.read()) < sc_bigint<32>(tmp_39_fu_600_p1.read()));
}

void hysteresis::thread_slt4_fu_677_p2() {
    slt4_fu_677_p2 = (!threshold_high.read().is_01() || !tmp_40_fu_603_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(threshold_high.read()) < sc_bigint<32>(tmp_40_fu_603_p1.read()));
}

void hysteresis::thread_slt5_fu_682_p2() {
    slt5_fu_682_p2 = (!threshold_high.read().is_01() || !tmp_41_fu_607_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(threshold_high.read()) < sc_bigint<32>(tmp_41_fu_607_p1.read()));
}

void hysteresis::thread_slt6_fu_687_p2() {
    slt6_fu_687_p2 = (!threshold_high.read().is_01() || !tmp_42_fu_610_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(threshold_high.read()) < sc_bigint<32>(tmp_42_fu_610_p1.read()));
}

void hysteresis::thread_slt7_fu_692_p2() {
    slt7_fu_692_p2 = (!threshold_high.read().is_01() || !tmp_43_fu_614_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(threshold_high.read()) < sc_bigint<32>(tmp_43_fu_614_p1.read()));
}

void hysteresis::thread_slt8_fu_697_p2() {
    slt8_fu_697_p2 = (!threshold_high.read().is_01() || !tmp_44_fu_618_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(threshold_high.read()) < sc_bigint<32>(tmp_44_fu_618_p1.read()));
}

void hysteresis::thread_slt_fu_633_p2() {
    slt_fu_633_p2 = (!threshold_high.read().is_01() || !tmp_35_fu_583_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(threshold_high.read()) < sc_bigint<32>(tmp_35_fu_583_p1.read()));
}

void hysteresis::thread_src_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(or_cond_fu_483_p2.read(), ap_const_lv1_1))) {
        src_data_stream_V_blk_n = src_data_stream_V_empty_n.read();
    } else {
        src_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void hysteresis::thread_src_data_stream_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(or_cond_fu_483_p2.read(), ap_const_lv1_1) && 
         !(esl_seteq<1,1,1>(or_cond_fu_483_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())))) {
        src_data_stream_V_read = ap_const_logic_1;
    } else {
        src_data_stream_V_read = ap_const_logic_0;
    }
}

void hysteresis::thread_t_V_mid2_fu_439_p3() {
    t_V_mid2_fu_439_p3 = (!tmp_28_fu_366_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_28_fu_366_p2.read()[0].to_bool())? t_V_reg_243.read(): i_V_fu_397_p2.read());
}

void hysteresis::thread_tmp24_fu_567_p2() {
    tmp24_fu_567_p2 = (icmp3_fu_557_p2.read() | tmp_28_mid2_reg_1061.read());
}

void hysteresis::thread_tmp25_fu_572_p2() {
    tmp25_fu_572_p2 = (tmp_26_mid2_reg_1051.read() | tmp_34_fu_563_p2.read());
}

void hysteresis::thread_tmp26_fu_702_p2() {
    tmp26_fu_702_p2 = (rev_fu_638_p2.read() & sel_tmp6_fu_627_p2.read());
}

void hysteresis::thread_tmp27_fu_720_p2() {
    tmp27_fu_720_p2 = (tmp29_fu_714_p2.read() & tmp26_fu_702_p2.read());
}

void hysteresis::thread_tmp28_fu_708_p2() {
    tmp28_fu_708_p2 = (rev2_fu_660_p2.read() & rev3_fu_671_p2.read());
}

void hysteresis::thread_tmp29_fu_714_p2() {
    tmp29_fu_714_p2 = (tmp28_fu_708_p2.read() & rev1_fu_649_p2.read());
}

void hysteresis::thread_tmp30_fu_766_p2() {
    tmp30_fu_766_p2 = (rev4_fu_741_p2.read() & rev5_fu_746_p2.read());
}

void hysteresis::thread_tmp31_fu_784_p2() {
    tmp31_fu_784_p2 = (tmp33_fu_778_p2.read() & tmp30_fu_766_p2.read());
}

void hysteresis::thread_tmp32_fu_772_p2() {
    tmp32_fu_772_p2 = (rev7_fu_756_p2.read() & rev8_fu_761_p2.read());
}

void hysteresis::thread_tmp33_fu_778_p2() {
    tmp33_fu_778_p2 = (tmp32_fu_772_p2.read() & rev6_fu_751_p2.read());
}

void hysteresis::thread_tmp34_fu_795_p2() {
    tmp34_fu_795_p2 = (or_cond4_reg_1097.read() | sel_tmp4_fu_790_p2.read());
}

void hysteresis::thread_tmp_24_fu_330_p2() {
    tmp_24_fu_330_p2 = (!t_V_reg_243.read().is_01() || !src_rows_V.read().is_01())? sc_lv<1>(): (sc_biguint<32>(t_V_reg_243.read()) < sc_biguint<32>(src_rows_V.read()));
}

void hysteresis::thread_tmp_25_mid1_fu_407_p2() {
    tmp_25_mid1_fu_407_p2 = (!i_V_fu_397_p2.read().is_01() || !src_rows_V.read().is_01())? sc_lv<1>(): (sc_biguint<32>(i_V_fu_397_p2.read()) < sc_biguint<32>(src_rows_V.read()));
}

void hysteresis::thread_tmp_25_mid2_fu_454_p3() {
    tmp_25_mid2_fu_454_p3 = (!tmp_28_reg_1001.read()[0].is_01())? sc_lv<1>(): ((tmp_28_reg_1001.read()[0].to_bool())? tmp_24_reg_981.read(): tmp_25_mid1_reg_1018.read());
}

void hysteresis::thread_tmp_26_fu_351_p2() {
    tmp_26_fu_351_p2 = (!t_V_reg_243.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(t_V_reg_243.read() == ap_const_lv32_0);
}

void hysteresis::thread_tmp_26_mid2_fu_459_p3() {
    tmp_26_mid2_fu_459_p3 = (!tmp_28_reg_1001.read()[0].is_01())? sc_lv<1>(): ((tmp_28_reg_1001.read()[0].to_bool())? icmp_reg_986.read(): icmp2_reg_1023.read());
}

void hysteresis::thread_tmp_27_fu_357_p2() {
    tmp_27_fu_357_p2 = (!tmp_cast_mid1_fu_326_p1.read().is_01() || !tmp_s_fu_307_p2.read().is_01())? sc_lv<1>(): (sc_bigint<33>(tmp_cast_mid1_fu_326_p1.read()) > sc_bigint<33>(tmp_s_fu_307_p2.read()));
}

void hysteresis::thread_tmp_27_mid1_fu_428_p2() {
    tmp_27_mid1_fu_428_p2 = (!i_V_fu_397_p2.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(i_V_fu_397_p2.read() == ap_const_lv32_0);
}

void hysteresis::thread_tmp_27_mid2_fu_464_p3() {
    tmp_27_mid2_fu_464_p3 = (!tmp_28_reg_1001.read()[0].is_01())? sc_lv<1>(): ((tmp_28_reg_1001.read()[0].to_bool())? tmp_26_reg_991.read(): tmp_27_mid1_reg_1028.read());
}

void hysteresis::thread_tmp_28_fu_366_p2() {
    tmp_28_fu_366_p2 = (!tmp_30_cast_fu_362_p1.read().is_01() || !ret_V_4_fu_289_p2.read().is_01())? sc_lv<1>(): (sc_biguint<33>(tmp_30_cast_fu_362_p1.read()) < sc_biguint<33>(ret_V_4_fu_289_p2.read()));
}

void hysteresis::thread_tmp_28_mid1_fu_434_p2() {
    tmp_28_mid1_fu_434_p2 = (!tmp_cast_fu_403_p1.read().is_01() || !tmp_s_fu_307_p2.read().is_01())? sc_lv<1>(): (sc_bigint<33>(tmp_cast_fu_403_p1.read()) > sc_bigint<33>(tmp_s_fu_307_p2.read()));
}

void hysteresis::thread_tmp_28_mid2_fu_469_p3() {
    tmp_28_mid2_fu_469_p3 = (!tmp_28_reg_1001.read()[0].is_01())? sc_lv<1>(): ((tmp_28_reg_1001.read()[0].to_bool())? tmp_27_reg_996.read(): tmp_28_mid1_reg_1033.read());
}

void hysteresis::thread_tmp_29_fu_478_p2() {
    tmp_29_fu_478_p2 = (!col_assign_mid2_fu_447_p3.read().is_01() || !src_cols_V.read().is_01())? sc_lv<1>(): (sc_biguint<32>(col_assign_mid2_fu_447_p3.read()) < sc_biguint<32>(src_cols_V.read()));
}

void hysteresis::thread_tmp_30_cast_fu_362_p1() {
    tmp_30_cast_fu_362_p1 = esl_zext<33,32>(t_V_2_reg_254.read());
}

void hysteresis::thread_tmp_30_cast_mid2_cas_fu_474_p1() {
    tmp_30_cast_mid2_cas_fu_474_p1 = esl_zext<33,32>(col_assign_mid2_fu_447_p3.read());
}

void hysteresis::thread_tmp_31_fu_494_p1() {
    tmp_31_fu_494_p1 = esl_zext<64,32>(col_assign_mid2_fu_447_p3.read());
}

void hysteresis::thread_tmp_32_fu_514_p1() {
    tmp_32_fu_514_p1 = esl_zext<64,32>(col_assign_mid2_reg_1043.read());
}

void hysteresis::thread_tmp_34_fu_563_p2() {
    tmp_34_fu_563_p2 = (!tmp_30_cast_mid2_cas_reg_1066.read().is_01() || !ret_V_5_fu_312_p2.read().is_01())? sc_lv<1>(): (sc_bigint<33>(tmp_30_cast_mid2_cas_reg_1066.read()) > sc_bigint<33>(ret_V_5_fu_312_p2.read()));
}

void hysteresis::thread_tmp_35_fu_583_p1() {
    tmp_35_fu_583_p1 = esl_zext<32,16>(win_val_1_1_fu_128.read());
}

void hysteresis::thread_tmp_36_fu_587_p2() {
    tmp_36_fu_587_p2 = (!tmp_35_fu_583_p1.read().is_01() || !threshold_low.read().is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_35_fu_583_p1.read()) < sc_bigint<32>(threshold_low.read()));
}

void hysteresis::thread_tmp_37_fu_592_p1() {
    tmp_37_fu_592_p1 = esl_zext<32,16>(win_val_0_0_0_win_va_fu_541_p3.read());
}

void hysteresis::thread_tmp_38_fu_596_p1() {
    tmp_38_fu_596_p1 = esl_zext<32,16>(win_val_0_1_fu_120.read());
}

void hysteresis::thread_tmp_39_fu_600_p1() {
    tmp_39_fu_600_p1 = esl_zext<32,16>(win_val_0_1_2_load_reg_966.read());
}

void hysteresis::thread_tmp_40_fu_603_p1() {
    tmp_40_fu_603_p1 = esl_zext<32,16>(win_val_1_0_0_win_va_fu_534_p3.read());
}

void hysteresis::thread_tmp_41_fu_607_p1() {
    tmp_41_fu_607_p1 = esl_zext<32,16>(win_val_1_1_2_load_reg_971.read());
}

void hysteresis::thread_tmp_42_fu_610_p1() {
    tmp_42_fu_610_p1 = esl_zext<32,16>(win_val_2_0_0_win_va_fu_527_p3.read());
}

void hysteresis::thread_tmp_43_fu_614_p1() {
    tmp_43_fu_614_p1 = esl_zext<32,16>(win_val_2_1_fu_136.read());
}

void hysteresis::thread_tmp_44_fu_618_p1() {
    tmp_44_fu_618_p1 = esl_zext<32,16>(win_val_2_1_2_load_reg_976.read());
}

void hysteresis::thread_tmp_45_fu_805_p2() {
    tmp_45_fu_805_p2 = (tmp_55_demorgan_fu_800_p2.read() ^ ap_const_lv1_1);
}

void hysteresis::thread_tmp_46_fu_412_p4() {
    tmp_46_fu_412_p4 = i_V_fu_397_p2.read().range(31, 1);
}

void hysteresis::thread_tmp_47_fu_820_p2() {
    tmp_47_fu_820_p2 = (!col_assign_mid2_reg_1043.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(col_assign_mid2_reg_1043.read() == ap_const_lv32_0);
}

void hysteresis::thread_tmp_50_fu_548_p4() {
    tmp_50_fu_548_p4 = col_assign_mid2_reg_1043.read().range(31, 1);
}

void hysteresis::thread_tmp_55_demorgan_fu_800_p2() {
    tmp_55_demorgan_fu_800_p2 = (tmp34_fu_795_p2.read() | tmp_36_reg_1102.read());
}

void hysteresis::thread_tmp_cast_fu_403_p1() {
    tmp_cast_fu_403_p1 = esl_zext<33,32>(i_V_fu_397_p2.read());
}

void hysteresis::thread_tmp_cast_mid1_fu_326_p1() {
    tmp_cast_mid1_fu_326_p1 = esl_zext<33,32>(t_V_reg_243.read());
}

void hysteresis::thread_tmp_fu_335_p4() {
    tmp_fu_335_p4 = t_V_reg_243.read().range(31, 1);
}

void hysteresis::thread_tmp_s_fu_307_p2() {
    tmp_s_fu_307_p2 = (!lhs_V_cast_fu_275_p1.read().is_01() || !ap_const_lv33_1FFFFFFFF.is_01())? sc_lv<33>(): (sc_biguint<33>(lhs_V_cast_fu_275_p1.read()) + sc_bigint<33>(ap_const_lv33_1FFFFFFFF));
}

void hysteresis::thread_win_val_0_0_0_win_va_fu_541_p3() {
    win_val_0_0_0_win_va_fu_541_p3 = (!tmp_29_reg_1071.read()[0].is_01())? sc_lv<16>(): ((tmp_29_reg_1071.read()[0].to_bool())? element_gd_1_fu_152.read(): win_val_0_1_fu_120.read());
}

void hysteresis::thread_win_val_1_0_0_win_va_fu_534_p3() {
    win_val_1_0_0_win_va_fu_534_p3 = (!tmp_29_reg_1071.read()[0].is_01())? sc_lv<16>(): ((tmp_29_reg_1071.read()[0].to_bool())? tmp0_1_fu_148.read(): win_val_1_1_fu_128.read());
}

void hysteresis::thread_win_val_2_0_0_win_va_fu_527_p3() {
    win_val_2_0_0_win_va_fu_527_p3 = (!tmp_29_reg_1071.read()[0].is_01())? sc_lv<16>(): ((tmp_29_reg_1071.read()[0].to_bool())? tmp1_1_fu_144.read(): win_val_2_1_fu_136.read());
}

void hysteresis::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten_fu_371_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && !(esl_seteq<1,1,1>(or_cond_fu_483_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_fu_478_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && !(esl_seteq<1,1,1>(or_cond_fu_483_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_29_fu_478_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && !(esl_seteq<1,1,1>(or_cond5_fu_825_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXX";
            break;
    }
}

}

