// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write,
        p_kernel_val_0_V_1_read,
        p_kernel_val_0_V_2_read,
        p_kernel_val_1_V_0_read,
        p_kernel_val_1_V_2_read,
        p_kernel_val_2_V_0_read,
        p_kernel_val_2_V_1_read
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp0_stage0 = 6'd16;
parameter    ap_ST_fsm_state15 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V_read;
input  [31:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [15:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;
input  [1:0] p_kernel_val_0_V_1_read;
input  [1:0] p_kernel_val_0_V_2_read;
input  [2:0] p_kernel_val_1_V_0_read;
input  [3:0] p_kernel_val_1_V_2_read;
input  [1:0] p_kernel_val_2_V_0_read;
input  [2:0] p_kernel_val_2_V_1_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_reg_1611;
reg   [0:0] or_cond_i_i_reg_1635;
reg   [0:0] icmp_reg_1512;
reg   [0:0] tmp_s_reg_1507;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter9;
reg   [0:0] or_cond_i_reg_1662;
reg   [0:0] or_cond_i_reg_1662_pp0_iter8_reg;
reg   [10:0] t_V_3_reg_330;
reg   [7:0] reg_341;
wire    ap_block_state5_pp0_stage0_iter0;
reg    ap_predicate_op179_read_state6;
reg    ap_predicate_op180_read_state6;
reg    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_state8_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state10_pp0_stage0_iter5;
wire    ap_block_state11_pp0_stage0_iter6;
wire    ap_block_state12_pp0_stage0_iter7;
wire    ap_block_state13_pp0_stage0_iter8;
reg    ap_block_state14_pp0_stage0_iter9;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] reg_341_pp0_iter2_reg;
wire   [10:0] widthloop_fu_352_p2;
wire   [10:0] tmp_77_fu_358_p1;
wire   [1:0] tmp_80_fu_366_p1;
wire   [10:0] tmp_fu_370_p2;
wire   [11:0] tmp_86_fu_376_p1;
wire   [11:0] tmp_92_fu_384_p1;
wire   [12:0] tmp_227_cast_cast_fu_402_p1;
wire   [1:0] tmp_54_fu_406_p2;
wire  signed [9:0] tmp_231_0_1_cast_fu_424_p1;
reg  signed [9:0] tmp_231_0_1_cast_reg_1453;
wire  signed [9:0] tmp_231_0_2_cast_fu_428_p1;
reg  signed [9:0] tmp_231_0_2_cast_reg_1458;
wire  signed [10:0] tmp_231_1_cast_fu_432_p1;
reg  signed [10:0] tmp_231_1_cast_reg_1463;
wire   [11:0] tmp_231_1_2_cast_fu_436_p1;
reg   [11:0] tmp_231_1_2_cast_reg_1468;
wire  signed [9:0] tmp_231_2_cast_fu_440_p1;
reg  signed [9:0] tmp_231_2_cast_reg_1473;
wire   [10:0] tmp_231_2_1_cast_fu_444_p1;
reg   [10:0] tmp_231_2_1_cast_reg_1478;
wire   [12:0] tmp_68_cast_cast_fu_462_p1;
wire   [1:0] tmp_70_fu_466_p2;
wire   [1:0] tmp_72_fu_472_p2;
wire   [10:0] i_V_fu_487_p2;
reg   [10:0] i_V_reg_1502;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_s_fu_493_p2;
wire   [0:0] exitcond1_fu_482_p2;
wire   [0:0] icmp_fu_508_p2;
wire   [0:0] tmp_59_fu_514_p2;
reg   [0:0] tmp_59_reg_1517;
wire   [0:0] tmp_190_1_fu_520_p2;
reg   [0:0] tmp_190_1_reg_1521;
wire   [0:0] tmp_62_fu_526_p2;
reg   [0:0] tmp_62_reg_1525;
wire   [11:0] tmp_67_fu_531_p2;
reg   [11:0] tmp_67_reg_1532;
reg   [0:0] tmp_99_reg_1540;
wire   [11:0] p_assign_7_fu_545_p2;
reg   [11:0] p_assign_7_reg_1545;
wire   [11:0] p_assign_6_1_fu_551_p2;
reg   [11:0] p_assign_6_1_reg_1550;
wire   [0:0] tmp_225_1_fu_579_p2;
reg   [0:0] tmp_225_1_reg_1557;
wire   [1:0] tmp_102_fu_584_p1;
reg   [1:0] tmp_102_reg_1562;
wire   [11:0] p_assign_6_2_fu_588_p2;
reg   [11:0] p_assign_6_2_reg_1568;
wire   [0:0] tmp_225_2_fu_616_p2;
reg   [0:0] tmp_225_2_reg_1575;
wire   [1:0] tmp_105_fu_621_p1;
reg   [1:0] tmp_105_reg_1580;
wire   [1:0] tmp_111_fu_732_p3;
reg   [1:0] tmp_111_reg_1586;
wire    ap_CS_fsm_state3;
wire   [1:0] row_assign_10_1_t_fu_761_p2;
reg   [1:0] row_assign_10_1_t_reg_1591;
wire   [1:0] row_assign_10_2_t_fu_787_p2;
reg   [1:0] row_assign_10_2_t_reg_1596;
wire   [0:0] tmp_146_0_not_fu_792_p2;
reg   [0:0] tmp_146_0_not_reg_1601;
wire    ap_CS_fsm_state4;
wire   [1:0] tmp_112_fu_802_p2;
reg   [1:0] tmp_112_reg_1606;
wire   [0:0] exitcond_fu_811_p2;
reg   [0:0] exitcond_reg_1611_pp0_iter1_reg;
reg   [0:0] exitcond_reg_1611_pp0_iter2_reg;
reg   [0:0] exitcond_reg_1611_pp0_iter3_reg;
reg   [0:0] exitcond_reg_1611_pp0_iter4_reg;
wire   [10:0] j_V_fu_816_p2;
reg    ap_enable_reg_pp0_iter0;
wire  signed [11:0] ImagLoc_x_fu_838_p2;
reg  signed [11:0] ImagLoc_x_reg_1620;
wire   [0:0] tmp_116_fu_844_p3;
reg   [0:0] tmp_116_reg_1625;
wire   [0:0] tmp_64_fu_858_p2;
reg   [0:0] tmp_64_reg_1630;
wire   [0:0] or_cond_i_i_fu_863_p2;
reg   [0:0] or_cond_i_i_reg_1635_pp0_iter1_reg;
reg   [0:0] or_cond_i_i_reg_1635_pp0_iter2_reg;
wire  signed [12:0] p_p2_i_i_cast_cast_fu_891_p1;
reg  signed [12:0] p_p2_i_i_cast_cast_reg_1640;
wire   [0:0] tmp_66_fu_895_p2;
reg   [0:0] tmp_66_reg_1645;
wire   [12:0] p_assign_2_fu_900_p2;
reg   [12:0] p_assign_2_reg_1650;
wire   [0:0] brmerge_fu_905_p2;
reg   [0:0] brmerge_reg_1655;
reg   [0:0] brmerge_reg_1655_pp0_iter1_reg;
wire   [0:0] or_cond_i_fu_910_p2;
reg   [0:0] or_cond_i_reg_1662_pp0_iter1_reg;
reg   [0:0] or_cond_i_reg_1662_pp0_iter2_reg;
reg   [0:0] or_cond_i_reg_1662_pp0_iter3_reg;
reg   [0:0] or_cond_i_reg_1662_pp0_iter4_reg;
reg   [0:0] or_cond_i_reg_1662_pp0_iter5_reg;
reg   [0:0] or_cond_i_reg_1662_pp0_iter6_reg;
reg   [0:0] or_cond_i_reg_1662_pp0_iter7_reg;
reg   [10:0] k_buf_0_val_3_addr_reg_1666;
wire   [1:0] col_assign_3_t_fu_961_p2;
reg   [1:0] col_assign_3_t_reg_1672;
reg   [10:0] k_buf_0_val_4_addr_reg_1679;
reg   [10:0] k_buf_0_val_4_addr_reg_1679_pp0_iter2_reg;
reg   [10:0] k_buf_0_val_5_addr_reg_1685;
reg   [10:0] k_buf_0_val_5_addr_reg_1685_pp0_iter2_reg;
wire   [7:0] k_buf_0_val_3_q0;
reg   [7:0] k_buf_0_val_3_load_reg_1691;
reg    ap_enable_reg_pp0_iter2;
wire   [7:0] col_buf_0_val_0_0_fu_995_p3;
reg   [7:0] col_buf_0_val_0_0_reg_1696;
wire   [7:0] k_buf_0_val_4_q0;
reg   [7:0] k_buf_0_val_4_load_reg_1704;
wire   [7:0] col_buf_0_val_1_0_fu_1013_p3;
reg   [7:0] col_buf_0_val_1_0_reg_1709;
wire   [7:0] col_buf_0_val_2_0_fu_1031_p3;
reg   [7:0] col_buf_0_val_2_0_reg_1717;
wire   [7:0] src_kernel_win_0_va_6_fu_1082_p3;
reg   [7:0] src_kernel_win_0_va_6_reg_1725;
reg   [7:0] src_kernel_win_0_va_6_reg_1725_pp0_iter4_reg;
reg   [7:0] src_kernel_win_0_va_6_reg_1725_pp0_iter5_reg;
reg   [7:0] src_kernel_win_0_va_6_reg_1725_pp0_iter6_reg;
wire   [7:0] src_kernel_win_0_va_7_fu_1096_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_1731;
reg   [7:0] src_kernel_win_0_va_7_reg_1731_pp0_iter4_reg;
reg   [7:0] src_kernel_win_0_va_7_reg_1731_pp0_iter5_reg;
wire   [7:0] src_kernel_win_0_va_8_fu_1110_p3;
reg   [7:0] src_kernel_win_0_va_8_reg_1737;
reg   [7:0] src_kernel_win_0_va_16_reg_1747;
reg   [7:0] src_kernel_win_0_va_16_reg_1747_pp0_iter4_reg;
reg   [7:0] src_kernel_win_0_va_9_reg_1757;
wire  signed [10:0] grp_fu_1287_p3;
reg  signed [10:0] sum_V_0_1_reg_1762;
reg    ap_enable_reg_pp0_iter5;
wire  signed [10:0] grp_fu_1294_p3;
reg  signed [10:0] sum_V_0_2_reg_1777;
reg    ap_enable_reg_pp0_iter6;
wire  signed [11:0] grp_fu_1300_p3;
reg  signed [11:0] sum_V_1_1_reg_1792;
reg    ap_enable_reg_pp0_iter7;
wire  signed [9:0] grp_fu_1307_p3;
reg  signed [9:0] tmp27_reg_1797;
(* use_dsp48 = "no" *) wire  signed [11:0] p_Val2_s_fu_1214_p2;
reg  signed [11:0] p_Val2_s_reg_1802;
reg   [0:0] p_Result_s_reg_1807;
reg   [0:0] tmp_122_reg_1814;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter3;
reg    ap_condition_pp0_exit_iter2_state7;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter8;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [10:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [10:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [10:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [10:0] t_V_reg_319;
wire    ap_CS_fsm_state15;
wire   [63:0] tmp_81_fu_954_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_150;
reg   [7:0] src_kernel_win_0_va_1_fu_154;
reg   [7:0] src_kernel_win_0_va_2_fu_158;
reg   [7:0] src_kernel_win_0_va_3_fu_162;
reg   [7:0] src_kernel_win_0_va_4_fu_166;
reg   [7:0] src_kernel_win_0_va_5_fu_170;
reg   [7:0] right_border_buf_0_s_fu_174;
reg   [7:0] right_border_buf_0_1_fu_178;
reg   [7:0] right_border_buf_0_2_fu_182;
reg   [7:0] right_border_buf_0_3_fu_186;
reg   [7:0] right_border_buf_0_4_fu_190;
reg   [7:0] right_border_buf_0_5_fu_194;
wire   [10:0] tmp_75_fu_348_p1;
wire   [11:0] tmp_50_fu_388_p3;
wire   [11:0] tmp_53_fu_396_p2;
wire   [1:0] tmp_78_fu_362_p1;
wire   [0:0] tmp_94_fu_412_p1;
wire   [11:0] tmp_55_fu_448_p3;
wire   [11:0] tmp_56_fu_456_p2;
wire   [1:0] tmp_68_fu_416_p3;
wire   [1:0] tmp_88_fu_380_p1;
wire   [9:0] tmp_97_fu_498_p4;
wire   [11:0] t_V_cast_fu_478_p1;
wire   [0:0] tmp_101_fu_557_p3;
wire   [11:0] p_assign_7_1_fu_565_p2;
wire   [11:0] p_p2_i485_i_1_fu_571_p3;
wire   [0:0] tmp_104_fu_594_p3;
wire   [11:0] p_assign_7_2_fu_602_p2;
wire   [11:0] p_p2_i485_i_2_fu_608_p3;
wire   [0:0] tmp_98_fu_625_p3;
wire   [0:0] tmp_69_fu_638_p2;
wire   [0:0] rev_fu_632_p2;
wire  signed [11:0] p_p2_i485_i_fu_648_p3;
wire  signed [12:0] p_p2_i485_i_cast_cast_fu_653_p1;
wire   [0:0] tmp_100_fu_667_p3;
wire   [0:0] tmp_216_1_fu_680_p2;
wire   [0:0] rev12_fu_674_p2;
wire   [0:0] tmp_103_fu_690_p3;
wire   [0:0] tmp_216_2_fu_703_p2;
wire   [0:0] rev13_fu_697_p2;
wire   [12:0] p_assign_8_fu_662_p2;
wire   [0:0] tmp_71_fu_657_p2;
wire   [1:0] tmp_108_fu_716_p1;
wire   [1:0] tmp_109_fu_720_p1;
wire   [0:0] or_cond_i484_i_fu_642_p2;
wire   [1:0] tmp_107_fu_713_p1;
wire   [1:0] tmp_110_fu_724_p3;
wire   [1:0] tmp_73_fu_740_p2;
wire   [0:0] or_cond_i484_i_1_fu_684_p2;
wire   [1:0] tmp_113_fu_750_p1;
wire   [1:0] tmp_74_fu_744_p3;
wire   [1:0] tmp_76_fu_753_p3;
wire   [1:0] tmp_79_fu_766_p2;
wire   [0:0] or_cond_i484_i_2_fu_707_p2;
wire   [1:0] tmp_114_fu_776_p1;
wire   [1:0] tmp_87_fu_770_p3;
wire   [1:0] tmp_89_fu_779_p3;
wire   [1:0] tmp_106_fu_797_p2;
wire   [9:0] tmp_115_fu_822_p4;
wire   [11:0] t_V_3_cast_fu_807_p1;
wire   [0:0] rev14_fu_852_p2;
wire   [0:0] tmp_117_fu_869_p3;
wire   [11:0] p_assign_1_fu_877_p2;
wire  signed [11:0] p_p2_i_i_fu_883_p3;
wire   [0:0] icmp4_fu_832_p2;
wire  signed [12:0] ImagLoc_x_cast_cast_fu_915_p1;
wire   [0:0] tmp_64_not_fu_924_p2;
wire   [0:0] sel_tmp7_fu_929_p2;
wire   [0:0] sel_tmp8_fu_934_p2;
wire   [12:0] sel_tmp_fu_918_p3;
wire  signed [12:0] x_fu_939_p3;
wire  signed [31:0] col_assign_cast_fu_946_p1;
wire   [1:0] tmp_118_fu_950_p1;
wire   [7:0] tmp_82_fu_984_p5;
wire   [7:0] tmp_83_fu_1002_p5;
wire   [7:0] tmp_84_fu_1020_p5;
wire   [7:0] tmp_85_fu_1074_p5;
wire   [7:0] tmp_90_fu_1088_p5;
wire   [7:0] tmp_91_fu_1102_p5;
wire   [8:0] r_V_0_cast_fu_1146_p1;
wire  signed [8:0] r_V_2_fu_1150_p2;
wire  signed [10:0] grp_fu_1321_p3;
wire  signed [11:0] grp_fu_1314_p3;
wire  signed [11:0] tmp26_cast_fu_1211_p1;
wire   [0:0] p_not1_i_i_fu_1238_p2;
wire   [0:0] p_Result_not_fu_1252_p2;
wire   [0:0] brmerge2_i_i_fu_1248_p2;
wire  signed [15:0] p_Val2_1_fu_1235_p1;
wire   [0:0] underflow_fu_1243_p2;
wire   [0:0] brmerge3_i_i_fu_1257_p2;
wire   [15:0] p_mux_i_i_fu_1262_p3;
wire   [15:0] p_i_i_fu_1270_p3;
wire  signed [1:0] grp_fu_1287_p0;
wire   [7:0] grp_fu_1287_p1;
wire  signed [1:0] grp_fu_1294_p0;
wire   [7:0] grp_fu_1294_p1;
wire  signed [2:0] grp_fu_1300_p0;
wire   [7:0] grp_fu_1300_p1;
wire  signed [1:0] grp_fu_1307_p0;
wire   [7:0] grp_fu_1307_p1;
wire   [7:0] grp_fu_1307_p2;
wire   [3:0] grp_fu_1314_p0;
wire   [7:0] grp_fu_1314_p1;
wire   [2:0] grp_fu_1321_p0;
wire   [7:0] grp_fu_1321_p1;
reg    grp_fu_1287_ce;
reg    grp_fu_1294_ce;
reg    grp_fu_1300_ce;
reg    grp_fu_1307_ce;
reg    grp_fu_1314_ce;
reg    grp_fu_1321_ce;
reg   [5:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_172;
reg    ap_enable_state6_pp0_iter1_stage0;
reg    ap_enable_operation_192;
reg    ap_enable_state7_pp0_iter2_stage0;
reg    ap_predicate_op201_store_state7;
reg    ap_enable_operation_201;
reg    ap_predicate_op205_store_state7;
reg    ap_enable_operation_205;
reg    ap_enable_operation_175;
reg    ap_enable_operation_195;
reg    ap_predicate_op214_store_state8;
reg    ap_enable_operation_214;
reg    ap_enable_state8_pp0_iter3_stage0;
reg    ap_predicate_op217_store_state8;
reg    ap_enable_operation_217;
reg    ap_predicate_op177_load_state6;
reg    ap_enable_operation_177;
reg    ap_predicate_op198_load_state7;
reg    ap_enable_operation_198;
reg    ap_predicate_op212_store_state8;
reg    ap_enable_operation_212;
reg    ap_predicate_op216_store_state8;
reg    ap_enable_operation_216;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [9:0] grp_fu_1287_p10;
wire   [9:0] grp_fu_1294_p10;
wire   [10:0] grp_fu_1300_p10;
wire   [9:0] grp_fu_1307_p10;
wire   [9:0] grp_fu_1307_p20;
wire   [11:0] grp_fu_1314_p10;
wire   [10:0] grp_fu_1321_p10;
reg    ap_condition_1246;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
end

Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_address1),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(reg_341)
);

Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_address1),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_address1),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

canny_edge_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
canny_edge_mux_32_8_1_1_U15(
    .din0(right_border_buf_0_s_fu_174),
    .din1(right_border_buf_0_1_fu_178),
    .din2(8'd0),
    .din3(col_assign_3_t_reg_1672),
    .dout(tmp_82_fu_984_p5)
);

canny_edge_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
canny_edge_mux_32_8_1_1_U16(
    .din0(right_border_buf_0_3_fu_186),
    .din1(right_border_buf_0_4_fu_190),
    .din2(8'd0),
    .din3(col_assign_3_t_reg_1672),
    .dout(tmp_83_fu_1002_p5)
);

canny_edge_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
canny_edge_mux_32_8_1_1_U17(
    .din0(right_border_buf_0_5_fu_194),
    .din1(right_border_buf_0_2_fu_182),
    .din2(8'd0),
    .din3(col_assign_3_t_reg_1672),
    .dout(tmp_84_fu_1020_p5)
);

canny_edge_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
canny_edge_mux_32_8_1_1_U18(
    .din0(col_buf_0_val_0_0_reg_1696),
    .din1(col_buf_0_val_1_0_reg_1709),
    .din2(col_buf_0_val_2_0_reg_1717),
    .din3(tmp_112_reg_1606),
    .dout(tmp_85_fu_1074_p5)
);

canny_edge_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
canny_edge_mux_32_8_1_1_U19(
    .din0(col_buf_0_val_0_0_reg_1696),
    .din1(col_buf_0_val_1_0_reg_1709),
    .din2(col_buf_0_val_2_0_reg_1717),
    .din3(row_assign_10_1_t_reg_1591),
    .dout(tmp_90_fu_1088_p5)
);

canny_edge_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
canny_edge_mux_32_8_1_1_U20(
    .din0(col_buf_0_val_0_0_reg_1696),
    .din1(col_buf_0_val_1_0_reg_1709),
    .din2(col_buf_0_val_2_0_reg_1717),
    .din3(row_assign_10_2_t_reg_1596),
    .dout(tmp_91_fu_1102_p5)
);

canny_edge_mac_muladd_2s_8ns_9s_11_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
canny_edge_mac_muladd_2s_8ns_9s_11_3_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1287_p0),
    .din1(grp_fu_1287_p1),
    .din2(r_V_2_fu_1150_p2),
    .ce(grp_fu_1287_ce),
    .dout(grp_fu_1287_p3)
);

canny_edge_mac_muladd_2s_8ns_11s_11_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
canny_edge_mac_muladd_2s_8ns_11s_11_3_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1294_p0),
    .din1(grp_fu_1294_p1),
    .din2(sum_V_0_1_reg_1762),
    .ce(grp_fu_1294_ce),
    .dout(grp_fu_1294_p3)
);

canny_edge_mac_muladd_3s_8ns_11s_12_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 12 ))
canny_edge_mac_muladd_3s_8ns_11s_12_3_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1300_p0),
    .din1(grp_fu_1300_p1),
    .din2(sum_V_0_2_reg_1777),
    .ce(grp_fu_1300_ce),
    .dout(grp_fu_1300_p3)
);

canny_edge_mac_muladd_2s_8ns_8ns_10_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
canny_edge_mac_muladd_2s_8ns_8ns_10_3_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1307_p0),
    .din1(grp_fu_1307_p1),
    .din2(grp_fu_1307_p2),
    .ce(grp_fu_1307_ce),
    .dout(grp_fu_1307_p3)
);

canny_edge_mac_muladd_4ns_8ns_12s_12_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 12 ))
canny_edge_mac_muladd_4ns_8ns_12s_12_3_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1314_p0),
    .din1(grp_fu_1314_p1),
    .din2(sum_V_1_1_reg_1792),
    .ce(grp_fu_1314_ce),
    .dout(grp_fu_1314_p3)
);

canny_edge_mac_muladd_3ns_8ns_10s_11_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
canny_edge_mac_muladd_3ns_8ns_10s_11_3_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1321_p0),
    .din1(grp_fu_1321_p1),
    .din2(tmp27_reg_1797),
    .ce(grp_fu_1321_ce),
    .dout(grp_fu_1321_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond_fu_811_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter2_state7)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter9 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_811_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_3_reg_330 <= j_V_fu_816_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        t_V_3_reg_330 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        t_V_reg_319 <= i_V_reg_1502;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t_V_reg_319 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_811_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ImagLoc_x_reg_1620 <= ImagLoc_x_fu_838_p2;
        brmerge_reg_1655 <= brmerge_fu_905_p2;
        or_cond_i_i_reg_1635 <= or_cond_i_i_fu_863_p2;
        or_cond_i_reg_1662 <= or_cond_i_fu_910_p2;
        p_assign_2_reg_1650 <= p_assign_2_fu_900_p2;
        p_p2_i_i_cast_cast_reg_1640 <= p_p2_i_i_cast_cast_fu_891_p1;
        tmp_116_reg_1625 <= ImagLoc_x_fu_838_p2[32'd11];
        tmp_64_reg_1630 <= tmp_64_fu_858_p2;
        tmp_66_reg_1645 <= tmp_66_fu_895_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_1655_pp0_iter1_reg <= brmerge_reg_1655;
        exitcond_reg_1611 <= exitcond_fu_811_p2;
        exitcond_reg_1611_pp0_iter1_reg <= exitcond_reg_1611;
        or_cond_i_i_reg_1635_pp0_iter1_reg <= or_cond_i_i_reg_1635;
        or_cond_i_reg_1662_pp0_iter1_reg <= or_cond_i_reg_1662;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_1611 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        col_assign_3_t_reg_1672 <= col_assign_3_t_fu_961_p2;
        k_buf_0_val_3_addr_reg_1666 <= tmp_81_fu_954_p1;
        k_buf_0_val_4_addr_reg_1679 <= tmp_81_fu_954_p1;
        k_buf_0_val_5_addr_reg_1685 <= tmp_81_fu_954_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_1611_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        col_buf_0_val_0_0_reg_1696 <= col_buf_0_val_0_0_fu_995_p3;
        col_buf_0_val_1_0_reg_1709 <= col_buf_0_val_1_0_fu_1013_p3;
        col_buf_0_val_2_0_reg_1717 <= col_buf_0_val_2_0_fu_1031_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond_reg_1611_pp0_iter2_reg <= exitcond_reg_1611_pp0_iter1_reg;
        exitcond_reg_1611_pp0_iter3_reg <= exitcond_reg_1611_pp0_iter2_reg;
        exitcond_reg_1611_pp0_iter4_reg <= exitcond_reg_1611_pp0_iter3_reg;
        k_buf_0_val_4_addr_reg_1679_pp0_iter2_reg <= k_buf_0_val_4_addr_reg_1679;
        k_buf_0_val_5_addr_reg_1685_pp0_iter2_reg <= k_buf_0_val_5_addr_reg_1685;
        or_cond_i_i_reg_1635_pp0_iter2_reg <= or_cond_i_i_reg_1635_pp0_iter1_reg;
        or_cond_i_reg_1662_pp0_iter2_reg <= or_cond_i_reg_1662_pp0_iter1_reg;
        or_cond_i_reg_1662_pp0_iter3_reg <= or_cond_i_reg_1662_pp0_iter2_reg;
        or_cond_i_reg_1662_pp0_iter4_reg <= or_cond_i_reg_1662_pp0_iter3_reg;
        or_cond_i_reg_1662_pp0_iter5_reg <= or_cond_i_reg_1662_pp0_iter4_reg;
        or_cond_i_reg_1662_pp0_iter6_reg <= or_cond_i_reg_1662_pp0_iter5_reg;
        or_cond_i_reg_1662_pp0_iter7_reg <= or_cond_i_reg_1662_pp0_iter6_reg;
        or_cond_i_reg_1662_pp0_iter8_reg <= or_cond_i_reg_1662_pp0_iter7_reg;
        reg_341_pp0_iter2_reg <= reg_341;
        src_kernel_win_0_va_16_reg_1747_pp0_iter4_reg <= src_kernel_win_0_va_16_reg_1747;
        src_kernel_win_0_va_6_reg_1725 <= src_kernel_win_0_va_6_fu_1082_p3;
        src_kernel_win_0_va_6_reg_1725_pp0_iter4_reg <= src_kernel_win_0_va_6_reg_1725;
        src_kernel_win_0_va_6_reg_1725_pp0_iter5_reg <= src_kernel_win_0_va_6_reg_1725_pp0_iter4_reg;
        src_kernel_win_0_va_6_reg_1725_pp0_iter6_reg <= src_kernel_win_0_va_6_reg_1725_pp0_iter5_reg;
        src_kernel_win_0_va_7_reg_1731 <= src_kernel_win_0_va_7_fu_1096_p3;
        src_kernel_win_0_va_7_reg_1731_pp0_iter4_reg <= src_kernel_win_0_va_7_reg_1731;
        src_kernel_win_0_va_7_reg_1731_pp0_iter5_reg <= src_kernel_win_0_va_7_reg_1731_pp0_iter4_reg;
        src_kernel_win_0_va_8_reg_1737 <= src_kernel_win_0_va_8_fu_1110_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_1502 <= i_V_fu_487_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_482_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_reg_1512 <= icmp_fu_508_p2;
        p_assign_6_1_reg_1550 <= p_assign_6_1_fu_551_p2;
        p_assign_6_2_reg_1568 <= p_assign_6_2_fu_588_p2;
        p_assign_7_reg_1545 <= p_assign_7_fu_545_p2;
        tmp_102_reg_1562 <= tmp_102_fu_584_p1;
        tmp_105_reg_1580 <= tmp_105_fu_621_p1;
        tmp_190_1_reg_1521 <= tmp_190_1_fu_520_p2;
        tmp_225_1_reg_1557 <= tmp_225_1_fu_579_p2;
        tmp_225_2_reg_1575 <= tmp_225_2_fu_616_p2;
        tmp_59_reg_1517 <= tmp_59_fu_514_p2;
        tmp_62_reg_1525 <= tmp_62_fu_526_p2;
        tmp_67_reg_1532 <= tmp_67_fu_531_p2;
        tmp_99_reg_1540 <= tmp_67_fu_531_p2[32'd11];
        tmp_s_reg_1507 <= tmp_s_fu_493_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_1611_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_load_reg_1691 <= k_buf_0_val_3_q0;
        k_buf_0_val_4_load_reg_1704 <= k_buf_0_val_4_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1662_pp0_iter7_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Result_s_reg_1807 <= p_Val2_s_fu_1214_p2[32'd11];
        p_Val2_s_reg_1802 <= p_Val2_s_fu_1214_p2;
        tmp_122_reg_1814 <= p_Val2_s_fu_1214_p2[32'd11];
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op180_read_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op179_read_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_341 <= p_src_data_stream_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1) & (or_cond_i_i_reg_1635_pp0_iter1_reg == 1'd1) & (exitcond_reg_1611_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_0_1_fu_178 <= right_border_buf_0_s_fu_174;
        right_border_buf_0_2_fu_182 <= right_border_buf_0_5_fu_194;
        right_border_buf_0_3_fu_186 <= col_buf_0_val_1_0_fu_1013_p3;
        right_border_buf_0_4_fu_190 <= right_border_buf_0_3_fu_186;
        right_border_buf_0_5_fu_194 <= col_buf_0_val_2_0_fu_1031_p3;
        right_border_buf_0_s_fu_174 <= col_buf_0_val_0_0_fu_995_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_62_reg_1525 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        row_assign_10_1_t_reg_1591 <= row_assign_10_1_t_fu_761_p2;
        row_assign_10_2_t_reg_1596 <= row_assign_10_2_t_fu_787_p2;
        tmp_111_reg_1586 <= tmp_111_fu_732_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_1611_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_16_reg_1747 <= src_kernel_win_0_va_4_fu_166;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_1611_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_1_fu_154 <= src_kernel_win_0_va_fu_150;
        src_kernel_win_0_va_2_fu_158 <= src_kernel_win_0_va_7_reg_1731_pp0_iter4_reg;
        src_kernel_win_0_va_3_fu_162 <= src_kernel_win_0_va_2_fu_158;
        src_kernel_win_0_va_5_fu_170 <= src_kernel_win_0_va_16_reg_1747_pp0_iter4_reg;
        src_kernel_win_0_va_fu_150 <= src_kernel_win_0_va_6_reg_1725_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_1611_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_4_fu_166 <= src_kernel_win_0_va_8_fu_1110_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1662_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_9_reg_1757 <= src_kernel_win_0_va_fu_150;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1662_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_V_0_1_reg_1762 <= grp_fu_1287_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1662_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_V_0_2_reg_1777 <= grp_fu_1294_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1662_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_V_1_1_reg_1792 <= grp_fu_1300_p3;
        tmp27_reg_1797 <= grp_fu_1307_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_62_reg_1525 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_112_reg_1606 <= tmp_112_fu_802_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_146_0_not_reg_1601 <= tmp_146_0_not_fu_792_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_231_0_1_cast_reg_1453 <= tmp_231_0_1_cast_fu_424_p1;
        tmp_231_0_2_cast_reg_1458 <= tmp_231_0_2_cast_fu_428_p1;
        tmp_231_1_2_cast_reg_1468[3 : 0] <= tmp_231_1_2_cast_fu_436_p1[3 : 0];
        tmp_231_1_cast_reg_1463 <= tmp_231_1_cast_fu_432_p1;
        tmp_231_2_1_cast_reg_1478[2 : 0] <= tmp_231_2_1_cast_fu_444_p1[2 : 0];
        tmp_231_2_cast_reg_1473 <= tmp_231_2_cast_fu_440_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_condition_pp0_exit_iter2_state7 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state7 = 1'b0;
    end
end

always @ (*) begin
    if ((((exitcond1_fu_482_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_482_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1287_ce = 1'b1;
    end else begin
        grp_fu_1287_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1294_ce = 1'b1;
    end else begin
        grp_fu_1294_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1300_ce = 1'b1;
    end else begin
        grp_fu_1300_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1307_ce = 1'b1;
    end else begin
        grp_fu_1307_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1314_ce = 1'b1;
    end else begin
        grp_fu_1314_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1321_ce = 1'b1;
    end else begin
        grp_fu_1321_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1) & (or_cond_i_i_reg_1635_pp0_iter1_reg == 1'd1) & (exitcond_reg_1611_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond_i_i_reg_1635_pp0_iter1_reg == 1'd1) & (tmp_59_reg_1517 == 1'd1) & (icmp_reg_1512 == 1'd0) & (exitcond_reg_1611_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1) & (or_cond_i_i_reg_1635_pp0_iter1_reg == 1'd1) & (exitcond_reg_1611_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond_i_i_reg_1635_pp0_iter1_reg == 1'd1) & (tmp_59_reg_1517 == 1'd1) & (icmp_reg_1512 == 1'd0) & (exitcond_reg_1611_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1) & (or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1) & (tmp_190_1_reg_1521 == 1'd1) & (icmp_reg_1512 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1246)) begin
        if (((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_load_reg_1691;
        end else if (((tmp_190_1_reg_1521 == 1'd1) & (icmp_reg_1512 == 1'd0))) begin
            k_buf_0_val_4_d1 = reg_341_pp0_iter2_reg;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1) & (or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1) & (tmp_190_1_reg_1521 == 1'd1) & (icmp_reg_1512 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1) & (or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1) & (tmp_59_reg_1517 == 1'd1) & (icmp_reg_1512 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1246)) begin
        if (((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_load_reg_1704;
        end else if (((tmp_59_reg_1517 == 1'd1) & (icmp_reg_1512 == 1'd0))) begin
            k_buf_0_val_5_d1 = reg_341_pp0_iter2_reg;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1) & (or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1) & (tmp_59_reg_1517 == 1'd1) & (icmp_reg_1512 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_1662_pp0_iter8_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_1662_pp0_iter8_reg == 1'd1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1) & (or_cond_i_i_reg_1635 == 1'd1) & (exitcond_reg_1611 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((or_cond_i_i_reg_1635 == 1'd1) & (icmp_reg_1512 == 1'd0) & (exitcond_reg_1611 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op180_read_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op179_read_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond1_fu_482_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) & ~((ap_enable_reg_pp0_iter8 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter9 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter8 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_cast_cast_fu_915_p1 = ImagLoc_x_reg_1620;

assign ImagLoc_x_fu_838_p2 = ($signed(12'd4095) + $signed(t_V_3_cast_fu_807_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((or_cond_i_reg_1662_pp0_iter8_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op180_read_state6 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op179_read_state6 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((or_cond_i_reg_1662_pp0_iter8_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op180_read_state6 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op179_read_state6 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((or_cond_i_reg_1662_pp0_iter8_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op180_read_state6 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op179_read_state6 == 1'b1)))));
end

assign ap_block_state10_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state14_pp0_stage0_iter9 = ((or_cond_i_reg_1662_pp0_iter8_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter1 = (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op180_read_state6 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op179_read_state6 == 1'b1)));
end

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1246 = ((or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

always @ (*) begin
    ap_enable_operation_172 = (exitcond_reg_1611 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_175 = (exitcond_reg_1611 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_177 = (ap_predicate_op177_load_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_192 = (exitcond_reg_1611_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_195 = (exitcond_reg_1611_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_198 = (ap_predicate_op198_load_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_201 = (ap_predicate_op201_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_205 = (ap_predicate_op205_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_212 = (ap_predicate_op212_store_state8 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_214 = (ap_predicate_op214_store_state8 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_216 = (ap_predicate_op216_store_state8 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_217 = (ap_predicate_op217_store_state8 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state6_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state7_pp0_iter2_stage0 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_enable_state8_pp0_iter3_stage0 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

always @ (*) begin
    ap_predicate_op177_load_state6 = ((brmerge_reg_1655 == 1'd1) & (exitcond_reg_1611 == 1'd0));
end

always @ (*) begin
    ap_predicate_op179_read_state6 = ((or_cond_i_i_reg_1635 == 1'd1) & (icmp_reg_1512 == 1'd0) & (exitcond_reg_1611 == 1'd0));
end

always @ (*) begin
    ap_predicate_op180_read_state6 = ((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1) & (or_cond_i_i_reg_1635 == 1'd1) & (exitcond_reg_1611 == 1'd0));
end

always @ (*) begin
    ap_predicate_op198_load_state7 = ((brmerge_reg_1655_pp0_iter1_reg == 1'd1) & (exitcond_reg_1611_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op201_store_state7 = ((or_cond_i_i_reg_1635_pp0_iter1_reg == 1'd1) & (tmp_59_reg_1517 == 1'd1) & (icmp_reg_1512 == 1'd0) & (exitcond_reg_1611_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op205_store_state7 = ((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1) & (or_cond_i_i_reg_1635_pp0_iter1_reg == 1'd1) & (exitcond_reg_1611_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op212_store_state8 = ((or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1) & (tmp_59_reg_1517 == 1'd1) & (icmp_reg_1512 == 1'd0));
end

always @ (*) begin
    ap_predicate_op214_store_state8 = ((or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1) & (tmp_190_1_reg_1521 == 1'd1) & (icmp_reg_1512 == 1'd0));
end

always @ (*) begin
    ap_predicate_op216_store_state8 = ((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1) & (or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op217_store_state8 = ((tmp_s_reg_1507 == 1'd1) & (icmp_reg_1512 == 1'd1) & (or_cond_i_i_reg_1635_pp0_iter2_reg == 1'd1));
end

assign brmerge2_i_i_fu_1248_p2 = (tmp_122_reg_1814 ^ p_Result_s_reg_1807);

assign brmerge3_i_i_fu_1257_p2 = (tmp_122_reg_1814 | p_Result_not_fu_1252_p2);

assign brmerge_fu_905_p2 = (tmp_64_fu_858_p2 | tmp_146_0_not_reg_1601);

assign col_assign_3_t_fu_961_p2 = (tmp_72_fu_472_p2 - tmp_118_fu_950_p1);

assign col_assign_cast_fu_946_p1 = x_fu_939_p3;

assign col_buf_0_val_0_0_fu_995_p3 = ((brmerge_reg_1655_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_82_fu_984_p5);

assign col_buf_0_val_1_0_fu_1013_p3 = ((brmerge_reg_1655_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_83_fu_1002_p5);

assign col_buf_0_val_2_0_fu_1031_p3 = ((brmerge_reg_1655_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_84_fu_1020_p5);

assign exitcond1_fu_482_p2 = ((t_V_reg_319 == tmp_fu_370_p2) ? 1'b1 : 1'b0);

assign exitcond_fu_811_p2 = ((t_V_3_reg_330 == widthloop_fu_352_p2) ? 1'b1 : 1'b0);

assign grp_fu_1287_p0 = tmp_231_0_1_cast_reg_1453;

assign grp_fu_1287_p1 = grp_fu_1287_p10;

assign grp_fu_1287_p10 = src_kernel_win_0_va_4_fu_166;

assign grp_fu_1294_p0 = tmp_231_0_2_cast_reg_1458;

assign grp_fu_1294_p1 = grp_fu_1294_p10;

assign grp_fu_1294_p10 = src_kernel_win_0_va_8_reg_1737;

assign grp_fu_1300_p0 = tmp_231_1_cast_reg_1463;

assign grp_fu_1300_p1 = grp_fu_1300_p10;

assign grp_fu_1300_p10 = src_kernel_win_0_va_3_fu_162;

assign grp_fu_1307_p0 = tmp_231_2_cast_reg_1473;

assign grp_fu_1307_p1 = grp_fu_1307_p10;

assign grp_fu_1307_p10 = src_kernel_win_0_va_1_fu_154;

assign grp_fu_1307_p2 = grp_fu_1307_p20;

assign grp_fu_1307_p20 = src_kernel_win_0_va_6_reg_1725_pp0_iter6_reg;

assign grp_fu_1314_p0 = tmp_231_1_2_cast_reg_1468;

assign grp_fu_1314_p1 = grp_fu_1314_p10;

assign grp_fu_1314_p10 = src_kernel_win_0_va_7_reg_1731_pp0_iter5_reg;

assign grp_fu_1321_p0 = tmp_231_2_1_cast_reg_1478;

assign grp_fu_1321_p1 = grp_fu_1321_p10;

assign grp_fu_1321_p10 = src_kernel_win_0_va_9_reg_1757;

assign i_V_fu_487_p2 = (t_V_reg_319 + 11'd1);

assign icmp4_fu_832_p2 = ((tmp_115_fu_822_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_fu_508_p2 = ((tmp_97_fu_498_p4 != 10'd0) ? 1'b1 : 1'b0);

assign j_V_fu_816_p2 = (t_V_3_reg_330 + 11'd1);

assign k_buf_0_val_3_address0 = tmp_81_fu_954_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_1666;

assign k_buf_0_val_4_address0 = tmp_81_fu_954_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_1679_pp0_iter2_reg;

assign k_buf_0_val_5_address0 = tmp_81_fu_954_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_1685_pp0_iter2_reg;

assign or_cond_i484_i_1_fu_684_p2 = (tmp_216_1_fu_680_p2 & rev12_fu_674_p2);

assign or_cond_i484_i_2_fu_707_p2 = (tmp_216_2_fu_703_p2 & rev13_fu_697_p2);

assign or_cond_i484_i_fu_642_p2 = (tmp_69_fu_638_p2 & rev_fu_632_p2);

assign or_cond_i_fu_910_p2 = (icmp_reg_1512 & icmp4_fu_832_p2);

assign or_cond_i_i_fu_863_p2 = (tmp_64_fu_858_p2 & rev14_fu_852_p2);

assign p_Result_not_fu_1252_p2 = (p_Result_s_reg_1807 ^ 1'd1);

assign p_Val2_1_fu_1235_p1 = p_Val2_s_reg_1802;

assign p_Val2_s_fu_1214_p2 = ($signed(grp_fu_1314_p3) + $signed(tmp26_cast_fu_1211_p1));

assign p_assign_1_fu_877_p2 = (12'd1 - t_V_3_cast_fu_807_p1);

assign p_assign_2_fu_900_p2 = ($signed(tmp_68_cast_cast_fu_462_p1) - $signed(p_p2_i_i_cast_cast_fu_891_p1));

assign p_assign_6_1_fu_551_p2 = ($signed(t_V_cast_fu_478_p1) + $signed(12'd4094));

assign p_assign_6_2_fu_588_p2 = ($signed(t_V_cast_fu_478_p1) + $signed(12'd4093));

assign p_assign_7_1_fu_565_p2 = (12'd2 - t_V_cast_fu_478_p1);

assign p_assign_7_2_fu_602_p2 = (12'd3 - t_V_cast_fu_478_p1);

assign p_assign_7_fu_545_p2 = (12'd1 - t_V_cast_fu_478_p1);

assign p_assign_8_fu_662_p2 = ($signed(tmp_227_cast_cast_fu_402_p1) - $signed(p_p2_i485_i_cast_cast_fu_653_p1));

assign p_dst_data_stream_V_din = ((brmerge3_i_i_fu_1257_p2[0:0] === 1'b1) ? p_mux_i_i_fu_1262_p3 : p_i_i_fu_1270_p3);

assign p_i_i_fu_1270_p3 = ((underflow_fu_1243_p2[0:0] === 1'b1) ? 16'd32768 : p_Val2_1_fu_1235_p1);

assign p_mux_i_i_fu_1262_p3 = ((brmerge2_i_i_fu_1248_p2[0:0] === 1'b1) ? 16'd32767 : p_Val2_1_fu_1235_p1);

assign p_not1_i_i_fu_1238_p2 = (tmp_122_reg_1814 ^ 1'd1);

assign p_p2_i485_i_1_fu_571_p3 = ((tmp_101_fu_557_p3[0:0] === 1'b1) ? p_assign_7_1_fu_565_p2 : p_assign_6_1_fu_551_p2);

assign p_p2_i485_i_2_fu_608_p3 = ((tmp_104_fu_594_p3[0:0] === 1'b1) ? p_assign_7_2_fu_602_p2 : p_assign_6_2_fu_588_p2);

assign p_p2_i485_i_cast_cast_fu_653_p1 = p_p2_i485_i_fu_648_p3;

assign p_p2_i485_i_fu_648_p3 = ((tmp_99_reg_1540[0:0] === 1'b1) ? p_assign_7_reg_1545 : tmp_67_reg_1532);

assign p_p2_i_i_cast_cast_fu_891_p1 = p_p2_i_i_fu_883_p3;

assign p_p2_i_i_fu_883_p3 = ((tmp_117_fu_869_p3[0:0] === 1'b1) ? p_assign_1_fu_877_p2 : ImagLoc_x_fu_838_p2);

assign r_V_0_cast_fu_1146_p1 = src_kernel_win_0_va_5_fu_170;

assign r_V_2_fu_1150_p2 = (9'd0 - r_V_0_cast_fu_1146_p1);

assign rev12_fu_674_p2 = (tmp_100_fu_667_p3 ^ 1'd1);

assign rev13_fu_697_p2 = (tmp_103_fu_690_p3 ^ 1'd1);

assign rev14_fu_852_p2 = (tmp_116_fu_844_p3 ^ 1'd1);

assign rev_fu_632_p2 = (tmp_98_fu_625_p3 ^ 1'd1);

assign row_assign_10_1_t_fu_761_p2 = (tmp_54_fu_406_p2 - tmp_76_fu_753_p3);

assign row_assign_10_2_t_fu_787_p2 = (tmp_54_fu_406_p2 - tmp_89_fu_779_p3);

assign sel_tmp7_fu_929_p2 = (tmp_64_not_fu_924_p2 | tmp_116_reg_1625);

assign sel_tmp8_fu_934_p2 = (tmp_66_reg_1645 & sel_tmp7_fu_929_p2);

assign sel_tmp_fu_918_p3 = ((or_cond_i_i_reg_1635[0:0] === 1'b1) ? ImagLoc_x_cast_cast_fu_915_p1 : p_assign_2_reg_1650);

assign src_kernel_win_0_va_6_fu_1082_p3 = ((tmp_62_reg_1525[0:0] === 1'b1) ? tmp_85_fu_1074_p5 : col_buf_0_val_0_0_reg_1696);

assign src_kernel_win_0_va_7_fu_1096_p3 = ((tmp_62_reg_1525[0:0] === 1'b1) ? tmp_90_fu_1088_p5 : col_buf_0_val_1_0_reg_1709);

assign src_kernel_win_0_va_8_fu_1110_p3 = ((tmp_62_reg_1525[0:0] === 1'b1) ? tmp_91_fu_1102_p5 : col_buf_0_val_2_0_reg_1717);

assign t_V_3_cast_fu_807_p1 = t_V_3_reg_330;

assign t_V_cast_fu_478_p1 = t_V_reg_319;

assign tmp26_cast_fu_1211_p1 = grp_fu_1321_p3;

assign tmp_100_fu_667_p3 = p_assign_6_1_reg_1550[32'd11];

assign tmp_101_fu_557_p3 = p_assign_6_1_fu_551_p2[32'd11];

assign tmp_102_fu_584_p1 = p_p2_i485_i_1_fu_571_p3[1:0];

assign tmp_103_fu_690_p3 = p_assign_6_2_reg_1568[32'd11];

assign tmp_104_fu_594_p3 = p_assign_6_2_fu_588_p2[32'd11];

assign tmp_105_fu_621_p1 = p_p2_i485_i_2_fu_608_p3[1:0];

assign tmp_106_fu_797_p2 = ($signed(tmp_80_fu_366_p1) + $signed(2'd3));

assign tmp_107_fu_713_p1 = tmp_67_reg_1532[1:0];

assign tmp_108_fu_716_p1 = p_p2_i485_i_fu_648_p3[1:0];

assign tmp_109_fu_720_p1 = p_assign_8_fu_662_p2[1:0];

assign tmp_110_fu_724_p3 = ((tmp_71_fu_657_p2[0:0] === 1'b1) ? tmp_108_fu_716_p1 : tmp_109_fu_720_p1);

assign tmp_111_fu_732_p3 = ((or_cond_i484_i_fu_642_p2[0:0] === 1'b1) ? tmp_107_fu_713_p1 : tmp_110_fu_724_p3);

assign tmp_112_fu_802_p2 = (tmp_106_fu_797_p2 - tmp_111_reg_1586);

assign tmp_113_fu_750_p1 = p_assign_6_1_reg_1550[1:0];

assign tmp_114_fu_776_p1 = p_assign_6_2_reg_1568[1:0];

assign tmp_115_fu_822_p4 = {{t_V_3_reg_330[10:1]}};

assign tmp_116_fu_844_p3 = ImagLoc_x_fu_838_p2[32'd11];

assign tmp_117_fu_869_p3 = ImagLoc_x_fu_838_p2[32'd11];

assign tmp_118_fu_950_p1 = x_fu_939_p3[1:0];

assign tmp_146_0_not_fu_792_p2 = (tmp_s_reg_1507 ^ 1'd1);

assign tmp_190_1_fu_520_p2 = ((t_V_reg_319 == 11'd0) ? 1'b1 : 1'b0);

assign tmp_216_1_fu_680_p2 = (($signed(p_assign_6_1_reg_1550) < $signed(tmp_92_fu_384_p1)) ? 1'b1 : 1'b0);

assign tmp_216_2_fu_703_p2 = (($signed(p_assign_6_2_reg_1568) < $signed(tmp_92_fu_384_p1)) ? 1'b1 : 1'b0);

assign tmp_225_1_fu_579_p2 = (($signed(p_p2_i485_i_1_fu_571_p3) < $signed(tmp_92_fu_384_p1)) ? 1'b1 : 1'b0);

assign tmp_225_2_fu_616_p2 = (($signed(p_p2_i485_i_2_fu_608_p3) < $signed(tmp_92_fu_384_p1)) ? 1'b1 : 1'b0);

assign tmp_227_cast_cast_fu_402_p1 = tmp_53_fu_396_p2;

assign tmp_231_0_1_cast_fu_424_p1 = $signed(p_kernel_val_0_V_1_read);

assign tmp_231_0_2_cast_fu_428_p1 = $signed(p_kernel_val_0_V_2_read);

assign tmp_231_1_2_cast_fu_436_p1 = p_kernel_val_1_V_2_read;

assign tmp_231_1_cast_fu_432_p1 = $signed(p_kernel_val_1_V_0_read);

assign tmp_231_2_1_cast_fu_444_p1 = p_kernel_val_2_V_1_read;

assign tmp_231_2_cast_fu_440_p1 = $signed(p_kernel_val_2_V_0_read);

assign tmp_50_fu_388_p3 = {{tmp_77_fu_358_p1}, {1'd0}};

assign tmp_53_fu_396_p2 = (12'd2 + tmp_50_fu_388_p3);

assign tmp_54_fu_406_p2 = ($signed(2'd3) + $signed(tmp_78_fu_362_p1));

assign tmp_55_fu_448_p3 = {{tmp_75_fu_348_p1}, {1'd0}};

assign tmp_56_fu_456_p2 = ($signed(12'd4094) + $signed(tmp_55_fu_448_p3));

assign tmp_59_fu_514_p2 = ((t_V_reg_319 == 11'd1) ? 1'b1 : 1'b0);

assign tmp_62_fu_526_p2 = ((t_V_reg_319 > tmp_77_fu_358_p1) ? 1'b1 : 1'b0);

assign tmp_64_fu_858_p2 = (($signed(ImagLoc_x_fu_838_p2) < $signed(tmp_86_fu_376_p1)) ? 1'b1 : 1'b0);

assign tmp_64_not_fu_924_p2 = (tmp_64_reg_1630 ^ 1'd1);

assign tmp_66_fu_895_p2 = (($signed(p_p2_i_i_fu_883_p3) < $signed(tmp_86_fu_376_p1)) ? 1'b1 : 1'b0);

assign tmp_67_fu_531_p2 = ($signed(t_V_cast_fu_478_p1) + $signed(12'd4095));

assign tmp_68_cast_cast_fu_462_p1 = tmp_56_fu_456_p2;

assign tmp_68_fu_416_p3 = {{tmp_94_fu_412_p1}, {1'd0}};

assign tmp_69_fu_638_p2 = (($signed(tmp_67_reg_1532) < $signed(tmp_92_fu_384_p1)) ? 1'b1 : 1'b0);

assign tmp_70_fu_466_p2 = (tmp_68_fu_416_p3 ^ 2'd2);

assign tmp_71_fu_657_p2 = (($signed(p_p2_i485_i_fu_648_p3) < $signed(tmp_92_fu_384_p1)) ? 1'b1 : 1'b0);

assign tmp_72_fu_472_p2 = ($signed(2'd3) + $signed(tmp_88_fu_380_p1));

assign tmp_73_fu_740_p2 = (tmp_70_fu_466_p2 - tmp_102_reg_1562);

assign tmp_74_fu_744_p3 = ((tmp_225_1_reg_1557[0:0] === 1'b1) ? tmp_102_reg_1562 : tmp_73_fu_740_p2);

assign tmp_75_fu_348_p1 = p_src_cols_V_read[10:0];

assign tmp_76_fu_753_p3 = ((or_cond_i484_i_1_fu_684_p2[0:0] === 1'b1) ? tmp_113_fu_750_p1 : tmp_74_fu_744_p3);

assign tmp_77_fu_358_p1 = p_src_rows_V_read[10:0];

assign tmp_78_fu_362_p1 = p_src_rows_V_read[1:0];

assign tmp_79_fu_766_p2 = (tmp_70_fu_466_p2 - tmp_105_reg_1580);

assign tmp_80_fu_366_p1 = p_src_rows_V_read[1:0];

assign tmp_81_fu_954_p1 = $unsigned(col_assign_cast_fu_946_p1);

assign tmp_86_fu_376_p1 = p_src_cols_V_read[11:0];

assign tmp_87_fu_770_p3 = ((tmp_225_2_reg_1575[0:0] === 1'b1) ? tmp_105_reg_1580 : tmp_79_fu_766_p2);

assign tmp_88_fu_380_p1 = p_src_cols_V_read[1:0];

assign tmp_89_fu_779_p3 = ((or_cond_i484_i_2_fu_707_p2[0:0] === 1'b1) ? tmp_114_fu_776_p1 : tmp_87_fu_770_p3);

assign tmp_92_fu_384_p1 = p_src_rows_V_read[11:0];

assign tmp_94_fu_412_p1 = p_src_rows_V_read[0:0];

assign tmp_97_fu_498_p4 = {{t_V_reg_319[10:1]}};

assign tmp_98_fu_625_p3 = tmp_67_reg_1532[32'd11];

assign tmp_fu_370_p2 = (11'd2 + tmp_77_fu_358_p1);

assign tmp_s_fu_493_p2 = ((t_V_reg_319 < tmp_77_fu_358_p1) ? 1'b1 : 1'b0);

assign underflow_fu_1243_p2 = (p_not1_i_i_fu_1238_p2 & p_Result_s_reg_1807);

assign widthloop_fu_352_p2 = (11'd2 + tmp_75_fu_348_p1);

assign x_fu_939_p3 = ((sel_tmp8_fu_934_p2[0:0] === 1'b1) ? p_p2_i_i_cast_cast_reg_1640 : sel_tmp_fu_918_p3);

always @ (posedge ap_clk) begin
    tmp_231_1_2_cast_reg_1468[11:4] <= 8'b00000000;
    tmp_231_2_1_cast_reg_1478[10:3] <= 8'b00000000;
end

endmodule //Filter2D
